// flow-typed signature: cd035d692ef7921c6e04eb2ec48ba843
// flow-typed version: <<STUB>>/@michaelmior/js-sql-parser_v^1.3.0/flow_v0.158.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@michaelmior/js-sql-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@michaelmior/js-sql-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@michaelmior/js-sql-parser/dist/parser/sqlParser' {
  declare module.exports: any;
}

// Filename aliases
declare module '@michaelmior/js-sql-parser/dist/parser/sqlParser.js' {
  declare module.exports: $Exports<'@michaelmior/js-sql-parser/dist/parser/sqlParser'>;
}
