// flow-typed signature: 0d3151942baab7e80cc08f7147cdcb48
// flow-typed version: <<STUB>>/@sentry/browser_v^7.60.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@sentry/browser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@sentry/browser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@sentry/browser/cjs/client' {
  declare module.exports: any;
}

declare module '@sentry/browser/cjs/eventbuilder' {
  declare module.exports: any;
}

declare module '@sentry/browser/cjs/helpers' {
  declare module.exports: any;
}

declare module '@sentry/browser/cjs' {
  declare module.exports: any;
}

declare module '@sentry/browser/cjs/integrations/breadcrumbs' {
  declare module.exports: any;
}

declare module '@sentry/browser/cjs/integrations/dedupe' {
  declare module.exports: any;
}

declare module '@sentry/browser/cjs/integrations/globalhandlers' {
  declare module.exports: any;
}

declare module '@sentry/browser/cjs/integrations/httpcontext' {
  declare module.exports: any;
}

declare module '@sentry/browser/cjs/integrations' {
  declare module.exports: any;
}

declare module '@sentry/browser/cjs/integrations/linkederrors' {
  declare module.exports: any;
}

declare module '@sentry/browser/cjs/integrations/trycatch' {
  declare module.exports: any;
}

declare module '@sentry/browser/cjs/profiling/hubextensions' {
  declare module.exports: any;
}

declare module '@sentry/browser/cjs/profiling/integration' {
  declare module.exports: any;
}

declare module '@sentry/browser/cjs/profiling/utils' {
  declare module.exports: any;
}

declare module '@sentry/browser/cjs/sdk' {
  declare module.exports: any;
}

declare module '@sentry/browser/cjs/stack-parsers' {
  declare module.exports: any;
}

declare module '@sentry/browser/cjs/transports/fetch' {
  declare module.exports: any;
}

declare module '@sentry/browser/cjs/transports/offline' {
  declare module.exports: any;
}

declare module '@sentry/browser/cjs/transports/utils' {
  declare module.exports: any;
}

declare module '@sentry/browser/cjs/transports/xhr' {
  declare module.exports: any;
}

declare module '@sentry/browser/cjs/userfeedback' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/client' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/eventbuilder' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/helpers' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/integrations/breadcrumbs' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/integrations/dedupe' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/integrations/globalhandlers' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/integrations/httpcontext' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/integrations' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/integrations/linkederrors' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/integrations/trycatch' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/profiling/hubextensions' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/profiling/integration' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/profiling/utils' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/sdk' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/stack-parsers' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/transports/fetch' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/transports/offline' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/transports/utils' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/transports/xhr' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/userfeedback' {
  declare module.exports: any;
}

// Filename aliases
declare module '@sentry/browser/cjs/client.js' {
  declare module.exports: $Exports<'@sentry/browser/cjs/client'>;
}
declare module '@sentry/browser/cjs/eventbuilder.js' {
  declare module.exports: $Exports<'@sentry/browser/cjs/eventbuilder'>;
}
declare module '@sentry/browser/cjs/helpers.js' {
  declare module.exports: $Exports<'@sentry/browser/cjs/helpers'>;
}
declare module '@sentry/browser/cjs/index' {
  declare module.exports: $Exports<'@sentry/browser/cjs'>;
}
declare module '@sentry/browser/cjs/index.js' {
  declare module.exports: $Exports<'@sentry/browser/cjs'>;
}
declare module '@sentry/browser/cjs/integrations/breadcrumbs.js' {
  declare module.exports: $Exports<'@sentry/browser/cjs/integrations/breadcrumbs'>;
}
declare module '@sentry/browser/cjs/integrations/dedupe.js' {
  declare module.exports: $Exports<'@sentry/browser/cjs/integrations/dedupe'>;
}
declare module '@sentry/browser/cjs/integrations/globalhandlers.js' {
  declare module.exports: $Exports<'@sentry/browser/cjs/integrations/globalhandlers'>;
}
declare module '@sentry/browser/cjs/integrations/httpcontext.js' {
  declare module.exports: $Exports<'@sentry/browser/cjs/integrations/httpcontext'>;
}
declare module '@sentry/browser/cjs/integrations/index' {
  declare module.exports: $Exports<'@sentry/browser/cjs/integrations'>;
}
declare module '@sentry/browser/cjs/integrations/index.js' {
  declare module.exports: $Exports<'@sentry/browser/cjs/integrations'>;
}
declare module '@sentry/browser/cjs/integrations/linkederrors.js' {
  declare module.exports: $Exports<'@sentry/browser/cjs/integrations/linkederrors'>;
}
declare module '@sentry/browser/cjs/integrations/trycatch.js' {
  declare module.exports: $Exports<'@sentry/browser/cjs/integrations/trycatch'>;
}
declare module '@sentry/browser/cjs/profiling/hubextensions.js' {
  declare module.exports: $Exports<'@sentry/browser/cjs/profiling/hubextensions'>;
}
declare module '@sentry/browser/cjs/profiling/integration.js' {
  declare module.exports: $Exports<'@sentry/browser/cjs/profiling/integration'>;
}
declare module '@sentry/browser/cjs/profiling/utils.js' {
  declare module.exports: $Exports<'@sentry/browser/cjs/profiling/utils'>;
}
declare module '@sentry/browser/cjs/sdk.js' {
  declare module.exports: $Exports<'@sentry/browser/cjs/sdk'>;
}
declare module '@sentry/browser/cjs/stack-parsers.js' {
  declare module.exports: $Exports<'@sentry/browser/cjs/stack-parsers'>;
}
declare module '@sentry/browser/cjs/transports/fetch.js' {
  declare module.exports: $Exports<'@sentry/browser/cjs/transports/fetch'>;
}
declare module '@sentry/browser/cjs/transports/offline.js' {
  declare module.exports: $Exports<'@sentry/browser/cjs/transports/offline'>;
}
declare module '@sentry/browser/cjs/transports/utils.js' {
  declare module.exports: $Exports<'@sentry/browser/cjs/transports/utils'>;
}
declare module '@sentry/browser/cjs/transports/xhr.js' {
  declare module.exports: $Exports<'@sentry/browser/cjs/transports/xhr'>;
}
declare module '@sentry/browser/cjs/userfeedback.js' {
  declare module.exports: $Exports<'@sentry/browser/cjs/userfeedback'>;
}
declare module '@sentry/browser/esm/client.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/client'>;
}
declare module '@sentry/browser/esm/eventbuilder.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/eventbuilder'>;
}
declare module '@sentry/browser/esm/helpers.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/helpers'>;
}
declare module '@sentry/browser/esm/index' {
  declare module.exports: $Exports<'@sentry/browser/esm'>;
}
declare module '@sentry/browser/esm/index.js' {
  declare module.exports: $Exports<'@sentry/browser/esm'>;
}
declare module '@sentry/browser/esm/integrations/breadcrumbs.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/integrations/breadcrumbs'>;
}
declare module '@sentry/browser/esm/integrations/dedupe.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/integrations/dedupe'>;
}
declare module '@sentry/browser/esm/integrations/globalhandlers.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/integrations/globalhandlers'>;
}
declare module '@sentry/browser/esm/integrations/httpcontext.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/integrations/httpcontext'>;
}
declare module '@sentry/browser/esm/integrations/index' {
  declare module.exports: $Exports<'@sentry/browser/esm/integrations'>;
}
declare module '@sentry/browser/esm/integrations/index.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/integrations'>;
}
declare module '@sentry/browser/esm/integrations/linkederrors.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/integrations/linkederrors'>;
}
declare module '@sentry/browser/esm/integrations/trycatch.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/integrations/trycatch'>;
}
declare module '@sentry/browser/esm/profiling/hubextensions.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/profiling/hubextensions'>;
}
declare module '@sentry/browser/esm/profiling/integration.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/profiling/integration'>;
}
declare module '@sentry/browser/esm/profiling/utils.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/profiling/utils'>;
}
declare module '@sentry/browser/esm/sdk.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/sdk'>;
}
declare module '@sentry/browser/esm/stack-parsers.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/stack-parsers'>;
}
declare module '@sentry/browser/esm/transports/fetch.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/transports/fetch'>;
}
declare module '@sentry/browser/esm/transports/offline.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/transports/offline'>;
}
declare module '@sentry/browser/esm/transports/utils.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/transports/utils'>;
}
declare module '@sentry/browser/esm/transports/xhr.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/transports/xhr'>;
}
declare module '@sentry/browser/esm/userfeedback.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/userfeedback'>;
}
