// flow-typed signature: ebeebd97e9ae4d20669ad5c92def5a20
// flow-typed version: <<STUB>>/@sentry/browser_v^6.15.0/flow_v0.164.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@sentry/browser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@sentry/browser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@sentry/browser/build/bundle.es6' {
  declare module.exports: any;
}

declare module '@sentry/browser/build/bundle.es6.min' {
  declare module.exports: any;
}

declare module '@sentry/browser/build/bundle' {
  declare module.exports: any;
}

declare module '@sentry/browser/build/bundle.min' {
  declare module.exports: any;
}

declare module '@sentry/browser/dist/backend' {
  declare module.exports: any;
}

declare module '@sentry/browser/dist/client' {
  declare module.exports: any;
}

declare module '@sentry/browser/dist/eventbuilder' {
  declare module.exports: any;
}

declare module '@sentry/browser/dist/exports' {
  declare module.exports: any;
}

declare module '@sentry/browser/dist/helpers' {
  declare module.exports: any;
}

declare module '@sentry/browser/dist' {
  declare module.exports: any;
}

declare module '@sentry/browser/dist/integrations/breadcrumbs' {
  declare module.exports: any;
}

declare module '@sentry/browser/dist/integrations/dedupe' {
  declare module.exports: any;
}

declare module '@sentry/browser/dist/integrations/globalhandlers' {
  declare module.exports: any;
}

declare module '@sentry/browser/dist/integrations' {
  declare module.exports: any;
}

declare module '@sentry/browser/dist/integrations/linkederrors' {
  declare module.exports: any;
}

declare module '@sentry/browser/dist/integrations/trycatch' {
  declare module.exports: any;
}

declare module '@sentry/browser/dist/integrations/useragent' {
  declare module.exports: any;
}

declare module '@sentry/browser/dist/parsers' {
  declare module.exports: any;
}

declare module '@sentry/browser/dist/sdk' {
  declare module.exports: any;
}

declare module '@sentry/browser/dist/tracekit' {
  declare module.exports: any;
}

declare module '@sentry/browser/dist/transports/base' {
  declare module.exports: any;
}

declare module '@sentry/browser/dist/transports/fetch' {
  declare module.exports: any;
}

declare module '@sentry/browser/dist/transports' {
  declare module.exports: any;
}

declare module '@sentry/browser/dist/transports/utils' {
  declare module.exports: any;
}

declare module '@sentry/browser/dist/transports/xhr' {
  declare module.exports: any;
}

declare module '@sentry/browser/dist/version' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/backend' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/client' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/eventbuilder' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/exports' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/helpers' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/integrations/breadcrumbs' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/integrations/dedupe' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/integrations/globalhandlers' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/integrations' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/integrations/linkederrors' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/integrations/trycatch' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/integrations/useragent' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/parsers' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/sdk' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/tracekit' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/transports/base' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/transports/fetch' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/transports' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/transports/utils' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/transports/xhr' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/version' {
  declare module.exports: any;
}

// Filename aliases
declare module '@sentry/browser/build/bundle.es6.js' {
  declare module.exports: $Exports<'@sentry/browser/build/bundle.es6'>;
}
declare module '@sentry/browser/build/bundle.es6.min.js' {
  declare module.exports: $Exports<'@sentry/browser/build/bundle.es6.min'>;
}
declare module '@sentry/browser/build/bundle.js' {
  declare module.exports: $Exports<'@sentry/browser/build/bundle'>;
}
declare module '@sentry/browser/build/bundle.min.js' {
  declare module.exports: $Exports<'@sentry/browser/build/bundle.min'>;
}
declare module '@sentry/browser/dist/backend.js' {
  declare module.exports: $Exports<'@sentry/browser/dist/backend'>;
}
declare module '@sentry/browser/dist/client.js' {
  declare module.exports: $Exports<'@sentry/browser/dist/client'>;
}
declare module '@sentry/browser/dist/eventbuilder.js' {
  declare module.exports: $Exports<'@sentry/browser/dist/eventbuilder'>;
}
declare module '@sentry/browser/dist/exports.js' {
  declare module.exports: $Exports<'@sentry/browser/dist/exports'>;
}
declare module '@sentry/browser/dist/helpers.js' {
  declare module.exports: $Exports<'@sentry/browser/dist/helpers'>;
}
declare module '@sentry/browser/dist/index' {
  declare module.exports: $Exports<'@sentry/browser/dist'>;
}
declare module '@sentry/browser/dist/index.js' {
  declare module.exports: $Exports<'@sentry/browser/dist'>;
}
declare module '@sentry/browser/dist/integrations/breadcrumbs.js' {
  declare module.exports: $Exports<'@sentry/browser/dist/integrations/breadcrumbs'>;
}
declare module '@sentry/browser/dist/integrations/dedupe.js' {
  declare module.exports: $Exports<'@sentry/browser/dist/integrations/dedupe'>;
}
declare module '@sentry/browser/dist/integrations/globalhandlers.js' {
  declare module.exports: $Exports<'@sentry/browser/dist/integrations/globalhandlers'>;
}
declare module '@sentry/browser/dist/integrations/index' {
  declare module.exports: $Exports<'@sentry/browser/dist/integrations'>;
}
declare module '@sentry/browser/dist/integrations/index.js' {
  declare module.exports: $Exports<'@sentry/browser/dist/integrations'>;
}
declare module '@sentry/browser/dist/integrations/linkederrors.js' {
  declare module.exports: $Exports<'@sentry/browser/dist/integrations/linkederrors'>;
}
declare module '@sentry/browser/dist/integrations/trycatch.js' {
  declare module.exports: $Exports<'@sentry/browser/dist/integrations/trycatch'>;
}
declare module '@sentry/browser/dist/integrations/useragent.js' {
  declare module.exports: $Exports<'@sentry/browser/dist/integrations/useragent'>;
}
declare module '@sentry/browser/dist/parsers.js' {
  declare module.exports: $Exports<'@sentry/browser/dist/parsers'>;
}
declare module '@sentry/browser/dist/sdk.js' {
  declare module.exports: $Exports<'@sentry/browser/dist/sdk'>;
}
declare module '@sentry/browser/dist/tracekit.js' {
  declare module.exports: $Exports<'@sentry/browser/dist/tracekit'>;
}
declare module '@sentry/browser/dist/transports/base.js' {
  declare module.exports: $Exports<'@sentry/browser/dist/transports/base'>;
}
declare module '@sentry/browser/dist/transports/fetch.js' {
  declare module.exports: $Exports<'@sentry/browser/dist/transports/fetch'>;
}
declare module '@sentry/browser/dist/transports/index' {
  declare module.exports: $Exports<'@sentry/browser/dist/transports'>;
}
declare module '@sentry/browser/dist/transports/index.js' {
  declare module.exports: $Exports<'@sentry/browser/dist/transports'>;
}
declare module '@sentry/browser/dist/transports/utils.js' {
  declare module.exports: $Exports<'@sentry/browser/dist/transports/utils'>;
}
declare module '@sentry/browser/dist/transports/xhr.js' {
  declare module.exports: $Exports<'@sentry/browser/dist/transports/xhr'>;
}
declare module '@sentry/browser/dist/version.js' {
  declare module.exports: $Exports<'@sentry/browser/dist/version'>;
}
declare module '@sentry/browser/esm/backend.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/backend'>;
}
declare module '@sentry/browser/esm/client.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/client'>;
}
declare module '@sentry/browser/esm/eventbuilder.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/eventbuilder'>;
}
declare module '@sentry/browser/esm/exports.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/exports'>;
}
declare module '@sentry/browser/esm/helpers.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/helpers'>;
}
declare module '@sentry/browser/esm/index' {
  declare module.exports: $Exports<'@sentry/browser/esm'>;
}
declare module '@sentry/browser/esm/index.js' {
  declare module.exports: $Exports<'@sentry/browser/esm'>;
}
declare module '@sentry/browser/esm/integrations/breadcrumbs.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/integrations/breadcrumbs'>;
}
declare module '@sentry/browser/esm/integrations/dedupe.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/integrations/dedupe'>;
}
declare module '@sentry/browser/esm/integrations/globalhandlers.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/integrations/globalhandlers'>;
}
declare module '@sentry/browser/esm/integrations/index' {
  declare module.exports: $Exports<'@sentry/browser/esm/integrations'>;
}
declare module '@sentry/browser/esm/integrations/index.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/integrations'>;
}
declare module '@sentry/browser/esm/integrations/linkederrors.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/integrations/linkederrors'>;
}
declare module '@sentry/browser/esm/integrations/trycatch.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/integrations/trycatch'>;
}
declare module '@sentry/browser/esm/integrations/useragent.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/integrations/useragent'>;
}
declare module '@sentry/browser/esm/parsers.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/parsers'>;
}
declare module '@sentry/browser/esm/sdk.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/sdk'>;
}
declare module '@sentry/browser/esm/tracekit.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/tracekit'>;
}
declare module '@sentry/browser/esm/transports/base.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/transports/base'>;
}
declare module '@sentry/browser/esm/transports/fetch.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/transports/fetch'>;
}
declare module '@sentry/browser/esm/transports/index' {
  declare module.exports: $Exports<'@sentry/browser/esm/transports'>;
}
declare module '@sentry/browser/esm/transports/index.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/transports'>;
}
declare module '@sentry/browser/esm/transports/utils.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/transports/utils'>;
}
declare module '@sentry/browser/esm/transports/xhr.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/transports/xhr'>;
}
declare module '@sentry/browser/esm/version.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/version'>;
}
