// flow-typed signature: 28cd4ec581858b0f9a42d171a64087c4
// flow-typed version: <<STUB>>/@sentry/cli_v^2.32.1/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@sentry/cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@sentry/cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@sentry/cli/js/helper' {
  declare module.exports: any;
}

declare module '@sentry/cli/js' {
  declare module.exports: any;
}

declare module '@sentry/cli/js/logger' {
  declare module.exports: any;
}

declare module '@sentry/cli/js/releases' {
  declare module.exports: any;
}

declare module '@sentry/cli/js/releases/options/deploys' {
  declare module.exports: any;
}

declare module '@sentry/cli/js/releases/options/uploadSourcemaps' {
  declare module.exports: any;
}

declare module '@sentry/cli/scripts/install' {
  declare module.exports: any;
}

declare module '@sentry/cli/scripts/test-vercel-nft' {
  declare module.exports: any;
}

// Filename aliases
declare module '@sentry/cli/js/helper.js' {
  declare module.exports: $Exports<'@sentry/cli/js/helper'>;
}
declare module '@sentry/cli/js/index' {
  declare module.exports: $Exports<'@sentry/cli/js'>;
}
declare module '@sentry/cli/js/index.js' {
  declare module.exports: $Exports<'@sentry/cli/js'>;
}
declare module '@sentry/cli/js/logger.js' {
  declare module.exports: $Exports<'@sentry/cli/js/logger'>;
}
declare module '@sentry/cli/js/releases/index' {
  declare module.exports: $Exports<'@sentry/cli/js/releases'>;
}
declare module '@sentry/cli/js/releases/index.js' {
  declare module.exports: $Exports<'@sentry/cli/js/releases'>;
}
declare module '@sentry/cli/js/releases/options/deploys.js' {
  declare module.exports: $Exports<'@sentry/cli/js/releases/options/deploys'>;
}
declare module '@sentry/cli/js/releases/options/uploadSourcemaps.js' {
  declare module.exports: $Exports<'@sentry/cli/js/releases/options/uploadSourcemaps'>;
}
declare module '@sentry/cli/scripts/install.js' {
  declare module.exports: $Exports<'@sentry/cli/scripts/install'>;
}
declare module '@sentry/cli/scripts/test-vercel-nft.js' {
  declare module.exports: $Exports<'@sentry/cli/scripts/test-vercel-nft'>;
}
