// flow-typed signature: ec3519b15f755a5dbd37c333d76fe085
// flow-typed version: <<STUB>>/@welldone-software/why-did-you-render_v^6.2.3/flow_v0.164.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@welldone-software/why-did-you-render'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@welldone-software/why-did-you-render' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@welldone-software/why-did-you-render/dist/whyDidYouRender' {
  declare module.exports: any;
}

declare module '@welldone-software/why-did-you-render/jsx-dev-runtime' {
  declare module.exports: any;
}

declare module '@welldone-software/why-did-you-render/jsx-runtime' {
  declare module.exports: any;
}

// Filename aliases
declare module '@welldone-software/why-did-you-render/dist/whyDidYouRender.js' {
  declare module.exports: $Exports<'@welldone-software/why-did-you-render/dist/whyDidYouRender'>;
}
declare module '@welldone-software/why-did-you-render/jsx-dev-runtime.js' {
  declare module.exports: $Exports<'@welldone-software/why-did-you-render/jsx-dev-runtime'>;
}
declare module '@welldone-software/why-did-you-render/jsx-runtime.js' {
  declare module.exports: $Exports<'@welldone-software/why-did-you-render/jsx-runtime'>;
}
