// flow-typed signature: 2228b1803d8338ed578fedcf99b3594b
// flow-typed version: <<STUB>>/chromatic_v^6.5.3/flow_v0.174.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chromatic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chromatic' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chromatic/isChromatic' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chromatic/isChromatic.js' {
  declare module.exports: $Exports<'chromatic/isChromatic'>;
}
