// flow-typed signature: f00268a32272d2550d93cdc23b0aae4c
// flow-typed version: <<STUB>>/eslint-plugin-yaml_v^0.5.0/flow_v0.165.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-yaml'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-yaml' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-yaml/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-yaml/lib/index' {
  declare module.exports: $Exports<'eslint-plugin-yaml/lib'>;
}
declare module 'eslint-plugin-yaml/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-yaml/lib'>;
}
