// flow-typed signature: bc7561a2642281a75693702fe5eb28b1
// flow-typed version: <<STUB>>/eslint-plugin-yaml_v^1.1.3/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-yaml'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-yaml' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-yaml/dist' {
  declare module.exports: any;
}

declare module 'eslint-plugin-yaml/dist/YamlLang' {
  declare module.exports: any;
}

declare module 'eslint-plugin-yaml/dist/YamlProcessor' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-yaml/dist/index' {
  declare module.exports: $Exports<'eslint-plugin-yaml/dist'>;
}
declare module 'eslint-plugin-yaml/dist/index.js' {
  declare module.exports: $Exports<'eslint-plugin-yaml/dist'>;
}
declare module 'eslint-plugin-yaml/dist/YamlLang.js' {
  declare module.exports: $Exports<'eslint-plugin-yaml/dist/YamlLang'>;
}
declare module 'eslint-plugin-yaml/dist/YamlProcessor.js' {
  declare module.exports: $Exports<'eslint-plugin-yaml/dist/YamlProcessor'>;
}
