// flow-typed signature: e09f3e52c0a9193514c3847556df37f5
// flow-typed version: <<STUB>>/fast-equals_v^6.0.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fast-equals'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fast-equals' {
  declare module.exports: any;
}
