// flow-typed signature: bab0b199d91ce56a358dfae70469983e
// flow-typed version: <<STUB>>/fast-equals_v^4.0.1/flow_v0.183.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fast-equals'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fast-equals' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fast-equals/dist/fast-equals.cjs' {
  declare module.exports: any;
}

declare module 'fast-equals/dist/fast-equals.esm' {
  declare module.exports: any;
}

declare module 'fast-equals/dist/fast-equals' {
  declare module.exports: any;
}

declare module 'fast-equals/dist/fast-equals.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fast-equals/dist/fast-equals.cjs.js' {
  declare module.exports: $Exports<'fast-equals/dist/fast-equals.cjs'>;
}
declare module 'fast-equals/dist/fast-equals.esm.js' {
  declare module.exports: $Exports<'fast-equals/dist/fast-equals.esm'>;
}
declare module 'fast-equals/dist/fast-equals.js' {
  declare module.exports: $Exports<'fast-equals/dist/fast-equals'>;
}
declare module 'fast-equals/dist/fast-equals.min.js' {
  declare module.exports: $Exports<'fast-equals/dist/fast-equals.min'>;
}
