// flow-typed signature: cbf012230133c355c4817496a253c81b
// flow-typed version: <<STUB>>/fromentries_v^1.3.2/flow_v0.191.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fromentries'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fromentries' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'fromentries/index' {
  declare module.exports: $Exports<'fromentries'>;
}
declare module 'fromentries/index.js' {
  declare module.exports: $Exports<'fromentries'>;
}
