// flow-typed signature: 0a00fc4d10f05e6bb8e6b87983f65305
// flow-typed version: <<STUB>>/jest-each_v^29.6.2/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-each'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-each' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-each/build/bind' {
  declare module.exports: any;
}

declare module 'jest-each/build' {
  declare module.exports: any;
}

declare module 'jest-each/build/table/array' {
  declare module.exports: any;
}

declare module 'jest-each/build/table/interpolation' {
  declare module.exports: any;
}

declare module 'jest-each/build/table/template' {
  declare module.exports: any;
}

declare module 'jest-each/build/validation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-each/build/bind.js' {
  declare module.exports: $Exports<'jest-each/build/bind'>;
}
declare module 'jest-each/build/index' {
  declare module.exports: $Exports<'jest-each/build'>;
}
declare module 'jest-each/build/index.js' {
  declare module.exports: $Exports<'jest-each/build'>;
}
declare module 'jest-each/build/table/array.js' {
  declare module.exports: $Exports<'jest-each/build/table/array'>;
}
declare module 'jest-each/build/table/interpolation.js' {
  declare module.exports: $Exports<'jest-each/build/table/interpolation'>;
}
declare module 'jest-each/build/table/template.js' {
  declare module.exports: $Exports<'jest-each/build/table/template'>;
}
declare module 'jest-each/build/validation.js' {
  declare module.exports: $Exports<'jest-each/build/validation'>;
}
