// flow-typed signature: f09c5022af04450eda3cd9d534eab9b3
// flow-typed version: <<STUB>>/markdownlint-cli_v^0.28.1/flow_v0.160.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'markdownlint-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'markdownlint-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'markdownlint-cli/markdownlint' {
  declare module.exports: any;
}

// Filename aliases
declare module 'markdownlint-cli/markdownlint.js' {
  declare module.exports: $Exports<'markdownlint-cli/markdownlint'>;
}
