// flow-typed signature: bafec03128f398fec2d975f457975fdc
// flow-typed version: <<STUB>>/npm-package-json-lint_v^6.4.0/flow_v0.196.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'npm-package-json-lint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'npm-package-json-lint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'npm-package-json-lint/dist/api' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/cli' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/bin-type' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/bundledDependencies-type' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/config-type' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/cpu-type' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/dependencies-type' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/description-format' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/description-type' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/devDependencies-type' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/directories-type' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/engines-type' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/files-type' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/homepage-type' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/keywords-type' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/license-type' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/main-type' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/man-type' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/name-format' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/name-type' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/no-absolute-version-dependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/no-absolute-version-devDependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/no-archive-dependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/no-archive-devDependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/no-caret-version-dependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/no-caret-version-devDependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/no-duplicate-properties' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/no-file-dependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/no-file-devDependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/no-git-dependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/no-git-devDependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/no-repeated-dependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/no-restricted-dependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/no-restricted-devDependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/no-restricted-pre-release-dependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/no-restricted-pre-release-devDependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/no-tilde-version-dependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/no-tilde-version-devDependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/optionalDependencies-type' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/os-type' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/peerDependencies-type' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/prefer-absolute-version-dependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/prefer-absolute-version-devDependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/prefer-alphabetical-bundledDependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/prefer-alphabetical-dependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/prefer-alphabetical-devDependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/prefer-alphabetical-optionalDependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/prefer-alphabetical-peerDependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/prefer-alphabetical-scripts' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/prefer-caret-version-dependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/prefer-caret-version-devDependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/prefer-no-contributors' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/prefer-no-dependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/prefer-no-devDependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/prefer-no-engineStrict' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/prefer-no-optionalDependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/prefer-no-peerDependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/prefer-no-version-zero-dependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/prefer-no-version-zero-devDependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/prefer-property-order' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/prefer-scripts' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/prefer-tilde-version-dependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/prefer-tilde-version-devDependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/preferGlobal-type' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/private-type' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/repository-type' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/require-author' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/require-bin' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/require-bugs' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/require-bundledDependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/require-config' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/require-contributors' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/require-cpu' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/require-dependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/require-description' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/require-devDependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/require-directories' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/require-engines' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/require-files' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/require-funding' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/require-homepage' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/require-keywords' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/require-license' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/require-main' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/require-man' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/require-module' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/require-name' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/require-optionalDependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/require-os' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/require-peerDependencies' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/require-preferGlobal' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/require-private' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/require-publishConfig' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/require-repository-directory' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/require-repository' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/require-scripts' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/require-types' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/require-typings' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/require-version' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/scripts-type' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/valid-values-author' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/valid-values-engines' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/valid-values-license' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/valid-values-name-scope' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/valid-values-private' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/valid-values-publishConfig' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/version-format' {
  declare module.exports: any;
}

declare module 'npm-package-json-lint/dist/rules/version-type' {
  declare module.exports: any;
}

// Filename aliases
declare module 'npm-package-json-lint/dist/api.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/api'>;
}
declare module 'npm-package-json-lint/dist/cli.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/cli'>;
}
declare module 'npm-package-json-lint/dist/rules/bin-type.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/bin-type'>;
}
declare module 'npm-package-json-lint/dist/rules/bundledDependencies-type.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/bundledDependencies-type'>;
}
declare module 'npm-package-json-lint/dist/rules/config-type.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/config-type'>;
}
declare module 'npm-package-json-lint/dist/rules/cpu-type.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/cpu-type'>;
}
declare module 'npm-package-json-lint/dist/rules/dependencies-type.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/dependencies-type'>;
}
declare module 'npm-package-json-lint/dist/rules/description-format.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/description-format'>;
}
declare module 'npm-package-json-lint/dist/rules/description-type.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/description-type'>;
}
declare module 'npm-package-json-lint/dist/rules/devDependencies-type.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/devDependencies-type'>;
}
declare module 'npm-package-json-lint/dist/rules/directories-type.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/directories-type'>;
}
declare module 'npm-package-json-lint/dist/rules/engines-type.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/engines-type'>;
}
declare module 'npm-package-json-lint/dist/rules/files-type.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/files-type'>;
}
declare module 'npm-package-json-lint/dist/rules/homepage-type.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/homepage-type'>;
}
declare module 'npm-package-json-lint/dist/rules/keywords-type.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/keywords-type'>;
}
declare module 'npm-package-json-lint/dist/rules/license-type.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/license-type'>;
}
declare module 'npm-package-json-lint/dist/rules/main-type.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/main-type'>;
}
declare module 'npm-package-json-lint/dist/rules/man-type.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/man-type'>;
}
declare module 'npm-package-json-lint/dist/rules/name-format.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/name-format'>;
}
declare module 'npm-package-json-lint/dist/rules/name-type.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/name-type'>;
}
declare module 'npm-package-json-lint/dist/rules/no-absolute-version-dependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/no-absolute-version-dependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/no-absolute-version-devDependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/no-absolute-version-devDependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/no-archive-dependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/no-archive-dependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/no-archive-devDependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/no-archive-devDependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/no-caret-version-dependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/no-caret-version-dependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/no-caret-version-devDependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/no-caret-version-devDependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/no-duplicate-properties.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/no-duplicate-properties'>;
}
declare module 'npm-package-json-lint/dist/rules/no-file-dependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/no-file-dependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/no-file-devDependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/no-file-devDependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/no-git-dependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/no-git-dependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/no-git-devDependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/no-git-devDependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/no-repeated-dependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/no-repeated-dependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/no-restricted-dependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/no-restricted-dependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/no-restricted-devDependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/no-restricted-devDependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/no-restricted-pre-release-dependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/no-restricted-pre-release-dependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/no-restricted-pre-release-devDependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/no-restricted-pre-release-devDependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/no-tilde-version-dependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/no-tilde-version-dependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/no-tilde-version-devDependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/no-tilde-version-devDependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/optionalDependencies-type.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/optionalDependencies-type'>;
}
declare module 'npm-package-json-lint/dist/rules/os-type.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/os-type'>;
}
declare module 'npm-package-json-lint/dist/rules/peerDependencies-type.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/peerDependencies-type'>;
}
declare module 'npm-package-json-lint/dist/rules/prefer-absolute-version-dependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/prefer-absolute-version-dependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/prefer-absolute-version-devDependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/prefer-absolute-version-devDependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/prefer-alphabetical-bundledDependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/prefer-alphabetical-bundledDependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/prefer-alphabetical-dependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/prefer-alphabetical-dependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/prefer-alphabetical-devDependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/prefer-alphabetical-devDependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/prefer-alphabetical-optionalDependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/prefer-alphabetical-optionalDependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/prefer-alphabetical-peerDependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/prefer-alphabetical-peerDependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/prefer-alphabetical-scripts.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/prefer-alphabetical-scripts'>;
}
declare module 'npm-package-json-lint/dist/rules/prefer-caret-version-dependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/prefer-caret-version-dependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/prefer-caret-version-devDependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/prefer-caret-version-devDependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/prefer-no-contributors.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/prefer-no-contributors'>;
}
declare module 'npm-package-json-lint/dist/rules/prefer-no-dependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/prefer-no-dependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/prefer-no-devDependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/prefer-no-devDependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/prefer-no-engineStrict.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/prefer-no-engineStrict'>;
}
declare module 'npm-package-json-lint/dist/rules/prefer-no-optionalDependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/prefer-no-optionalDependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/prefer-no-peerDependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/prefer-no-peerDependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/prefer-no-version-zero-dependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/prefer-no-version-zero-dependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/prefer-no-version-zero-devDependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/prefer-no-version-zero-devDependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/prefer-property-order.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/prefer-property-order'>;
}
declare module 'npm-package-json-lint/dist/rules/prefer-scripts.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/prefer-scripts'>;
}
declare module 'npm-package-json-lint/dist/rules/prefer-tilde-version-dependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/prefer-tilde-version-dependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/prefer-tilde-version-devDependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/prefer-tilde-version-devDependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/preferGlobal-type.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/preferGlobal-type'>;
}
declare module 'npm-package-json-lint/dist/rules/private-type.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/private-type'>;
}
declare module 'npm-package-json-lint/dist/rules/repository-type.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/repository-type'>;
}
declare module 'npm-package-json-lint/dist/rules/require-author.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/require-author'>;
}
declare module 'npm-package-json-lint/dist/rules/require-bin.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/require-bin'>;
}
declare module 'npm-package-json-lint/dist/rules/require-bugs.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/require-bugs'>;
}
declare module 'npm-package-json-lint/dist/rules/require-bundledDependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/require-bundledDependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/require-config.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/require-config'>;
}
declare module 'npm-package-json-lint/dist/rules/require-contributors.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/require-contributors'>;
}
declare module 'npm-package-json-lint/dist/rules/require-cpu.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/require-cpu'>;
}
declare module 'npm-package-json-lint/dist/rules/require-dependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/require-dependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/require-description.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/require-description'>;
}
declare module 'npm-package-json-lint/dist/rules/require-devDependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/require-devDependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/require-directories.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/require-directories'>;
}
declare module 'npm-package-json-lint/dist/rules/require-engines.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/require-engines'>;
}
declare module 'npm-package-json-lint/dist/rules/require-files.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/require-files'>;
}
declare module 'npm-package-json-lint/dist/rules/require-funding.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/require-funding'>;
}
declare module 'npm-package-json-lint/dist/rules/require-homepage.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/require-homepage'>;
}
declare module 'npm-package-json-lint/dist/rules/require-keywords.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/require-keywords'>;
}
declare module 'npm-package-json-lint/dist/rules/require-license.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/require-license'>;
}
declare module 'npm-package-json-lint/dist/rules/require-main.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/require-main'>;
}
declare module 'npm-package-json-lint/dist/rules/require-man.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/require-man'>;
}
declare module 'npm-package-json-lint/dist/rules/require-module.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/require-module'>;
}
declare module 'npm-package-json-lint/dist/rules/require-name.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/require-name'>;
}
declare module 'npm-package-json-lint/dist/rules/require-optionalDependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/require-optionalDependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/require-os.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/require-os'>;
}
declare module 'npm-package-json-lint/dist/rules/require-peerDependencies.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/require-peerDependencies'>;
}
declare module 'npm-package-json-lint/dist/rules/require-preferGlobal.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/require-preferGlobal'>;
}
declare module 'npm-package-json-lint/dist/rules/require-private.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/require-private'>;
}
declare module 'npm-package-json-lint/dist/rules/require-publishConfig.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/require-publishConfig'>;
}
declare module 'npm-package-json-lint/dist/rules/require-repository-directory.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/require-repository-directory'>;
}
declare module 'npm-package-json-lint/dist/rules/require-repository.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/require-repository'>;
}
declare module 'npm-package-json-lint/dist/rules/require-scripts.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/require-scripts'>;
}
declare module 'npm-package-json-lint/dist/rules/require-types.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/require-types'>;
}
declare module 'npm-package-json-lint/dist/rules/require-typings.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/require-typings'>;
}
declare module 'npm-package-json-lint/dist/rules/require-version.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/require-version'>;
}
declare module 'npm-package-json-lint/dist/rules/scripts-type.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/scripts-type'>;
}
declare module 'npm-package-json-lint/dist/rules/valid-values-author.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/valid-values-author'>;
}
declare module 'npm-package-json-lint/dist/rules/valid-values-engines.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/valid-values-engines'>;
}
declare module 'npm-package-json-lint/dist/rules/valid-values-license.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/valid-values-license'>;
}
declare module 'npm-package-json-lint/dist/rules/valid-values-name-scope.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/valid-values-name-scope'>;
}
declare module 'npm-package-json-lint/dist/rules/valid-values-private.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/valid-values-private'>;
}
declare module 'npm-package-json-lint/dist/rules/valid-values-publishConfig.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/valid-values-publishConfig'>;
}
declare module 'npm-package-json-lint/dist/rules/version-format.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/version-format'>;
}
declare module 'npm-package-json-lint/dist/rules/version-type.js' {
  declare module.exports: $Exports<'npm-package-json-lint/dist/rules/version-type'>;
}
