// flow-typed signature: de94c4bc3a1405553a2e50a4a7d30473
// flow-typed version: <<STUB>>/npm-package-json-lint-config-default_v^5.0.0/flow_v0.181.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'npm-package-json-lint-config-default'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'npm-package-json-lint-config-default' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'npm-package-json-lint-config-default/index' {
  declare module.exports: $Exports<'npm-package-json-lint-config-default'>;
}
declare module 'npm-package-json-lint-config-default/index.js' {
  declare module.exports: $Exports<'npm-package-json-lint-config-default'>;
}
