// flow-typed signature: 81b58c3b12f1c87dec5640155d978b2e
// flow-typed version: <<STUB>>/pkg-ok_v^2.3.1/flow_v0.164.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pkg-ok'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pkg-ok' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pkg-ok/bin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pkg-ok/bin.js' {
  declare module.exports: $Exports<'pkg-ok/bin'>;
}
declare module 'pkg-ok/index' {
  declare module.exports: $Exports<'pkg-ok'>;
}
declare module 'pkg-ok/index.js' {
  declare module.exports: $Exports<'pkg-ok'>;
}
