// flow-typed signature: b3af4fe16f8953f06f8537443225f305
// flow-typed version: <<STUB>>/pkg-ok_v^3.0.0/flow_v0.199.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pkg-ok'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pkg-ok' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pkg-ok/dist/bin' {
  declare module.exports: any;
}

declare module 'pkg-ok/dist/errors' {
  declare module.exports: any;
}

declare module 'pkg-ok/dist/fields' {
  declare module.exports: any;
}

declare module 'pkg-ok/dist' {
  declare module.exports: any;
}

declare module 'pkg-ok/dist/pkg' {
  declare module.exports: any;
}

declare module 'pkg-ok/dist/scripts' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pkg-ok/dist/bin.js' {
  declare module.exports: $Exports<'pkg-ok/dist/bin'>;
}
declare module 'pkg-ok/dist/errors.js' {
  declare module.exports: $Exports<'pkg-ok/dist/errors'>;
}
declare module 'pkg-ok/dist/fields.js' {
  declare module.exports: $Exports<'pkg-ok/dist/fields'>;
}
declare module 'pkg-ok/dist/index' {
  declare module.exports: $Exports<'pkg-ok/dist'>;
}
declare module 'pkg-ok/dist/index.js' {
  declare module.exports: $Exports<'pkg-ok/dist'>;
}
declare module 'pkg-ok/dist/pkg.js' {
  declare module.exports: $Exports<'pkg-ok/dist/pkg'>;
}
declare module 'pkg-ok/dist/scripts.js' {
  declare module.exports: $Exports<'pkg-ok/dist/scripts'>;
}
