// flow-typed signature: ea1fe79993e9184268eaf46abcc4cef8
// flow-typed version: <<STUB>>/react-cookie_v^4.1.1/flow_v0.164.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-cookie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-cookie' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-cookie/cjs/Cookies' {
  declare module.exports: any;
}

declare module 'react-cookie/cjs/CookiesContext' {
  declare module.exports: any;
}

declare module 'react-cookie/cjs/CookiesProvider' {
  declare module.exports: any;
}

declare module 'react-cookie/cjs' {
  declare module.exports: any;
}

declare module 'react-cookie/cjs/types' {
  declare module.exports: any;
}

declare module 'react-cookie/cjs/useCookies' {
  declare module.exports: any;
}

declare module 'react-cookie/cjs/utils' {
  declare module.exports: any;
}

declare module 'react-cookie/cjs/withCookies' {
  declare module.exports: any;
}

declare module 'react-cookie/es6/Cookies' {
  declare module.exports: any;
}

declare module 'react-cookie/es6/CookiesContext' {
  declare module.exports: any;
}

declare module 'react-cookie/es6/CookiesProvider' {
  declare module.exports: any;
}

declare module 'react-cookie/es6' {
  declare module.exports: any;
}

declare module 'react-cookie/es6/types' {
  declare module.exports: any;
}

declare module 'react-cookie/es6/useCookies' {
  declare module.exports: any;
}

declare module 'react-cookie/es6/utils' {
  declare module.exports: any;
}

declare module 'react-cookie/es6/withCookies' {
  declare module.exports: any;
}

declare module 'react-cookie/lib/Cookies' {
  declare module.exports: any;
}

declare module 'react-cookie/lib/CookiesContext' {
  declare module.exports: any;
}

declare module 'react-cookie/lib/CookiesProvider' {
  declare module.exports: any;
}

declare module 'react-cookie/lib' {
  declare module.exports: any;
}

declare module 'react-cookie/lib/types' {
  declare module.exports: any;
}

declare module 'react-cookie/lib/useCookies' {
  declare module.exports: any;
}

declare module 'react-cookie/lib/utils' {
  declare module.exports: any;
}

declare module 'react-cookie/lib/withCookies' {
  declare module.exports: any;
}

declare module 'react-cookie/umd/reactCookie' {
  declare module.exports: any;
}

declare module 'react-cookie/umd/reactCookie.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-cookie/cjs/Cookies.js' {
  declare module.exports: $Exports<'react-cookie/cjs/Cookies'>;
}
declare module 'react-cookie/cjs/CookiesContext.js' {
  declare module.exports: $Exports<'react-cookie/cjs/CookiesContext'>;
}
declare module 'react-cookie/cjs/CookiesProvider.js' {
  declare module.exports: $Exports<'react-cookie/cjs/CookiesProvider'>;
}
declare module 'react-cookie/cjs/index' {
  declare module.exports: $Exports<'react-cookie/cjs'>;
}
declare module 'react-cookie/cjs/index.js' {
  declare module.exports: $Exports<'react-cookie/cjs'>;
}
declare module 'react-cookie/cjs/types.js' {
  declare module.exports: $Exports<'react-cookie/cjs/types'>;
}
declare module 'react-cookie/cjs/useCookies.js' {
  declare module.exports: $Exports<'react-cookie/cjs/useCookies'>;
}
declare module 'react-cookie/cjs/utils.js' {
  declare module.exports: $Exports<'react-cookie/cjs/utils'>;
}
declare module 'react-cookie/cjs/withCookies.js' {
  declare module.exports: $Exports<'react-cookie/cjs/withCookies'>;
}
declare module 'react-cookie/es6/Cookies.js' {
  declare module.exports: $Exports<'react-cookie/es6/Cookies'>;
}
declare module 'react-cookie/es6/CookiesContext.js' {
  declare module.exports: $Exports<'react-cookie/es6/CookiesContext'>;
}
declare module 'react-cookie/es6/CookiesProvider.js' {
  declare module.exports: $Exports<'react-cookie/es6/CookiesProvider'>;
}
declare module 'react-cookie/es6/index' {
  declare module.exports: $Exports<'react-cookie/es6'>;
}
declare module 'react-cookie/es6/index.js' {
  declare module.exports: $Exports<'react-cookie/es6'>;
}
declare module 'react-cookie/es6/types.js' {
  declare module.exports: $Exports<'react-cookie/es6/types'>;
}
declare module 'react-cookie/es6/useCookies.js' {
  declare module.exports: $Exports<'react-cookie/es6/useCookies'>;
}
declare module 'react-cookie/es6/utils.js' {
  declare module.exports: $Exports<'react-cookie/es6/utils'>;
}
declare module 'react-cookie/es6/withCookies.js' {
  declare module.exports: $Exports<'react-cookie/es6/withCookies'>;
}
declare module 'react-cookie/lib/Cookies.js' {
  declare module.exports: $Exports<'react-cookie/lib/Cookies'>;
}
declare module 'react-cookie/lib/CookiesContext.js' {
  declare module.exports: $Exports<'react-cookie/lib/CookiesContext'>;
}
declare module 'react-cookie/lib/CookiesProvider.js' {
  declare module.exports: $Exports<'react-cookie/lib/CookiesProvider'>;
}
declare module 'react-cookie/lib/index' {
  declare module.exports: $Exports<'react-cookie/lib'>;
}
declare module 'react-cookie/lib/index.js' {
  declare module.exports: $Exports<'react-cookie/lib'>;
}
declare module 'react-cookie/lib/types.js' {
  declare module.exports: $Exports<'react-cookie/lib/types'>;
}
declare module 'react-cookie/lib/useCookies.js' {
  declare module.exports: $Exports<'react-cookie/lib/useCookies'>;
}
declare module 'react-cookie/lib/utils.js' {
  declare module.exports: $Exports<'react-cookie/lib/utils'>;
}
declare module 'react-cookie/lib/withCookies.js' {
  declare module.exports: $Exports<'react-cookie/lib/withCookies'>;
}
declare module 'react-cookie/umd/reactCookie.js' {
  declare module.exports: $Exports<'react-cookie/umd/reactCookie'>;
}
declare module 'react-cookie/umd/reactCookie.min.js' {
  declare module.exports: $Exports<'react-cookie/umd/reactCookie.min'>;
}
