// flow-typed signature: 14ecf05a116e56e85fb933439d415472
// flow-typed version: <<STUB>>/react-joyride_v^2.5.5/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-joyride'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-joyride' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-joyride/es' {
  declare module.exports: any;
}

declare module 'react-joyride/lib' {
  declare module.exports: any;
}

declare module 'react-joyride/src/components/Beacon' {
  declare module.exports: any;
}

declare module 'react-joyride/src/components' {
  declare module.exports: any;
}

declare module 'react-joyride/src/components/Overlay' {
  declare module.exports: any;
}

declare module 'react-joyride/src/components/Portal' {
  declare module.exports: any;
}

declare module 'react-joyride/src/components/Spotlight' {
  declare module.exports: any;
}

declare module 'react-joyride/src/components/Step' {
  declare module.exports: any;
}

declare module 'react-joyride/src/components/Tooltip/CloseBtn' {
  declare module.exports: any;
}

declare module 'react-joyride/src/components/Tooltip/Container' {
  declare module.exports: any;
}

declare module 'react-joyride/src/components/Tooltip' {
  declare module.exports: any;
}

declare module 'react-joyride/src/config/defaults' {
  declare module.exports: any;
}

declare module 'react-joyride/src/constants/actions' {
  declare module.exports: any;
}

declare module 'react-joyride/src/constants/events' {
  declare module.exports: any;
}

declare module 'react-joyride/src/constants' {
  declare module.exports: any;
}

declare module 'react-joyride/src/constants/lifecycle' {
  declare module.exports: any;
}

declare module 'react-joyride/src/constants/status' {
  declare module.exports: any;
}

declare module 'react-joyride/src' {
  declare module.exports: any;
}

declare module 'react-joyride/src/modules/dom' {
  declare module.exports: any;
}

declare module 'react-joyride/src/modules/helpers' {
  declare module.exports: any;
}

declare module 'react-joyride/src/modules/propTypes' {
  declare module.exports: any;
}

declare module 'react-joyride/src/modules/scope' {
  declare module.exports: any;
}

declare module 'react-joyride/src/modules/step' {
  declare module.exports: any;
}

declare module 'react-joyride/src/modules/store' {
  declare module.exports: any;
}

declare module 'react-joyride/src/styles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-joyride/es/index' {
  declare module.exports: $Exports<'react-joyride/es'>;
}
declare module 'react-joyride/es/index.js' {
  declare module.exports: $Exports<'react-joyride/es'>;
}
declare module 'react-joyride/lib/index' {
  declare module.exports: $Exports<'react-joyride/lib'>;
}
declare module 'react-joyride/lib/index.js' {
  declare module.exports: $Exports<'react-joyride/lib'>;
}
declare module 'react-joyride/src/components/Beacon.js' {
  declare module.exports: $Exports<'react-joyride/src/components/Beacon'>;
}
declare module 'react-joyride/src/components/index' {
  declare module.exports: $Exports<'react-joyride/src/components'>;
}
declare module 'react-joyride/src/components/index.js' {
  declare module.exports: $Exports<'react-joyride/src/components'>;
}
declare module 'react-joyride/src/components/Overlay.js' {
  declare module.exports: $Exports<'react-joyride/src/components/Overlay'>;
}
declare module 'react-joyride/src/components/Portal.js' {
  declare module.exports: $Exports<'react-joyride/src/components/Portal'>;
}
declare module 'react-joyride/src/components/Spotlight.js' {
  declare module.exports: $Exports<'react-joyride/src/components/Spotlight'>;
}
declare module 'react-joyride/src/components/Step.js' {
  declare module.exports: $Exports<'react-joyride/src/components/Step'>;
}
declare module 'react-joyride/src/components/Tooltip/CloseBtn.js' {
  declare module.exports: $Exports<'react-joyride/src/components/Tooltip/CloseBtn'>;
}
declare module 'react-joyride/src/components/Tooltip/Container.js' {
  declare module.exports: $Exports<'react-joyride/src/components/Tooltip/Container'>;
}
declare module 'react-joyride/src/components/Tooltip/index' {
  declare module.exports: $Exports<'react-joyride/src/components/Tooltip'>;
}
declare module 'react-joyride/src/components/Tooltip/index.js' {
  declare module.exports: $Exports<'react-joyride/src/components/Tooltip'>;
}
declare module 'react-joyride/src/config/defaults.js' {
  declare module.exports: $Exports<'react-joyride/src/config/defaults'>;
}
declare module 'react-joyride/src/constants/actions.js' {
  declare module.exports: $Exports<'react-joyride/src/constants/actions'>;
}
declare module 'react-joyride/src/constants/events.js' {
  declare module.exports: $Exports<'react-joyride/src/constants/events'>;
}
declare module 'react-joyride/src/constants/index' {
  declare module.exports: $Exports<'react-joyride/src/constants'>;
}
declare module 'react-joyride/src/constants/index.js' {
  declare module.exports: $Exports<'react-joyride/src/constants'>;
}
declare module 'react-joyride/src/constants/lifecycle.js' {
  declare module.exports: $Exports<'react-joyride/src/constants/lifecycle'>;
}
declare module 'react-joyride/src/constants/status.js' {
  declare module.exports: $Exports<'react-joyride/src/constants/status'>;
}
declare module 'react-joyride/src/index' {
  declare module.exports: $Exports<'react-joyride/src'>;
}
declare module 'react-joyride/src/index.js' {
  declare module.exports: $Exports<'react-joyride/src'>;
}
declare module 'react-joyride/src/modules/dom.js' {
  declare module.exports: $Exports<'react-joyride/src/modules/dom'>;
}
declare module 'react-joyride/src/modules/helpers.js' {
  declare module.exports: $Exports<'react-joyride/src/modules/helpers'>;
}
declare module 'react-joyride/src/modules/propTypes.js' {
  declare module.exports: $Exports<'react-joyride/src/modules/propTypes'>;
}
declare module 'react-joyride/src/modules/scope.js' {
  declare module.exports: $Exports<'react-joyride/src/modules/scope'>;
}
declare module 'react-joyride/src/modules/step.js' {
  declare module.exports: $Exports<'react-joyride/src/modules/step'>;
}
declare module 'react-joyride/src/modules/store.js' {
  declare module.exports: $Exports<'react-joyride/src/modules/store'>;
}
declare module 'react-joyride/src/styles.js' {
  declare module.exports: $Exports<'react-joyride/src/styles'>;
}
