// flow-typed signature: c0d3b1f0278b8838ceba9946464a6c1f
// flow-typed version: <<STUB>>/react-split-pane_v^0.1.92/flow_v0.163.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-split-pane'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-split-pane' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-split-pane/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'react-split-pane/dist/index.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-split-pane/dist/index.cjs.js' {
  declare module.exports: $Exports<'react-split-pane/dist/index.cjs'>;
}
declare module 'react-split-pane/dist/index.esm.js' {
  declare module.exports: $Exports<'react-split-pane/dist/index.esm'>;
}
