// flow-typed signature: 43038e7d6fd0abf4a8f922987cd7f082
// flow-typed version: <<STUB>>/react-test-renderer_v^17.0.2/flow_v0.196.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-test-renderer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-test-renderer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-test-renderer/cjs/react-test-renderer.development' {
  declare module.exports: any;
}

declare module 'react-test-renderer/cjs/react-test-renderer.production.min' {
  declare module.exports: any;
}

declare module 'react-test-renderer/shallow' {
  declare module.exports: any;
}

declare module 'react-test-renderer/umd/react-test-renderer.development' {
  declare module.exports: any;
}

declare module 'react-test-renderer/umd/react-test-renderer.production.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-test-renderer/cjs/react-test-renderer.development.js' {
  declare module.exports: $Exports<'react-test-renderer/cjs/react-test-renderer.development'>;
}
declare module 'react-test-renderer/cjs/react-test-renderer.production.min.js' {
  declare module.exports: $Exports<'react-test-renderer/cjs/react-test-renderer.production.min'>;
}
declare module 'react-test-renderer/index' {
  declare module.exports: $Exports<'react-test-renderer'>;
}
declare module 'react-test-renderer/index.js' {
  declare module.exports: $Exports<'react-test-renderer'>;
}
declare module 'react-test-renderer/shallow.js' {
  declare module.exports: $Exports<'react-test-renderer/shallow'>;
}
declare module 'react-test-renderer/umd/react-test-renderer.development.js' {
  declare module.exports: $Exports<'react-test-renderer/umd/react-test-renderer.development'>;
}
declare module 'react-test-renderer/umd/react-test-renderer.production.min.js' {
  declare module.exports: $Exports<'react-test-renderer/umd/react-test-renderer.production.min'>;
}
