// flow-typed signature: 07e805ddf8f8a9d2594de41529c96c63
// flow-typed version: <<STUB>>/react-device-detect_v^1.17.0/flow_v0.159.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-device-detect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-device-detect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-device-detect/main' {
  declare module.exports: any;
}

declare module 'react-device-detect/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-device-detect/main.js' {
  declare module.exports: $Exports<'react-device-detect/main'>;
}
declare module 'react-device-detect/rollup.config.js' {
  declare module.exports: $Exports<'react-device-detect/rollup.config'>;
}
