// flow-typed signature: b517e8ed6cd8af121488d6854b14b904
// flow-typed version: <<STUB>>/react-router_v^7.14.1/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router/dist/development/chunk-3F6IB66O' {
  declare module.exports: any;
}

declare module 'react-router/dist/development/chunk-7VLQJKNG' {
  declare module.exports: any;
}

declare module 'react-router/dist/development/chunk-YMKMFAYZ' {
  declare module.exports: any;
}

declare module 'react-router/dist/development/dom-export' {
  declare module.exports: any;
}

declare module 'react-router/dist/development/index-react-server-client' {
  declare module.exports: any;
}

declare module 'react-router/dist/development/index-react-server' {
  declare module.exports: any;
}

declare module 'react-router/dist/development' {
  declare module.exports: any;
}

declare module 'react-router/dist/development/lib/types/internal' {
  declare module.exports: any;
}

declare module 'react-router/dist/production/chunk-3SUPTI2U' {
  declare module.exports: any;
}

declare module 'react-router/dist/production/chunk-LIOP3ILM' {
  declare module.exports: any;
}

declare module 'react-router/dist/production/chunk-UVEQGZIH' {
  declare module.exports: any;
}

declare module 'react-router/dist/production/dom-export' {
  declare module.exports: any;
}

declare module 'react-router/dist/production/index-react-server-client' {
  declare module.exports: any;
}

declare module 'react-router/dist/production/index-react-server' {
  declare module.exports: any;
}

declare module 'react-router/dist/production' {
  declare module.exports: any;
}

declare module 'react-router/dist/production/lib/types/internal' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router/dist/development/chunk-3F6IB66O.js' {
  declare module.exports: $Exports<'react-router/dist/development/chunk-3F6IB66O'>;
}
declare module 'react-router/dist/development/chunk-7VLQJKNG.js' {
  declare module.exports: $Exports<'react-router/dist/development/chunk-7VLQJKNG'>;
}
declare module 'react-router/dist/development/chunk-YMKMFAYZ.js' {
  declare module.exports: $Exports<'react-router/dist/development/chunk-YMKMFAYZ'>;
}
declare module 'react-router/dist/development/dom-export.js' {
  declare module.exports: $Exports<'react-router/dist/development/dom-export'>;
}
declare module 'react-router/dist/development/index-react-server-client.js' {
  declare module.exports: $Exports<'react-router/dist/development/index-react-server-client'>;
}
declare module 'react-router/dist/development/index-react-server.js' {
  declare module.exports: $Exports<'react-router/dist/development/index-react-server'>;
}
declare module 'react-router/dist/development/index' {
  declare module.exports: $Exports<'react-router/dist/development'>;
}
declare module 'react-router/dist/development/index.js' {
  declare module.exports: $Exports<'react-router/dist/development'>;
}
declare module 'react-router/dist/development/lib/types/internal.js' {
  declare module.exports: $Exports<'react-router/dist/development/lib/types/internal'>;
}
declare module 'react-router/dist/production/chunk-3SUPTI2U.js' {
  declare module.exports: $Exports<'react-router/dist/production/chunk-3SUPTI2U'>;
}
declare module 'react-router/dist/production/chunk-LIOP3ILM.js' {
  declare module.exports: $Exports<'react-router/dist/production/chunk-LIOP3ILM'>;
}
declare module 'react-router/dist/production/chunk-UVEQGZIH.js' {
  declare module.exports: $Exports<'react-router/dist/production/chunk-UVEQGZIH'>;
}
declare module 'react-router/dist/production/dom-export.js' {
  declare module.exports: $Exports<'react-router/dist/production/dom-export'>;
}
declare module 'react-router/dist/production/index-react-server-client.js' {
  declare module.exports: $Exports<'react-router/dist/production/index-react-server-client'>;
}
declare module 'react-router/dist/production/index-react-server.js' {
  declare module.exports: $Exports<'react-router/dist/production/index-react-server'>;
}
declare module 'react-router/dist/production/index' {
  declare module.exports: $Exports<'react-router/dist/production'>;
}
declare module 'react-router/dist/production/index.js' {
  declare module.exports: $Exports<'react-router/dist/production'>;
}
declare module 'react-router/dist/production/lib/types/internal.js' {
  declare module.exports: $Exports<'react-router/dist/production/lib/types/internal'>;
}
