// flow-typed signature: 16d3d0fe28a98191cb88119e3b2a3bf9
// flow-typed version: <<STUB>>/react-simple-code-editor_v^0.11.2/flow_v0.183.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-simple-code-editor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-simple-code-editor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-simple-code-editor/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-simple-code-editor/lib/index' {
  declare module.exports: $Exports<'react-simple-code-editor/lib'>;
}
declare module 'react-simple-code-editor/lib/index.js' {
  declare module.exports: $Exports<'react-simple-code-editor/lib'>;
}
