// flow-typed signature: 0876fdf09cf2547ebde9c3541929fd0f
// flow-typed version: <<STUB>>/react-router_v^7.12.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router/dist/development/chunk-2BEI23B2' {
  declare module.exports: any;
}

declare module 'react-router/dist/development/chunk-7ZCBDOCZ' {
  declare module.exports: any;
}

declare module 'react-router/dist/development/chunk-G2I2SRFA' {
  declare module.exports: any;
}

declare module 'react-router/dist/development/dom-export' {
  declare module.exports: any;
}

declare module 'react-router/dist/development/index-react-server-client' {
  declare module.exports: any;
}

declare module 'react-router/dist/development/index-react-server' {
  declare module.exports: any;
}

declare module 'react-router/dist/development' {
  declare module.exports: any;
}

declare module 'react-router/dist/development/lib/types/internal' {
  declare module.exports: any;
}

declare module 'react-router/dist/production/chunk-337Z4Y65' {
  declare module.exports: any;
}

declare module 'react-router/dist/production/chunk-Y62AB6TB' {
  declare module.exports: any;
}

declare module 'react-router/dist/production/chunk-Z47B263N' {
  declare module.exports: any;
}

declare module 'react-router/dist/production/dom-export' {
  declare module.exports: any;
}

declare module 'react-router/dist/production/index-react-server-client' {
  declare module.exports: any;
}

declare module 'react-router/dist/production/index-react-server' {
  declare module.exports: any;
}

declare module 'react-router/dist/production' {
  declare module.exports: any;
}

declare module 'react-router/dist/production/lib/types/internal' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router/dist/development/chunk-2BEI23B2.js' {
  declare module.exports: $Exports<'react-router/dist/development/chunk-2BEI23B2'>;
}
declare module 'react-router/dist/development/chunk-7ZCBDOCZ.js' {
  declare module.exports: $Exports<'react-router/dist/development/chunk-7ZCBDOCZ'>;
}
declare module 'react-router/dist/development/chunk-G2I2SRFA.js' {
  declare module.exports: $Exports<'react-router/dist/development/chunk-G2I2SRFA'>;
}
declare module 'react-router/dist/development/dom-export.js' {
  declare module.exports: $Exports<'react-router/dist/development/dom-export'>;
}
declare module 'react-router/dist/development/index-react-server-client.js' {
  declare module.exports: $Exports<'react-router/dist/development/index-react-server-client'>;
}
declare module 'react-router/dist/development/index-react-server.js' {
  declare module.exports: $Exports<'react-router/dist/development/index-react-server'>;
}
declare module 'react-router/dist/development/index' {
  declare module.exports: $Exports<'react-router/dist/development'>;
}
declare module 'react-router/dist/development/index.js' {
  declare module.exports: $Exports<'react-router/dist/development'>;
}
declare module 'react-router/dist/development/lib/types/internal.js' {
  declare module.exports: $Exports<'react-router/dist/development/lib/types/internal'>;
}
declare module 'react-router/dist/production/chunk-337Z4Y65.js' {
  declare module.exports: $Exports<'react-router/dist/production/chunk-337Z4Y65'>;
}
declare module 'react-router/dist/production/chunk-Y62AB6TB.js' {
  declare module.exports: $Exports<'react-router/dist/production/chunk-Y62AB6TB'>;
}
declare module 'react-router/dist/production/chunk-Z47B263N.js' {
  declare module.exports: $Exports<'react-router/dist/production/chunk-Z47B263N'>;
}
declare module 'react-router/dist/production/dom-export.js' {
  declare module.exports: $Exports<'react-router/dist/production/dom-export'>;
}
declare module 'react-router/dist/production/index-react-server-client.js' {
  declare module.exports: $Exports<'react-router/dist/production/index-react-server-client'>;
}
declare module 'react-router/dist/production/index-react-server.js' {
  declare module.exports: $Exports<'react-router/dist/production/index-react-server'>;
}
declare module 'react-router/dist/production/index' {
  declare module.exports: $Exports<'react-router/dist/production'>;
}
declare module 'react-router/dist/production/index.js' {
  declare module.exports: $Exports<'react-router/dist/production'>;
}
declare module 'react-router/dist/production/lib/types/internal.js' {
  declare module.exports: $Exports<'react-router/dist/production/lib/types/internal'>;
}
