// flow-typed signature: e23301d20242986002a3345bd9788747
// flow-typed version: <<STUB>>/react-router_v^7.14.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router/dist/development/chunk-IK6APEEG' {
  declare module.exports: any;
}

declare module 'react-router/dist/development/chunk-NXTEWSJO' {
  declare module.exports: any;
}

declare module 'react-router/dist/development/chunk-WAVMRYR2' {
  declare module.exports: any;
}

declare module 'react-router/dist/development/dom-export' {
  declare module.exports: any;
}

declare module 'react-router/dist/development/index-react-server-client' {
  declare module.exports: any;
}

declare module 'react-router/dist/development/index-react-server' {
  declare module.exports: any;
}

declare module 'react-router/dist/development' {
  declare module.exports: any;
}

declare module 'react-router/dist/development/lib/types/internal' {
  declare module.exports: any;
}

declare module 'react-router/dist/production/chunk-355DUZMC' {
  declare module.exports: any;
}

declare module 'react-router/dist/production/chunk-4TJ7T2OQ' {
  declare module.exports: any;
}

declare module 'react-router/dist/production/chunk-FPT5DLVJ' {
  declare module.exports: any;
}

declare module 'react-router/dist/production/dom-export' {
  declare module.exports: any;
}

declare module 'react-router/dist/production/index-react-server-client' {
  declare module.exports: any;
}

declare module 'react-router/dist/production/index-react-server' {
  declare module.exports: any;
}

declare module 'react-router/dist/production' {
  declare module.exports: any;
}

declare module 'react-router/dist/production/lib/types/internal' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router/dist/development/chunk-IK6APEEG.js' {
  declare module.exports: $Exports<'react-router/dist/development/chunk-IK6APEEG'>;
}
declare module 'react-router/dist/development/chunk-NXTEWSJO.js' {
  declare module.exports: $Exports<'react-router/dist/development/chunk-NXTEWSJO'>;
}
declare module 'react-router/dist/development/chunk-WAVMRYR2.js' {
  declare module.exports: $Exports<'react-router/dist/development/chunk-WAVMRYR2'>;
}
declare module 'react-router/dist/development/dom-export.js' {
  declare module.exports: $Exports<'react-router/dist/development/dom-export'>;
}
declare module 'react-router/dist/development/index-react-server-client.js' {
  declare module.exports: $Exports<'react-router/dist/development/index-react-server-client'>;
}
declare module 'react-router/dist/development/index-react-server.js' {
  declare module.exports: $Exports<'react-router/dist/development/index-react-server'>;
}
declare module 'react-router/dist/development/index' {
  declare module.exports: $Exports<'react-router/dist/development'>;
}
declare module 'react-router/dist/development/index.js' {
  declare module.exports: $Exports<'react-router/dist/development'>;
}
declare module 'react-router/dist/development/lib/types/internal.js' {
  declare module.exports: $Exports<'react-router/dist/development/lib/types/internal'>;
}
declare module 'react-router/dist/production/chunk-355DUZMC.js' {
  declare module.exports: $Exports<'react-router/dist/production/chunk-355DUZMC'>;
}
declare module 'react-router/dist/production/chunk-4TJ7T2OQ.js' {
  declare module.exports: $Exports<'react-router/dist/production/chunk-4TJ7T2OQ'>;
}
declare module 'react-router/dist/production/chunk-FPT5DLVJ.js' {
  declare module.exports: $Exports<'react-router/dist/production/chunk-FPT5DLVJ'>;
}
declare module 'react-router/dist/production/dom-export.js' {
  declare module.exports: $Exports<'react-router/dist/production/dom-export'>;
}
declare module 'react-router/dist/production/index-react-server-client.js' {
  declare module.exports: $Exports<'react-router/dist/production/index-react-server-client'>;
}
declare module 'react-router/dist/production/index-react-server.js' {
  declare module.exports: $Exports<'react-router/dist/production/index-react-server'>;
}
declare module 'react-router/dist/production/index' {
  declare module.exports: $Exports<'react-router/dist/production'>;
}
declare module 'react-router/dist/production/index.js' {
  declare module.exports: $Exports<'react-router/dist/production'>;
}
declare module 'react-router/dist/production/lib/types/internal.js' {
  declare module.exports: $Exports<'react-router/dist/production/lib/types/internal'>;
}
