// flow-typed signature: ac709ea5e688b356aeb441cf206a4b46
// flow-typed version: <<STUB>>/react-simple-tree-menu_v^1.1.18/flow_v0.196.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-simple-tree-menu'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-simple-tree-menu' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-simple-tree-menu/dist/main.cjs' {
  declare module.exports: any;
}

declare module 'react-simple-tree-menu/dist/main.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-simple-tree-menu/dist/main.cjs.js' {
  declare module.exports: $Exports<'react-simple-tree-menu/dist/main.cjs'>;
}
declare module 'react-simple-tree-menu/dist/main.esm.js' {
  declare module.exports: $Exports<'react-simple-tree-menu/dist/main.esm'>;
}
