// flow-typed signature: e20210d8c01d88cf90819749bde7629c
// flow-typed version: <<STUB>>/react-cookie_v^7.2.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-cookie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-cookie' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-cookie/cjs' {
  declare module.exports: any;
}

declare module 'react-cookie/umd/reactCookie' {
  declare module.exports: any;
}

declare module 'react-cookie/umd/reactCookie.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-cookie/cjs/index' {
  declare module.exports: $Exports<'react-cookie/cjs'>;
}
declare module 'react-cookie/cjs/index.js' {
  declare module.exports: $Exports<'react-cookie/cjs'>;
}
declare module 'react-cookie/umd/reactCookie.js' {
  declare module.exports: $Exports<'react-cookie/umd/reactCookie'>;
}
declare module 'react-cookie/umd/reactCookie.min.js' {
  declare module.exports: $Exports<'react-cookie/umd/reactCookie.min'>;
}
