// flow-typed signature: c88b22c0c63127f0e270ed01b5e69ad6
// flow-typed version: <<STUB>>/react-joyride_v^2.3.0/flow_v0.151.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-joyride'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-joyride' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-joyride/es' {
  declare module.exports: any;
}

declare module 'react-joyride/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-joyride/es/index' {
  declare module.exports: $Exports<'react-joyride/es'>;
}
declare module 'react-joyride/es/index.js' {
  declare module.exports: $Exports<'react-joyride/es'>;
}
declare module 'react-joyride/lib/index' {
  declare module.exports: $Exports<'react-joyride/lib'>;
}
declare module 'react-joyride/lib/index.js' {
  declare module.exports: $Exports<'react-joyride/lib'>;
}
