// flow-typed signature: 78607d3c6a7afe7aa9c2b0848ee58ee2
// flow-typed version: <<STUB>>/react-redux_v^9.0.4/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-redux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-redux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-redux/dist/cjs' {
  declare module.exports: any;
}

declare module 'react-redux/dist/react-redux.legacy-esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-redux/dist/cjs/index' {
  declare module.exports: $Exports<'react-redux/dist/cjs'>;
}
declare module 'react-redux/dist/cjs/index.js' {
  declare module.exports: $Exports<'react-redux/dist/cjs'>;
}
declare module 'react-redux/dist/react-redux.legacy-esm.js' {
  declare module.exports: $Exports<'react-redux/dist/react-redux.legacy-esm'>;
}
