// flow-typed signature: 892821024bd62c212b28af2da6eadcc2
// flow-typed version: <<STUB>>/redux-first-history_v^5.2.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-first-history'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-first-history' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-first-history/build/es5/actions' {
  declare module.exports: any;
}

declare module 'redux-first-history/build/es5/create' {
  declare module.exports: any;
}

declare module 'redux-first-history/build/es5' {
  declare module.exports: any;
}

declare module 'redux-first-history/build/es5/middleware' {
  declare module.exports: any;
}

declare module 'redux-first-history/build/es5/reachify' {
  declare module.exports: any;
}

declare module 'redux-first-history/build/es5/reachify.types' {
  declare module.exports: any;
}

declare module 'redux-first-history/build/es5/reducer' {
  declare module.exports: any;
}

declare module 'redux-first-history/build/es6/actions' {
  declare module.exports: any;
}

declare module 'redux-first-history/build/es6/create' {
  declare module.exports: any;
}

declare module 'redux-first-history/build/es6' {
  declare module.exports: any;
}

declare module 'redux-first-history/build/es6/middleware' {
  declare module.exports: any;
}

declare module 'redux-first-history/build/es6/reachify' {
  declare module.exports: any;
}

declare module 'redux-first-history/build/es6/reachify.types' {
  declare module.exports: any;
}

declare module 'redux-first-history/build/es6/reducer' {
  declare module.exports: any;
}

declare module 'redux-first-history/rr6' {
  declare module.exports: any;
}

declare module 'redux-first-history/wouter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-first-history/build/es5/actions.js' {
  declare module.exports: $Exports<'redux-first-history/build/es5/actions'>;
}
declare module 'redux-first-history/build/es5/create.js' {
  declare module.exports: $Exports<'redux-first-history/build/es5/create'>;
}
declare module 'redux-first-history/build/es5/index' {
  declare module.exports: $Exports<'redux-first-history/build/es5'>;
}
declare module 'redux-first-history/build/es5/index.js' {
  declare module.exports: $Exports<'redux-first-history/build/es5'>;
}
declare module 'redux-first-history/build/es5/middleware.js' {
  declare module.exports: $Exports<'redux-first-history/build/es5/middleware'>;
}
declare module 'redux-first-history/build/es5/reachify.js' {
  declare module.exports: $Exports<'redux-first-history/build/es5/reachify'>;
}
declare module 'redux-first-history/build/es5/reachify.types.js' {
  declare module.exports: $Exports<'redux-first-history/build/es5/reachify.types'>;
}
declare module 'redux-first-history/build/es5/reducer.js' {
  declare module.exports: $Exports<'redux-first-history/build/es5/reducer'>;
}
declare module 'redux-first-history/build/es6/actions.js' {
  declare module.exports: $Exports<'redux-first-history/build/es6/actions'>;
}
declare module 'redux-first-history/build/es6/create.js' {
  declare module.exports: $Exports<'redux-first-history/build/es6/create'>;
}
declare module 'redux-first-history/build/es6/index' {
  declare module.exports: $Exports<'redux-first-history/build/es6'>;
}
declare module 'redux-first-history/build/es6/index.js' {
  declare module.exports: $Exports<'redux-first-history/build/es6'>;
}
declare module 'redux-first-history/build/es6/middleware.js' {
  declare module.exports: $Exports<'redux-first-history/build/es6/middleware'>;
}
declare module 'redux-first-history/build/es6/reachify.js' {
  declare module.exports: $Exports<'redux-first-history/build/es6/reachify'>;
}
declare module 'redux-first-history/build/es6/reachify.types.js' {
  declare module.exports: $Exports<'redux-first-history/build/es6/reachify.types'>;
}
declare module 'redux-first-history/build/es6/reducer.js' {
  declare module.exports: $Exports<'redux-first-history/build/es6/reducer'>;
}
declare module 'redux-first-history/rr6/index' {
  declare module.exports: $Exports<'redux-first-history/rr6'>;
}
declare module 'redux-first-history/rr6/index.js' {
  declare module.exports: $Exports<'redux-first-history/rr6'>;
}
declare module 'redux-first-history/wouter/index' {
  declare module.exports: $Exports<'redux-first-history/wouter'>;
}
declare module 'redux-first-history/wouter/index.js' {
  declare module.exports: $Exports<'redux-first-history/wouter'>;
}
