// flow-typed signature: 37ba67fcddbe65b635429ea4965aff9f
// flow-typed version: <<STUB>>/storybook_v^8.1.10/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'storybook' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'storybook/index' {
  declare module.exports: $Exports<'storybook'>;
}
declare module 'storybook/index.js' {
  declare module.exports: $Exports<'storybook'>;
}
