// flow-typed signature: 374941da45c2af0ba90f8f875a339d0f
// flow-typed version: <<STUB>>/storybook_v^7.5.2/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'storybook' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storybook/jest.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storybook/index' {
  declare module.exports: $Exports<'storybook'>;
}
declare module 'storybook/index.js' {
  declare module.exports: $Exports<'storybook'>;
}
declare module 'storybook/jest.config.js' {
  declare module.exports: $Exports<'storybook/jest.config'>;
}
