// flow-typed signature: 377c2c7a18c3706d076800419940022d
// flow-typed version: <<STUB>>/storybook_v^8.6.12/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'storybook' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storybook/__mocks__/@aw-web-design/x-default-browser' {
  declare module.exports: any;
}

declare module 'storybook/core' {
  declare module.exports: any;
}

declare module 'storybook/core/babel' {
  declare module.exports: any;
}

declare module 'storybook/core/builder-manager' {
  declare module.exports: any;
}

declare module 'storybook/core/channels' {
  declare module.exports: any;
}

declare module 'storybook/core/cli/bin' {
  declare module.exports: any;
}

declare module 'storybook/core/cli' {
  declare module.exports: any;
}

declare module 'storybook/core/client-logger' {
  declare module.exports: any;
}

declare module 'storybook/core/common' {
  declare module.exports: any;
}

declare module 'storybook/core/components' {
  declare module.exports: any;
}

declare module 'storybook/core/core-events' {
  declare module.exports: any;
}

declare module 'storybook/core/core-server' {
  declare module.exports: any;
}

declare module 'storybook/core/core-server/presets/common-manager' {
  declare module.exports: any;
}

declare module 'storybook/core/core-server/presets/common-override-preset' {
  declare module.exports: any;
}

declare module 'storybook/core/core-server/presets/common-preset' {
  declare module.exports: any;
}

declare module 'storybook/core/csf-tools' {
  declare module.exports: any;
}

declare module 'storybook/core/csf' {
  declare module.exports: any;
}

declare module 'storybook/core/docs-tools' {
  declare module.exports: any;
}

declare module 'storybook/core/manager-api' {
  declare module.exports: any;
}

declare module 'storybook/core/manager-errors' {
  declare module.exports: any;
}

declare module 'storybook/core/manager/globals-module-info' {
  declare module.exports: any;
}

declare module 'storybook/core/manager/globals-runtime' {
  declare module.exports: any;
}

declare module 'storybook/core/manager/globals' {
  declare module.exports: any;
}

declare module 'storybook/core/node-logger' {
  declare module.exports: any;
}

declare module 'storybook/core/preview-api' {
  declare module.exports: any;
}

declare module 'storybook/core/preview-errors' {
  declare module.exports: any;
}

declare module 'storybook/core/preview/globals' {
  declare module.exports: any;
}

declare module 'storybook/core/preview/runtime' {
  declare module.exports: any;
}

declare module 'storybook/core/router' {
  declare module.exports: any;
}

declare module 'storybook/core/server-errors' {
  declare module.exports: any;
}

declare module 'storybook/core/telemetry' {
  declare module.exports: any;
}

declare module 'storybook/core/theming/create' {
  declare module.exports: any;
}

declare module 'storybook/core/theming' {
  declare module.exports: any;
}

declare module 'storybook/core/types' {
  declare module.exports: any;
}

declare module 'storybook/dist/chunk-OWLSIX54' {
  declare module.exports: any;
}

declare module 'storybook/dist/core-path' {
  declare module.exports: any;
}

declare module 'storybook/dist' {
  declare module.exports: any;
}

declare module 'storybook/dist/proxy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storybook/__mocks__/@aw-web-design/x-default-browser.js' {
  declare module.exports: $Exports<'storybook/__mocks__/@aw-web-design/x-default-browser'>;
}
declare module 'storybook/core.js' {
  declare module.exports: $Exports<'storybook/core'>;
}
declare module 'storybook/core/babel/index' {
  declare module.exports: $Exports<'storybook/core/babel'>;
}
declare module 'storybook/core/babel/index.js' {
  declare module.exports: $Exports<'storybook/core/babel'>;
}
declare module 'storybook/core/builder-manager/index' {
  declare module.exports: $Exports<'storybook/core/builder-manager'>;
}
declare module 'storybook/core/builder-manager/index.js' {
  declare module.exports: $Exports<'storybook/core/builder-manager'>;
}
declare module 'storybook/core/channels/index' {
  declare module.exports: $Exports<'storybook/core/channels'>;
}
declare module 'storybook/core/channels/index.js' {
  declare module.exports: $Exports<'storybook/core/channels'>;
}
declare module 'storybook/core/cli/bin/index' {
  declare module.exports: $Exports<'storybook/core/cli/bin'>;
}
declare module 'storybook/core/cli/bin/index.js' {
  declare module.exports: $Exports<'storybook/core/cli/bin'>;
}
declare module 'storybook/core/cli/index' {
  declare module.exports: $Exports<'storybook/core/cli'>;
}
declare module 'storybook/core/cli/index.js' {
  declare module.exports: $Exports<'storybook/core/cli'>;
}
declare module 'storybook/core/client-logger/index' {
  declare module.exports: $Exports<'storybook/core/client-logger'>;
}
declare module 'storybook/core/client-logger/index.js' {
  declare module.exports: $Exports<'storybook/core/client-logger'>;
}
declare module 'storybook/core/common/index' {
  declare module.exports: $Exports<'storybook/core/common'>;
}
declare module 'storybook/core/common/index.js' {
  declare module.exports: $Exports<'storybook/core/common'>;
}
declare module 'storybook/core/components/index' {
  declare module.exports: $Exports<'storybook/core/components'>;
}
declare module 'storybook/core/components/index.js' {
  declare module.exports: $Exports<'storybook/core/components'>;
}
declare module 'storybook/core/core-events/index' {
  declare module.exports: $Exports<'storybook/core/core-events'>;
}
declare module 'storybook/core/core-events/index.js' {
  declare module.exports: $Exports<'storybook/core/core-events'>;
}
declare module 'storybook/core/core-server/index' {
  declare module.exports: $Exports<'storybook/core/core-server'>;
}
declare module 'storybook/core/core-server/index.js' {
  declare module.exports: $Exports<'storybook/core/core-server'>;
}
declare module 'storybook/core/core-server/presets/common-manager.js' {
  declare module.exports: $Exports<'storybook/core/core-server/presets/common-manager'>;
}
declare module 'storybook/core/core-server/presets/common-override-preset.js' {
  declare module.exports: $Exports<'storybook/core/core-server/presets/common-override-preset'>;
}
declare module 'storybook/core/core-server/presets/common-preset.js' {
  declare module.exports: $Exports<'storybook/core/core-server/presets/common-preset'>;
}
declare module 'storybook/core/csf-tools/index' {
  declare module.exports: $Exports<'storybook/core/csf-tools'>;
}
declare module 'storybook/core/csf-tools/index.js' {
  declare module.exports: $Exports<'storybook/core/csf-tools'>;
}
declare module 'storybook/core/csf/index' {
  declare module.exports: $Exports<'storybook/core/csf'>;
}
declare module 'storybook/core/csf/index.js' {
  declare module.exports: $Exports<'storybook/core/csf'>;
}
declare module 'storybook/core/docs-tools/index' {
  declare module.exports: $Exports<'storybook/core/docs-tools'>;
}
declare module 'storybook/core/docs-tools/index.js' {
  declare module.exports: $Exports<'storybook/core/docs-tools'>;
}
declare module 'storybook/core/index' {
  declare module.exports: $Exports<'storybook/core'>;
}
declare module 'storybook/core/index.js' {
  declare module.exports: $Exports<'storybook/core'>;
}
declare module 'storybook/core/manager-api/index' {
  declare module.exports: $Exports<'storybook/core/manager-api'>;
}
declare module 'storybook/core/manager-api/index.js' {
  declare module.exports: $Exports<'storybook/core/manager-api'>;
}
declare module 'storybook/core/manager-errors.js' {
  declare module.exports: $Exports<'storybook/core/manager-errors'>;
}
declare module 'storybook/core/manager/globals-module-info.js' {
  declare module.exports: $Exports<'storybook/core/manager/globals-module-info'>;
}
declare module 'storybook/core/manager/globals-runtime.js' {
  declare module.exports: $Exports<'storybook/core/manager/globals-runtime'>;
}
declare module 'storybook/core/manager/globals.js' {
  declare module.exports: $Exports<'storybook/core/manager/globals'>;
}
declare module 'storybook/core/node-logger/index' {
  declare module.exports: $Exports<'storybook/core/node-logger'>;
}
declare module 'storybook/core/node-logger/index.js' {
  declare module.exports: $Exports<'storybook/core/node-logger'>;
}
declare module 'storybook/core/preview-api/index' {
  declare module.exports: $Exports<'storybook/core/preview-api'>;
}
declare module 'storybook/core/preview-api/index.js' {
  declare module.exports: $Exports<'storybook/core/preview-api'>;
}
declare module 'storybook/core/preview-errors.js' {
  declare module.exports: $Exports<'storybook/core/preview-errors'>;
}
declare module 'storybook/core/preview/globals.js' {
  declare module.exports: $Exports<'storybook/core/preview/globals'>;
}
declare module 'storybook/core/preview/runtime.js' {
  declare module.exports: $Exports<'storybook/core/preview/runtime'>;
}
declare module 'storybook/core/router/index' {
  declare module.exports: $Exports<'storybook/core/router'>;
}
declare module 'storybook/core/router/index.js' {
  declare module.exports: $Exports<'storybook/core/router'>;
}
declare module 'storybook/core/server-errors.js' {
  declare module.exports: $Exports<'storybook/core/server-errors'>;
}
declare module 'storybook/core/telemetry/index' {
  declare module.exports: $Exports<'storybook/core/telemetry'>;
}
declare module 'storybook/core/telemetry/index.js' {
  declare module.exports: $Exports<'storybook/core/telemetry'>;
}
declare module 'storybook/core/theming/create.js' {
  declare module.exports: $Exports<'storybook/core/theming/create'>;
}
declare module 'storybook/core/theming/index' {
  declare module.exports: $Exports<'storybook/core/theming'>;
}
declare module 'storybook/core/theming/index.js' {
  declare module.exports: $Exports<'storybook/core/theming'>;
}
declare module 'storybook/core/types/index' {
  declare module.exports: $Exports<'storybook/core/types'>;
}
declare module 'storybook/core/types/index.js' {
  declare module.exports: $Exports<'storybook/core/types'>;
}
declare module 'storybook/dist/chunk-OWLSIX54.js' {
  declare module.exports: $Exports<'storybook/dist/chunk-OWLSIX54'>;
}
declare module 'storybook/dist/core-path.js' {
  declare module.exports: $Exports<'storybook/dist/core-path'>;
}
declare module 'storybook/dist/index' {
  declare module.exports: $Exports<'storybook/dist'>;
}
declare module 'storybook/dist/index.js' {
  declare module.exports: $Exports<'storybook/dist'>;
}
declare module 'storybook/dist/proxy.js' {
  declare module.exports: $Exports<'storybook/dist/proxy'>;
}
