// flow-typed signature: e4d4d3ea07f1db2095db2daf9369af7b
// flow-typed version: <<STUB>>/stylelint_v^16.18.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint' {
  declare module.exports: any;
}
