// flow-typed signature: fb2aec83c27806256e3981daf8b230d3
// flow-typed version: <<STUB>>/stylelint_v^16.2.1/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint' {
  declare module.exports: any;
}
