// flow-typed signature: 61c97187d41b54451f8102c4fcf6fd7d
// flow-typed version: <<STUB>>/stylelint_v^16.2.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint' {
  declare module.exports: any;
}
