// flow-typed signature: 2c2c5ab009c2098dca98e14e8d0a328b
// flow-typed version: <<STUB>>/typescript_v^7.0.2/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typescript'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typescript' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'typescript/dist/api/async/api' {
  declare module.exports: any;
}

declare module 'typescript/dist/api/async/client' {
  declare module.exports: any;
}

declare module 'typescript/dist/api/async/types' {
  declare module.exports: any;
}

declare module 'typescript/dist/api/compilerOptions' {
  declare module.exports: any;
}

declare module 'typescript/dist/api/fs' {
  declare module.exports: any;
}

declare module 'typescript/dist/api/node/encoder.generated' {
  declare module.exports: any;
}

declare module 'typescript/dist/api/node/encoder' {
  declare module.exports: any;
}

declare module 'typescript/dist/api/node/msgpack' {
  declare module.exports: any;
}

declare module 'typescript/dist/api/node/node.generated' {
  declare module.exports: any;
}

declare module 'typescript/dist/api/node/node.infrastructure' {
  declare module.exports: any;
}

declare module 'typescript/dist/api/node/node' {
  declare module.exports: any;
}

declare module 'typescript/dist/api/node/protocol.generated' {
  declare module.exports: any;
}

declare module 'typescript/dist/api/node/protocol' {
  declare module.exports: any;
}

declare module 'typescript/dist/api/node/wtf8' {
  declare module.exports: any;
}

declare module 'typescript/dist/api/options' {
  declare module.exports: any;
}

declare module 'typescript/dist/api/path' {
  declare module.exports: any;
}

declare module 'typescript/dist/api/proto' {
  declare module.exports: any;
}

declare module 'typescript/dist/api/sourceFileCache' {
  declare module.exports: any;
}

declare module 'typescript/dist/api/sync/api' {
  declare module.exports: any;
}

declare module 'typescript/dist/api/sync/client' {
  declare module.exports: any;
}

declare module 'typescript/dist/api/sync/types' {
  declare module.exports: any;
}

declare module 'typescript/dist/api/syncChannel' {
  declare module.exports: any;
}

declare module 'typescript/dist/api/timing' {
  declare module.exports: any;
}

declare module 'typescript/dist/ast/ast.generated' {
  declare module.exports: any;
}

declare module 'typescript/dist/ast/ast' {
  declare module.exports: any;
}

declare module 'typescript/dist/ast/astnav' {
  declare module.exports: any;
}

declare module 'typescript/dist/ast/clone' {
  declare module.exports: any;
}

declare module 'typescript/dist/ast/factory.generated' {
  declare module.exports: any;
}

declare module 'typescript/dist/ast' {
  declare module.exports: any;
}

declare module 'typescript/dist/ast/is.generated' {
  declare module.exports: any;
}

declare module 'typescript/dist/ast/is' {
  declare module.exports: any;
}

declare module 'typescript/dist/ast/jsdoc' {
  declare module.exports: any;
}

declare module 'typescript/dist/ast/scanner' {
  declare module.exports: any;
}

declare module 'typescript/dist/ast/utils' {
  declare module.exports: any;
}

declare module 'typescript/dist/ast/visitor.generated' {
  declare module.exports: any;
}

declare module 'typescript/dist/ast/visitor' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/characterCodes.enum' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/characterCodes' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/commentDirectiveType.enum' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/commentDirectiveType' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/completionItemKind.enum' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/completionItemKind' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/diagnosticCategory.enum' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/diagnosticCategory' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/elementFlags.enum' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/elementFlags' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/internalSymbolName.enum' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/internalSymbolName' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/jsxEmit.enum' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/jsxEmit' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/languageVariant.enum' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/languageVariant' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/modifierFlags.enum' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/modifierFlags' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/moduleDetectionKind.enum' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/moduleDetectionKind' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/moduleKind.enum' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/moduleKind' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/moduleResolutionKind.enum' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/moduleResolutionKind' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/newLineKind.enum' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/newLineKind' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/nodeBuilderFlags.enum' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/nodeBuilderFlags' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/nodeFlags.enum' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/nodeFlags' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/objectFlags.enum' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/objectFlags' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/outerExpressionKinds.enum' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/outerExpressionKinds' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/regularExpressionFlags.enum' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/regularExpressionFlags' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/scriptKind.enum' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/scriptKind' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/scriptTarget.enum' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/scriptTarget' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/signatureFlags.enum' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/signatureFlags' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/signatureKind.enum' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/signatureKind' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/symbolFlags.enum' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/symbolFlags' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/syntaxKind.enum' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/syntaxKind' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/tokenFlags.enum' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/tokenFlags' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/typeFlags.enum' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/typeFlags' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/typePredicateKind.enum' {
  declare module.exports: any;
}

declare module 'typescript/dist/enums/typePredicateKind' {
  declare module.exports: any;
}

declare module 'typescript/dist/internal/utils' {
  declare module.exports: any;
}

declare module 'typescript/lib/getExePath' {
  declare module.exports: any;
}

declare module 'typescript/lib/tsc' {
  declare module.exports: any;
}

declare module 'typescript/vendor/vscode-jsonrpc/lib/browser/main' {
  declare module.exports: any;
}

declare module 'typescript/vendor/vscode-jsonrpc/lib/browser/ril' {
  declare module.exports: any;
}

declare module 'typescript/vendor/vscode-jsonrpc/lib/common/api' {
  declare module.exports: any;
}

declare module 'typescript/vendor/vscode-jsonrpc/lib/common/cancellation' {
  declare module.exports: any;
}

declare module 'typescript/vendor/vscode-jsonrpc/lib/common/connection' {
  declare module.exports: any;
}

declare module 'typescript/vendor/vscode-jsonrpc/lib/common/disposable' {
  declare module.exports: any;
}

declare module 'typescript/vendor/vscode-jsonrpc/lib/common/encoding' {
  declare module.exports: any;
}

declare module 'typescript/vendor/vscode-jsonrpc/lib/common/events' {
  declare module.exports: any;
}

declare module 'typescript/vendor/vscode-jsonrpc/lib/common/is' {
  declare module.exports: any;
}

declare module 'typescript/vendor/vscode-jsonrpc/lib/common/linkedMap' {
  declare module.exports: any;
}

declare module 'typescript/vendor/vscode-jsonrpc/lib/common/messageBuffer' {
  declare module.exports: any;
}

declare module 'typescript/vendor/vscode-jsonrpc/lib/common/messageReader' {
  declare module.exports: any;
}

declare module 'typescript/vendor/vscode-jsonrpc/lib/common/messages' {
  declare module.exports: any;
}

declare module 'typescript/vendor/vscode-jsonrpc/lib/common/messageWriter' {
  declare module.exports: any;
}

declare module 'typescript/vendor/vscode-jsonrpc/lib/common/ral' {
  declare module.exports: any;
}

declare module 'typescript/vendor/vscode-jsonrpc/lib/common/semaphore' {
  declare module.exports: any;
}

declare module 'typescript/vendor/vscode-jsonrpc/lib/common/sharedArrayCancellation' {
  declare module.exports: any;
}

declare module 'typescript/vendor/vscode-jsonrpc/lib/node/main' {
  declare module.exports: any;
}

declare module 'typescript/vendor/vscode-jsonrpc/lib/node/ril' {
  declare module.exports: any;
}

// Filename aliases
declare module 'typescript/dist/api/async/api.js' {
  declare module.exports: $Exports<'typescript/dist/api/async/api'>;
}
declare module 'typescript/dist/api/async/client.js' {
  declare module.exports: $Exports<'typescript/dist/api/async/client'>;
}
declare module 'typescript/dist/api/async/types.js' {
  declare module.exports: $Exports<'typescript/dist/api/async/types'>;
}
declare module 'typescript/dist/api/compilerOptions.js' {
  declare module.exports: $Exports<'typescript/dist/api/compilerOptions'>;
}
declare module 'typescript/dist/api/fs.js' {
  declare module.exports: $Exports<'typescript/dist/api/fs'>;
}
declare module 'typescript/dist/api/node/encoder.generated.js' {
  declare module.exports: $Exports<'typescript/dist/api/node/encoder.generated'>;
}
declare module 'typescript/dist/api/node/encoder.js' {
  declare module.exports: $Exports<'typescript/dist/api/node/encoder'>;
}
declare module 'typescript/dist/api/node/msgpack.js' {
  declare module.exports: $Exports<'typescript/dist/api/node/msgpack'>;
}
declare module 'typescript/dist/api/node/node.generated.js' {
  declare module.exports: $Exports<'typescript/dist/api/node/node.generated'>;
}
declare module 'typescript/dist/api/node/node.infrastructure.js' {
  declare module.exports: $Exports<'typescript/dist/api/node/node.infrastructure'>;
}
declare module 'typescript/dist/api/node/node.js' {
  declare module.exports: $Exports<'typescript/dist/api/node/node'>;
}
declare module 'typescript/dist/api/node/protocol.generated.js' {
  declare module.exports: $Exports<'typescript/dist/api/node/protocol.generated'>;
}
declare module 'typescript/dist/api/node/protocol.js' {
  declare module.exports: $Exports<'typescript/dist/api/node/protocol'>;
}
declare module 'typescript/dist/api/node/wtf8.js' {
  declare module.exports: $Exports<'typescript/dist/api/node/wtf8'>;
}
declare module 'typescript/dist/api/options.js' {
  declare module.exports: $Exports<'typescript/dist/api/options'>;
}
declare module 'typescript/dist/api/path.js' {
  declare module.exports: $Exports<'typescript/dist/api/path'>;
}
declare module 'typescript/dist/api/proto.js' {
  declare module.exports: $Exports<'typescript/dist/api/proto'>;
}
declare module 'typescript/dist/api/sourceFileCache.js' {
  declare module.exports: $Exports<'typescript/dist/api/sourceFileCache'>;
}
declare module 'typescript/dist/api/sync/api.js' {
  declare module.exports: $Exports<'typescript/dist/api/sync/api'>;
}
declare module 'typescript/dist/api/sync/client.js' {
  declare module.exports: $Exports<'typescript/dist/api/sync/client'>;
}
declare module 'typescript/dist/api/sync/types.js' {
  declare module.exports: $Exports<'typescript/dist/api/sync/types'>;
}
declare module 'typescript/dist/api/syncChannel.js' {
  declare module.exports: $Exports<'typescript/dist/api/syncChannel'>;
}
declare module 'typescript/dist/api/timing.js' {
  declare module.exports: $Exports<'typescript/dist/api/timing'>;
}
declare module 'typescript/dist/ast/ast.generated.js' {
  declare module.exports: $Exports<'typescript/dist/ast/ast.generated'>;
}
declare module 'typescript/dist/ast/ast.js' {
  declare module.exports: $Exports<'typescript/dist/ast/ast'>;
}
declare module 'typescript/dist/ast/astnav.js' {
  declare module.exports: $Exports<'typescript/dist/ast/astnav'>;
}
declare module 'typescript/dist/ast/clone.js' {
  declare module.exports: $Exports<'typescript/dist/ast/clone'>;
}
declare module 'typescript/dist/ast/factory.generated.js' {
  declare module.exports: $Exports<'typescript/dist/ast/factory.generated'>;
}
declare module 'typescript/dist/ast/index' {
  declare module.exports: $Exports<'typescript/dist/ast'>;
}
declare module 'typescript/dist/ast/index.js' {
  declare module.exports: $Exports<'typescript/dist/ast'>;
}
declare module 'typescript/dist/ast/is.generated.js' {
  declare module.exports: $Exports<'typescript/dist/ast/is.generated'>;
}
declare module 'typescript/dist/ast/is.js' {
  declare module.exports: $Exports<'typescript/dist/ast/is'>;
}
declare module 'typescript/dist/ast/jsdoc.js' {
  declare module.exports: $Exports<'typescript/dist/ast/jsdoc'>;
}
declare module 'typescript/dist/ast/scanner.js' {
  declare module.exports: $Exports<'typescript/dist/ast/scanner'>;
}
declare module 'typescript/dist/ast/utils.js' {
  declare module.exports: $Exports<'typescript/dist/ast/utils'>;
}
declare module 'typescript/dist/ast/visitor.generated.js' {
  declare module.exports: $Exports<'typescript/dist/ast/visitor.generated'>;
}
declare module 'typescript/dist/ast/visitor.js' {
  declare module.exports: $Exports<'typescript/dist/ast/visitor'>;
}
declare module 'typescript/dist/enums/characterCodes.enum.js' {
  declare module.exports: $Exports<'typescript/dist/enums/characterCodes.enum'>;
}
declare module 'typescript/dist/enums/characterCodes.js' {
  declare module.exports: $Exports<'typescript/dist/enums/characterCodes'>;
}
declare module 'typescript/dist/enums/commentDirectiveType.enum.js' {
  declare module.exports: $Exports<'typescript/dist/enums/commentDirectiveType.enum'>;
}
declare module 'typescript/dist/enums/commentDirectiveType.js' {
  declare module.exports: $Exports<'typescript/dist/enums/commentDirectiveType'>;
}
declare module 'typescript/dist/enums/completionItemKind.enum.js' {
  declare module.exports: $Exports<'typescript/dist/enums/completionItemKind.enum'>;
}
declare module 'typescript/dist/enums/completionItemKind.js' {
  declare module.exports: $Exports<'typescript/dist/enums/completionItemKind'>;
}
declare module 'typescript/dist/enums/diagnosticCategory.enum.js' {
  declare module.exports: $Exports<'typescript/dist/enums/diagnosticCategory.enum'>;
}
declare module 'typescript/dist/enums/diagnosticCategory.js' {
  declare module.exports: $Exports<'typescript/dist/enums/diagnosticCategory'>;
}
declare module 'typescript/dist/enums/elementFlags.enum.js' {
  declare module.exports: $Exports<'typescript/dist/enums/elementFlags.enum'>;
}
declare module 'typescript/dist/enums/elementFlags.js' {
  declare module.exports: $Exports<'typescript/dist/enums/elementFlags'>;
}
declare module 'typescript/dist/enums/internalSymbolName.enum.js' {
  declare module.exports: $Exports<'typescript/dist/enums/internalSymbolName.enum'>;
}
declare module 'typescript/dist/enums/internalSymbolName.js' {
  declare module.exports: $Exports<'typescript/dist/enums/internalSymbolName'>;
}
declare module 'typescript/dist/enums/jsxEmit.enum.js' {
  declare module.exports: $Exports<'typescript/dist/enums/jsxEmit.enum'>;
}
declare module 'typescript/dist/enums/jsxEmit.js' {
  declare module.exports: $Exports<'typescript/dist/enums/jsxEmit'>;
}
declare module 'typescript/dist/enums/languageVariant.enum.js' {
  declare module.exports: $Exports<'typescript/dist/enums/languageVariant.enum'>;
}
declare module 'typescript/dist/enums/languageVariant.js' {
  declare module.exports: $Exports<'typescript/dist/enums/languageVariant'>;
}
declare module 'typescript/dist/enums/modifierFlags.enum.js' {
  declare module.exports: $Exports<'typescript/dist/enums/modifierFlags.enum'>;
}
declare module 'typescript/dist/enums/modifierFlags.js' {
  declare module.exports: $Exports<'typescript/dist/enums/modifierFlags'>;
}
declare module 'typescript/dist/enums/moduleDetectionKind.enum.js' {
  declare module.exports: $Exports<'typescript/dist/enums/moduleDetectionKind.enum'>;
}
declare module 'typescript/dist/enums/moduleDetectionKind.js' {
  declare module.exports: $Exports<'typescript/dist/enums/moduleDetectionKind'>;
}
declare module 'typescript/dist/enums/moduleKind.enum.js' {
  declare module.exports: $Exports<'typescript/dist/enums/moduleKind.enum'>;
}
declare module 'typescript/dist/enums/moduleKind.js' {
  declare module.exports: $Exports<'typescript/dist/enums/moduleKind'>;
}
declare module 'typescript/dist/enums/moduleResolutionKind.enum.js' {
  declare module.exports: $Exports<'typescript/dist/enums/moduleResolutionKind.enum'>;
}
declare module 'typescript/dist/enums/moduleResolutionKind.js' {
  declare module.exports: $Exports<'typescript/dist/enums/moduleResolutionKind'>;
}
declare module 'typescript/dist/enums/newLineKind.enum.js' {
  declare module.exports: $Exports<'typescript/dist/enums/newLineKind.enum'>;
}
declare module 'typescript/dist/enums/newLineKind.js' {
  declare module.exports: $Exports<'typescript/dist/enums/newLineKind'>;
}
declare module 'typescript/dist/enums/nodeBuilderFlags.enum.js' {
  declare module.exports: $Exports<'typescript/dist/enums/nodeBuilderFlags.enum'>;
}
declare module 'typescript/dist/enums/nodeBuilderFlags.js' {
  declare module.exports: $Exports<'typescript/dist/enums/nodeBuilderFlags'>;
}
declare module 'typescript/dist/enums/nodeFlags.enum.js' {
  declare module.exports: $Exports<'typescript/dist/enums/nodeFlags.enum'>;
}
declare module 'typescript/dist/enums/nodeFlags.js' {
  declare module.exports: $Exports<'typescript/dist/enums/nodeFlags'>;
}
declare module 'typescript/dist/enums/objectFlags.enum.js' {
  declare module.exports: $Exports<'typescript/dist/enums/objectFlags.enum'>;
}
declare module 'typescript/dist/enums/objectFlags.js' {
  declare module.exports: $Exports<'typescript/dist/enums/objectFlags'>;
}
declare module 'typescript/dist/enums/outerExpressionKinds.enum.js' {
  declare module.exports: $Exports<'typescript/dist/enums/outerExpressionKinds.enum'>;
}
declare module 'typescript/dist/enums/outerExpressionKinds.js' {
  declare module.exports: $Exports<'typescript/dist/enums/outerExpressionKinds'>;
}
declare module 'typescript/dist/enums/regularExpressionFlags.enum.js' {
  declare module.exports: $Exports<'typescript/dist/enums/regularExpressionFlags.enum'>;
}
declare module 'typescript/dist/enums/regularExpressionFlags.js' {
  declare module.exports: $Exports<'typescript/dist/enums/regularExpressionFlags'>;
}
declare module 'typescript/dist/enums/scriptKind.enum.js' {
  declare module.exports: $Exports<'typescript/dist/enums/scriptKind.enum'>;
}
declare module 'typescript/dist/enums/scriptKind.js' {
  declare module.exports: $Exports<'typescript/dist/enums/scriptKind'>;
}
declare module 'typescript/dist/enums/scriptTarget.enum.js' {
  declare module.exports: $Exports<'typescript/dist/enums/scriptTarget.enum'>;
}
declare module 'typescript/dist/enums/scriptTarget.js' {
  declare module.exports: $Exports<'typescript/dist/enums/scriptTarget'>;
}
declare module 'typescript/dist/enums/signatureFlags.enum.js' {
  declare module.exports: $Exports<'typescript/dist/enums/signatureFlags.enum'>;
}
declare module 'typescript/dist/enums/signatureFlags.js' {
  declare module.exports: $Exports<'typescript/dist/enums/signatureFlags'>;
}
declare module 'typescript/dist/enums/signatureKind.enum.js' {
  declare module.exports: $Exports<'typescript/dist/enums/signatureKind.enum'>;
}
declare module 'typescript/dist/enums/signatureKind.js' {
  declare module.exports: $Exports<'typescript/dist/enums/signatureKind'>;
}
declare module 'typescript/dist/enums/symbolFlags.enum.js' {
  declare module.exports: $Exports<'typescript/dist/enums/symbolFlags.enum'>;
}
declare module 'typescript/dist/enums/symbolFlags.js' {
  declare module.exports: $Exports<'typescript/dist/enums/symbolFlags'>;
}
declare module 'typescript/dist/enums/syntaxKind.enum.js' {
  declare module.exports: $Exports<'typescript/dist/enums/syntaxKind.enum'>;
}
declare module 'typescript/dist/enums/syntaxKind.js' {
  declare module.exports: $Exports<'typescript/dist/enums/syntaxKind'>;
}
declare module 'typescript/dist/enums/tokenFlags.enum.js' {
  declare module.exports: $Exports<'typescript/dist/enums/tokenFlags.enum'>;
}
declare module 'typescript/dist/enums/tokenFlags.js' {
  declare module.exports: $Exports<'typescript/dist/enums/tokenFlags'>;
}
declare module 'typescript/dist/enums/typeFlags.enum.js' {
  declare module.exports: $Exports<'typescript/dist/enums/typeFlags.enum'>;
}
declare module 'typescript/dist/enums/typeFlags.js' {
  declare module.exports: $Exports<'typescript/dist/enums/typeFlags'>;
}
declare module 'typescript/dist/enums/typePredicateKind.enum.js' {
  declare module.exports: $Exports<'typescript/dist/enums/typePredicateKind.enum'>;
}
declare module 'typescript/dist/enums/typePredicateKind.js' {
  declare module.exports: $Exports<'typescript/dist/enums/typePredicateKind'>;
}
declare module 'typescript/dist/internal/utils.js' {
  declare module.exports: $Exports<'typescript/dist/internal/utils'>;
}
declare module 'typescript/lib/getExePath.js' {
  declare module.exports: $Exports<'typescript/lib/getExePath'>;
}
declare module 'typescript/lib/tsc.js' {
  declare module.exports: $Exports<'typescript/lib/tsc'>;
}
declare module 'typescript/vendor/vscode-jsonrpc/lib/browser/main.js' {
  declare module.exports: $Exports<'typescript/vendor/vscode-jsonrpc/lib/browser/main'>;
}
declare module 'typescript/vendor/vscode-jsonrpc/lib/browser/ril.js' {
  declare module.exports: $Exports<'typescript/vendor/vscode-jsonrpc/lib/browser/ril'>;
}
declare module 'typescript/vendor/vscode-jsonrpc/lib/common/api.js' {
  declare module.exports: $Exports<'typescript/vendor/vscode-jsonrpc/lib/common/api'>;
}
declare module 'typescript/vendor/vscode-jsonrpc/lib/common/cancellation.js' {
  declare module.exports: $Exports<'typescript/vendor/vscode-jsonrpc/lib/common/cancellation'>;
}
declare module 'typescript/vendor/vscode-jsonrpc/lib/common/connection.js' {
  declare module.exports: $Exports<'typescript/vendor/vscode-jsonrpc/lib/common/connection'>;
}
declare module 'typescript/vendor/vscode-jsonrpc/lib/common/disposable.js' {
  declare module.exports: $Exports<'typescript/vendor/vscode-jsonrpc/lib/common/disposable'>;
}
declare module 'typescript/vendor/vscode-jsonrpc/lib/common/encoding.js' {
  declare module.exports: $Exports<'typescript/vendor/vscode-jsonrpc/lib/common/encoding'>;
}
declare module 'typescript/vendor/vscode-jsonrpc/lib/common/events.js' {
  declare module.exports: $Exports<'typescript/vendor/vscode-jsonrpc/lib/common/events'>;
}
declare module 'typescript/vendor/vscode-jsonrpc/lib/common/is.js' {
  declare module.exports: $Exports<'typescript/vendor/vscode-jsonrpc/lib/common/is'>;
}
declare module 'typescript/vendor/vscode-jsonrpc/lib/common/linkedMap.js' {
  declare module.exports: $Exports<'typescript/vendor/vscode-jsonrpc/lib/common/linkedMap'>;
}
declare module 'typescript/vendor/vscode-jsonrpc/lib/common/messageBuffer.js' {
  declare module.exports: $Exports<'typescript/vendor/vscode-jsonrpc/lib/common/messageBuffer'>;
}
declare module 'typescript/vendor/vscode-jsonrpc/lib/common/messageReader.js' {
  declare module.exports: $Exports<'typescript/vendor/vscode-jsonrpc/lib/common/messageReader'>;
}
declare module 'typescript/vendor/vscode-jsonrpc/lib/common/messages.js' {
  declare module.exports: $Exports<'typescript/vendor/vscode-jsonrpc/lib/common/messages'>;
}
declare module 'typescript/vendor/vscode-jsonrpc/lib/common/messageWriter.js' {
  declare module.exports: $Exports<'typescript/vendor/vscode-jsonrpc/lib/common/messageWriter'>;
}
declare module 'typescript/vendor/vscode-jsonrpc/lib/common/ral.js' {
  declare module.exports: $Exports<'typescript/vendor/vscode-jsonrpc/lib/common/ral'>;
}
declare module 'typescript/vendor/vscode-jsonrpc/lib/common/semaphore.js' {
  declare module.exports: $Exports<'typescript/vendor/vscode-jsonrpc/lib/common/semaphore'>;
}
declare module 'typescript/vendor/vscode-jsonrpc/lib/common/sharedArrayCancellation.js' {
  declare module.exports: $Exports<'typescript/vendor/vscode-jsonrpc/lib/common/sharedArrayCancellation'>;
}
declare module 'typescript/vendor/vscode-jsonrpc/lib/node/main.js' {
  declare module.exports: $Exports<'typescript/vendor/vscode-jsonrpc/lib/node/main'>;
}
declare module 'typescript/vendor/vscode-jsonrpc/lib/node/ril.js' {
  declare module.exports: $Exports<'typescript/vendor/vscode-jsonrpc/lib/node/ril'>;
}
