// flow-typed signature: 18f963e5126605348ead9e0620a10cf2
// flow-typed version: <<STUB>>/universal-cookie_v^8.1.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'universal-cookie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'universal-cookie' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'universal-cookie/cjs' {
  declare module.exports: any;
}

declare module 'universal-cookie/umd/universalCookie' {
  declare module.exports: any;
}

declare module 'universal-cookie/umd/universalCookie.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'universal-cookie/cjs/index' {
  declare module.exports: $Exports<'universal-cookie/cjs'>;
}
declare module 'universal-cookie/cjs/index.js' {
  declare module.exports: $Exports<'universal-cookie/cjs'>;
}
declare module 'universal-cookie/umd/universalCookie.js' {
  declare module.exports: $Exports<'universal-cookie/umd/universalCookie'>;
}
declare module 'universal-cookie/umd/universalCookie.min.js' {
  declare module.exports: $Exports<'universal-cookie/umd/universalCookie.min'>;
}
