// flow-typed signature: 240664c72e40b715d7c0464292777221
// flow-typed version: <<STUB>>/uuid_v^11.1.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uuid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uuid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uuid/dist/cjs-browser' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs-browser/max' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs-browser/md5' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs-browser/native' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs-browser/nil' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs-browser/parse' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs-browser/regex' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs-browser/rng' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs-browser/sha1' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs-browser/stringify' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs-browser/types' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs-browser/uuid-bin' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs-browser/v1' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs-browser/v1ToV6' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs-browser/v3' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs-browser/v35' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs-browser/v4' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs-browser/v5' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs-browser/v6' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs-browser/v6ToV1' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs-browser/v7' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs-browser/validate' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs-browser/version' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs/max' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs/md5' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs/native' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs/nil' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs/parse' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs/regex' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs/rng' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs/sha1' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs/stringify' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs/types' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs/uuid-bin' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs/v1' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs/v1ToV6' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs/v3' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs/v35' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs/v4' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs/v5' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs/v6' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs/v6ToV1' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs/v7' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs/validate' {
  declare module.exports: any;
}

declare module 'uuid/dist/cjs/version' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/max' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/md5' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/native' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/nil' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/parse' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/regex' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/rng' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/sha1' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/stringify' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/types' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/uuid-bin' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/v1' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/v1ToV6' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/v3' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/v35' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/v4' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/v5' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/v6' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/v6ToV1' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/v7' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/validate' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/version' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm/max' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm/md5' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm/native' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm/nil' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm/parse' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm/regex' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm/rng' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm/sha1' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm/stringify' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm/types' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm/uuid-bin' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm/v1' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm/v1ToV6' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm/v3' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm/v35' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm/v4' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm/v5' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm/v6' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm/v6ToV1' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm/v7' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm/validate' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm/version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uuid/dist/cjs-browser/index' {
  declare module.exports: $Exports<'uuid/dist/cjs-browser'>;
}
declare module 'uuid/dist/cjs-browser/index.js' {
  declare module.exports: $Exports<'uuid/dist/cjs-browser'>;
}
declare module 'uuid/dist/cjs-browser/max.js' {
  declare module.exports: $Exports<'uuid/dist/cjs-browser/max'>;
}
declare module 'uuid/dist/cjs-browser/md5.js' {
  declare module.exports: $Exports<'uuid/dist/cjs-browser/md5'>;
}
declare module 'uuid/dist/cjs-browser/native.js' {
  declare module.exports: $Exports<'uuid/dist/cjs-browser/native'>;
}
declare module 'uuid/dist/cjs-browser/nil.js' {
  declare module.exports: $Exports<'uuid/dist/cjs-browser/nil'>;
}
declare module 'uuid/dist/cjs-browser/parse.js' {
  declare module.exports: $Exports<'uuid/dist/cjs-browser/parse'>;
}
declare module 'uuid/dist/cjs-browser/regex.js' {
  declare module.exports: $Exports<'uuid/dist/cjs-browser/regex'>;
}
declare module 'uuid/dist/cjs-browser/rng.js' {
  declare module.exports: $Exports<'uuid/dist/cjs-browser/rng'>;
}
declare module 'uuid/dist/cjs-browser/sha1.js' {
  declare module.exports: $Exports<'uuid/dist/cjs-browser/sha1'>;
}
declare module 'uuid/dist/cjs-browser/stringify.js' {
  declare module.exports: $Exports<'uuid/dist/cjs-browser/stringify'>;
}
declare module 'uuid/dist/cjs-browser/types.js' {
  declare module.exports: $Exports<'uuid/dist/cjs-browser/types'>;
}
declare module 'uuid/dist/cjs-browser/uuid-bin.js' {
  declare module.exports: $Exports<'uuid/dist/cjs-browser/uuid-bin'>;
}
declare module 'uuid/dist/cjs-browser/v1.js' {
  declare module.exports: $Exports<'uuid/dist/cjs-browser/v1'>;
}
declare module 'uuid/dist/cjs-browser/v1ToV6.js' {
  declare module.exports: $Exports<'uuid/dist/cjs-browser/v1ToV6'>;
}
declare module 'uuid/dist/cjs-browser/v3.js' {
  declare module.exports: $Exports<'uuid/dist/cjs-browser/v3'>;
}
declare module 'uuid/dist/cjs-browser/v35.js' {
  declare module.exports: $Exports<'uuid/dist/cjs-browser/v35'>;
}
declare module 'uuid/dist/cjs-browser/v4.js' {
  declare module.exports: $Exports<'uuid/dist/cjs-browser/v4'>;
}
declare module 'uuid/dist/cjs-browser/v5.js' {
  declare module.exports: $Exports<'uuid/dist/cjs-browser/v5'>;
}
declare module 'uuid/dist/cjs-browser/v6.js' {
  declare module.exports: $Exports<'uuid/dist/cjs-browser/v6'>;
}
declare module 'uuid/dist/cjs-browser/v6ToV1.js' {
  declare module.exports: $Exports<'uuid/dist/cjs-browser/v6ToV1'>;
}
declare module 'uuid/dist/cjs-browser/v7.js' {
  declare module.exports: $Exports<'uuid/dist/cjs-browser/v7'>;
}
declare module 'uuid/dist/cjs-browser/validate.js' {
  declare module.exports: $Exports<'uuid/dist/cjs-browser/validate'>;
}
declare module 'uuid/dist/cjs-browser/version.js' {
  declare module.exports: $Exports<'uuid/dist/cjs-browser/version'>;
}
declare module 'uuid/dist/cjs/index' {
  declare module.exports: $Exports<'uuid/dist/cjs'>;
}
declare module 'uuid/dist/cjs/index.js' {
  declare module.exports: $Exports<'uuid/dist/cjs'>;
}
declare module 'uuid/dist/cjs/max.js' {
  declare module.exports: $Exports<'uuid/dist/cjs/max'>;
}
declare module 'uuid/dist/cjs/md5.js' {
  declare module.exports: $Exports<'uuid/dist/cjs/md5'>;
}
declare module 'uuid/dist/cjs/native.js' {
  declare module.exports: $Exports<'uuid/dist/cjs/native'>;
}
declare module 'uuid/dist/cjs/nil.js' {
  declare module.exports: $Exports<'uuid/dist/cjs/nil'>;
}
declare module 'uuid/dist/cjs/parse.js' {
  declare module.exports: $Exports<'uuid/dist/cjs/parse'>;
}
declare module 'uuid/dist/cjs/regex.js' {
  declare module.exports: $Exports<'uuid/dist/cjs/regex'>;
}
declare module 'uuid/dist/cjs/rng.js' {
  declare module.exports: $Exports<'uuid/dist/cjs/rng'>;
}
declare module 'uuid/dist/cjs/sha1.js' {
  declare module.exports: $Exports<'uuid/dist/cjs/sha1'>;
}
declare module 'uuid/dist/cjs/stringify.js' {
  declare module.exports: $Exports<'uuid/dist/cjs/stringify'>;
}
declare module 'uuid/dist/cjs/types.js' {
  declare module.exports: $Exports<'uuid/dist/cjs/types'>;
}
declare module 'uuid/dist/cjs/uuid-bin.js' {
  declare module.exports: $Exports<'uuid/dist/cjs/uuid-bin'>;
}
declare module 'uuid/dist/cjs/v1.js' {
  declare module.exports: $Exports<'uuid/dist/cjs/v1'>;
}
declare module 'uuid/dist/cjs/v1ToV6.js' {
  declare module.exports: $Exports<'uuid/dist/cjs/v1ToV6'>;
}
declare module 'uuid/dist/cjs/v3.js' {
  declare module.exports: $Exports<'uuid/dist/cjs/v3'>;
}
declare module 'uuid/dist/cjs/v35.js' {
  declare module.exports: $Exports<'uuid/dist/cjs/v35'>;
}
declare module 'uuid/dist/cjs/v4.js' {
  declare module.exports: $Exports<'uuid/dist/cjs/v4'>;
}
declare module 'uuid/dist/cjs/v5.js' {
  declare module.exports: $Exports<'uuid/dist/cjs/v5'>;
}
declare module 'uuid/dist/cjs/v6.js' {
  declare module.exports: $Exports<'uuid/dist/cjs/v6'>;
}
declare module 'uuid/dist/cjs/v6ToV1.js' {
  declare module.exports: $Exports<'uuid/dist/cjs/v6ToV1'>;
}
declare module 'uuid/dist/cjs/v7.js' {
  declare module.exports: $Exports<'uuid/dist/cjs/v7'>;
}
declare module 'uuid/dist/cjs/validate.js' {
  declare module.exports: $Exports<'uuid/dist/cjs/validate'>;
}
declare module 'uuid/dist/cjs/version.js' {
  declare module.exports: $Exports<'uuid/dist/cjs/version'>;
}
declare module 'uuid/dist/esm-browser/index' {
  declare module.exports: $Exports<'uuid/dist/esm-browser'>;
}
declare module 'uuid/dist/esm-browser/index.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser'>;
}
declare module 'uuid/dist/esm-browser/max.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/max'>;
}
declare module 'uuid/dist/esm-browser/md5.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/md5'>;
}
declare module 'uuid/dist/esm-browser/native.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/native'>;
}
declare module 'uuid/dist/esm-browser/nil.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/nil'>;
}
declare module 'uuid/dist/esm-browser/parse.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/parse'>;
}
declare module 'uuid/dist/esm-browser/regex.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/regex'>;
}
declare module 'uuid/dist/esm-browser/rng.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/rng'>;
}
declare module 'uuid/dist/esm-browser/sha1.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/sha1'>;
}
declare module 'uuid/dist/esm-browser/stringify.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/stringify'>;
}
declare module 'uuid/dist/esm-browser/types.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/types'>;
}
declare module 'uuid/dist/esm-browser/uuid-bin.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/uuid-bin'>;
}
declare module 'uuid/dist/esm-browser/v1.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/v1'>;
}
declare module 'uuid/dist/esm-browser/v1ToV6.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/v1ToV6'>;
}
declare module 'uuid/dist/esm-browser/v3.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/v3'>;
}
declare module 'uuid/dist/esm-browser/v35.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/v35'>;
}
declare module 'uuid/dist/esm-browser/v4.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/v4'>;
}
declare module 'uuid/dist/esm-browser/v5.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/v5'>;
}
declare module 'uuid/dist/esm-browser/v6.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/v6'>;
}
declare module 'uuid/dist/esm-browser/v6ToV1.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/v6ToV1'>;
}
declare module 'uuid/dist/esm-browser/v7.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/v7'>;
}
declare module 'uuid/dist/esm-browser/validate.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/validate'>;
}
declare module 'uuid/dist/esm-browser/version.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/version'>;
}
declare module 'uuid/dist/esm/index' {
  declare module.exports: $Exports<'uuid/dist/esm'>;
}
declare module 'uuid/dist/esm/index.js' {
  declare module.exports: $Exports<'uuid/dist/esm'>;
}
declare module 'uuid/dist/esm/max.js' {
  declare module.exports: $Exports<'uuid/dist/esm/max'>;
}
declare module 'uuid/dist/esm/md5.js' {
  declare module.exports: $Exports<'uuid/dist/esm/md5'>;
}
declare module 'uuid/dist/esm/native.js' {
  declare module.exports: $Exports<'uuid/dist/esm/native'>;
}
declare module 'uuid/dist/esm/nil.js' {
  declare module.exports: $Exports<'uuid/dist/esm/nil'>;
}
declare module 'uuid/dist/esm/parse.js' {
  declare module.exports: $Exports<'uuid/dist/esm/parse'>;
}
declare module 'uuid/dist/esm/regex.js' {
  declare module.exports: $Exports<'uuid/dist/esm/regex'>;
}
declare module 'uuid/dist/esm/rng.js' {
  declare module.exports: $Exports<'uuid/dist/esm/rng'>;
}
declare module 'uuid/dist/esm/sha1.js' {
  declare module.exports: $Exports<'uuid/dist/esm/sha1'>;
}
declare module 'uuid/dist/esm/stringify.js' {
  declare module.exports: $Exports<'uuid/dist/esm/stringify'>;
}
declare module 'uuid/dist/esm/types.js' {
  declare module.exports: $Exports<'uuid/dist/esm/types'>;
}
declare module 'uuid/dist/esm/uuid-bin.js' {
  declare module.exports: $Exports<'uuid/dist/esm/uuid-bin'>;
}
declare module 'uuid/dist/esm/v1.js' {
  declare module.exports: $Exports<'uuid/dist/esm/v1'>;
}
declare module 'uuid/dist/esm/v1ToV6.js' {
  declare module.exports: $Exports<'uuid/dist/esm/v1ToV6'>;
}
declare module 'uuid/dist/esm/v3.js' {
  declare module.exports: $Exports<'uuid/dist/esm/v3'>;
}
declare module 'uuid/dist/esm/v35.js' {
  declare module.exports: $Exports<'uuid/dist/esm/v35'>;
}
declare module 'uuid/dist/esm/v4.js' {
  declare module.exports: $Exports<'uuid/dist/esm/v4'>;
}
declare module 'uuid/dist/esm/v5.js' {
  declare module.exports: $Exports<'uuid/dist/esm/v5'>;
}
declare module 'uuid/dist/esm/v6.js' {
  declare module.exports: $Exports<'uuid/dist/esm/v6'>;
}
declare module 'uuid/dist/esm/v6ToV1.js' {
  declare module.exports: $Exports<'uuid/dist/esm/v6ToV1'>;
}
declare module 'uuid/dist/esm/v7.js' {
  declare module.exports: $Exports<'uuid/dist/esm/v7'>;
}
declare module 'uuid/dist/esm/validate.js' {
  declare module.exports: $Exports<'uuid/dist/esm/validate'>;
}
declare module 'uuid/dist/esm/version.js' {
  declare module.exports: $Exports<'uuid/dist/esm/version'>;
}
