// flow-typed signature: d3420f8a23b9a5f5ae90fc3fb6f8d6bb
// flow-typed version: <<STUB>>/uuid_v^13.0.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uuid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uuid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uuid/dist-node' {
  declare module.exports: any;
}

declare module 'uuid/dist-node/max' {
  declare module.exports: any;
}

declare module 'uuid/dist-node/md5' {
  declare module.exports: any;
}

declare module 'uuid/dist-node/native' {
  declare module.exports: any;
}

declare module 'uuid/dist-node/nil' {
  declare module.exports: any;
}

declare module 'uuid/dist-node/parse' {
  declare module.exports: any;
}

declare module 'uuid/dist-node/regex' {
  declare module.exports: any;
}

declare module 'uuid/dist-node/rng' {
  declare module.exports: any;
}

declare module 'uuid/dist-node/sha1' {
  declare module.exports: any;
}

declare module 'uuid/dist-node/stringify' {
  declare module.exports: any;
}

declare module 'uuid/dist-node/types' {
  declare module.exports: any;
}

declare module 'uuid/dist-node/uuid-bin' {
  declare module.exports: any;
}

declare module 'uuid/dist-node/v1' {
  declare module.exports: any;
}

declare module 'uuid/dist-node/v1ToV6' {
  declare module.exports: any;
}

declare module 'uuid/dist-node/v3' {
  declare module.exports: any;
}

declare module 'uuid/dist-node/v35' {
  declare module.exports: any;
}

declare module 'uuid/dist-node/v4' {
  declare module.exports: any;
}

declare module 'uuid/dist-node/v5' {
  declare module.exports: any;
}

declare module 'uuid/dist-node/v6' {
  declare module.exports: any;
}

declare module 'uuid/dist-node/v6ToV1' {
  declare module.exports: any;
}

declare module 'uuid/dist-node/v7' {
  declare module.exports: any;
}

declare module 'uuid/dist-node/validate' {
  declare module.exports: any;
}

declare module 'uuid/dist-node/version' {
  declare module.exports: any;
}

declare module 'uuid/dist' {
  declare module.exports: any;
}

declare module 'uuid/dist/max' {
  declare module.exports: any;
}

declare module 'uuid/dist/md5' {
  declare module.exports: any;
}

declare module 'uuid/dist/native' {
  declare module.exports: any;
}

declare module 'uuid/dist/nil' {
  declare module.exports: any;
}

declare module 'uuid/dist/parse' {
  declare module.exports: any;
}

declare module 'uuid/dist/regex' {
  declare module.exports: any;
}

declare module 'uuid/dist/rng' {
  declare module.exports: any;
}

declare module 'uuid/dist/sha1' {
  declare module.exports: any;
}

declare module 'uuid/dist/stringify' {
  declare module.exports: any;
}

declare module 'uuid/dist/types' {
  declare module.exports: any;
}

declare module 'uuid/dist/uuid-bin' {
  declare module.exports: any;
}

declare module 'uuid/dist/v1' {
  declare module.exports: any;
}

declare module 'uuid/dist/v1ToV6' {
  declare module.exports: any;
}

declare module 'uuid/dist/v3' {
  declare module.exports: any;
}

declare module 'uuid/dist/v35' {
  declare module.exports: any;
}

declare module 'uuid/dist/v4' {
  declare module.exports: any;
}

declare module 'uuid/dist/v5' {
  declare module.exports: any;
}

declare module 'uuid/dist/v6' {
  declare module.exports: any;
}

declare module 'uuid/dist/v6ToV1' {
  declare module.exports: any;
}

declare module 'uuid/dist/v7' {
  declare module.exports: any;
}

declare module 'uuid/dist/validate' {
  declare module.exports: any;
}

declare module 'uuid/dist/version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uuid/dist-node/index' {
  declare module.exports: $Exports<'uuid/dist-node'>;
}
declare module 'uuid/dist-node/index.js' {
  declare module.exports: $Exports<'uuid/dist-node'>;
}
declare module 'uuid/dist-node/max.js' {
  declare module.exports: $Exports<'uuid/dist-node/max'>;
}
declare module 'uuid/dist-node/md5.js' {
  declare module.exports: $Exports<'uuid/dist-node/md5'>;
}
declare module 'uuid/dist-node/native.js' {
  declare module.exports: $Exports<'uuid/dist-node/native'>;
}
declare module 'uuid/dist-node/nil.js' {
  declare module.exports: $Exports<'uuid/dist-node/nil'>;
}
declare module 'uuid/dist-node/parse.js' {
  declare module.exports: $Exports<'uuid/dist-node/parse'>;
}
declare module 'uuid/dist-node/regex.js' {
  declare module.exports: $Exports<'uuid/dist-node/regex'>;
}
declare module 'uuid/dist-node/rng.js' {
  declare module.exports: $Exports<'uuid/dist-node/rng'>;
}
declare module 'uuid/dist-node/sha1.js' {
  declare module.exports: $Exports<'uuid/dist-node/sha1'>;
}
declare module 'uuid/dist-node/stringify.js' {
  declare module.exports: $Exports<'uuid/dist-node/stringify'>;
}
declare module 'uuid/dist-node/types.js' {
  declare module.exports: $Exports<'uuid/dist-node/types'>;
}
declare module 'uuid/dist-node/uuid-bin.js' {
  declare module.exports: $Exports<'uuid/dist-node/uuid-bin'>;
}
declare module 'uuid/dist-node/v1.js' {
  declare module.exports: $Exports<'uuid/dist-node/v1'>;
}
declare module 'uuid/dist-node/v1ToV6.js' {
  declare module.exports: $Exports<'uuid/dist-node/v1ToV6'>;
}
declare module 'uuid/dist-node/v3.js' {
  declare module.exports: $Exports<'uuid/dist-node/v3'>;
}
declare module 'uuid/dist-node/v35.js' {
  declare module.exports: $Exports<'uuid/dist-node/v35'>;
}
declare module 'uuid/dist-node/v4.js' {
  declare module.exports: $Exports<'uuid/dist-node/v4'>;
}
declare module 'uuid/dist-node/v5.js' {
  declare module.exports: $Exports<'uuid/dist-node/v5'>;
}
declare module 'uuid/dist-node/v6.js' {
  declare module.exports: $Exports<'uuid/dist-node/v6'>;
}
declare module 'uuid/dist-node/v6ToV1.js' {
  declare module.exports: $Exports<'uuid/dist-node/v6ToV1'>;
}
declare module 'uuid/dist-node/v7.js' {
  declare module.exports: $Exports<'uuid/dist-node/v7'>;
}
declare module 'uuid/dist-node/validate.js' {
  declare module.exports: $Exports<'uuid/dist-node/validate'>;
}
declare module 'uuid/dist-node/version.js' {
  declare module.exports: $Exports<'uuid/dist-node/version'>;
}
declare module 'uuid/dist/index' {
  declare module.exports: $Exports<'uuid/dist'>;
}
declare module 'uuid/dist/index.js' {
  declare module.exports: $Exports<'uuid/dist'>;
}
declare module 'uuid/dist/max.js' {
  declare module.exports: $Exports<'uuid/dist/max'>;
}
declare module 'uuid/dist/md5.js' {
  declare module.exports: $Exports<'uuid/dist/md5'>;
}
declare module 'uuid/dist/native.js' {
  declare module.exports: $Exports<'uuid/dist/native'>;
}
declare module 'uuid/dist/nil.js' {
  declare module.exports: $Exports<'uuid/dist/nil'>;
}
declare module 'uuid/dist/parse.js' {
  declare module.exports: $Exports<'uuid/dist/parse'>;
}
declare module 'uuid/dist/regex.js' {
  declare module.exports: $Exports<'uuid/dist/regex'>;
}
declare module 'uuid/dist/rng.js' {
  declare module.exports: $Exports<'uuid/dist/rng'>;
}
declare module 'uuid/dist/sha1.js' {
  declare module.exports: $Exports<'uuid/dist/sha1'>;
}
declare module 'uuid/dist/stringify.js' {
  declare module.exports: $Exports<'uuid/dist/stringify'>;
}
declare module 'uuid/dist/types.js' {
  declare module.exports: $Exports<'uuid/dist/types'>;
}
declare module 'uuid/dist/uuid-bin.js' {
  declare module.exports: $Exports<'uuid/dist/uuid-bin'>;
}
declare module 'uuid/dist/v1.js' {
  declare module.exports: $Exports<'uuid/dist/v1'>;
}
declare module 'uuid/dist/v1ToV6.js' {
  declare module.exports: $Exports<'uuid/dist/v1ToV6'>;
}
declare module 'uuid/dist/v3.js' {
  declare module.exports: $Exports<'uuid/dist/v3'>;
}
declare module 'uuid/dist/v35.js' {
  declare module.exports: $Exports<'uuid/dist/v35'>;
}
declare module 'uuid/dist/v4.js' {
  declare module.exports: $Exports<'uuid/dist/v4'>;
}
declare module 'uuid/dist/v5.js' {
  declare module.exports: $Exports<'uuid/dist/v5'>;
}
declare module 'uuid/dist/v6.js' {
  declare module.exports: $Exports<'uuid/dist/v6'>;
}
declare module 'uuid/dist/v6ToV1.js' {
  declare module.exports: $Exports<'uuid/dist/v6ToV1'>;
}
declare module 'uuid/dist/v7.js' {
  declare module.exports: $Exports<'uuid/dist/v7'>;
}
declare module 'uuid/dist/validate.js' {
  declare module.exports: $Exports<'uuid/dist/validate'>;
}
declare module 'uuid/dist/version.js' {
  declare module.exports: $Exports<'uuid/dist/version'>;
}
