// flow-typed signature: c81513856b16f61053c32496bbd0d52f
// flow-typed version: <<STUB>>/@babel/eslint-parser_v^7.27.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/eslint-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/eslint-parser' {
  declare module.exports: any;
}
