// flow-typed signature: 1ff44a7c5418f7f0490c357c8206cde5
// flow-typed version: <<STUB>>/@babel/eslint-parser_v^7.25.7/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/eslint-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/eslint-parser' {
  declare module.exports: any;
}
