// flow-typed signature: 96586187921be4190d3fec510e670163
// flow-typed version: <<STUB>>/@testing-library/user-event_v^14.6.1/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@testing-library/user-event'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@testing-library/user-event' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@testing-library/user-event/dist/cjs/clipboard/copy' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/clipboard/cut' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/clipboard' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/clipboard/paste' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/convenience/click' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/convenience/hover' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/convenience' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/convenience/tab' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/document/copySelection' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/document/getValueOrTextContent' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/document' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/document/interceptor' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/document/patchFocus' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/document/prepareDocument' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/document/trackValue' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/document/UI' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/event/behavior/click' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/event/behavior/cut' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/event/behavior' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/event/behavior/keydown' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/event/behavior/keypress' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/event/behavior/keyup' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/event/behavior/paste' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/event/behavior/registry' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/event/createEvent' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/event/dispatchEvent' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/event/eventMap' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/event/focus' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/event' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/event/input' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/event/radio' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/event/selection/getInputRange' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/event/selection/getTargetTypeAndSelection' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/event/selection' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/event/selection/modifySelection' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/event/selection/modifySelectionPerMouse' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/event/selection/moveSelection' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/event/selection/resolveCaretPosition' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/event/selection/selectAll' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/event/selection/setSelection' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/event/selection/setSelectionPerMouse' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/event/selection/setSelectionRange' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/event/selection/updateSelectionOnFocus' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/event/types' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/event/wrapEvent' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/keyboard' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/keyboard/keyMap' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/keyboard/parseKeyDef' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/options' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/pointer' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/pointer/keyMap' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/pointer/parseKeyDef' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/setup/api' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/setup/directApi' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/setup' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/setup/setup' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/setup/wrapAsync' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/system' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/system/keyboard' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/system/pointer/buttons' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/system/pointer/device' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/system/pointer' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/system/pointer/mouse' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/system/pointer/pointer' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/system/pointer/shared' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utility/clear' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utility' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utility/selectOptions' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utility/type' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utility/upload' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utils/click/isClickableInput' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utils/dataTransfer/Blob' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utils/dataTransfer/Clipboard' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utils/dataTransfer/DataTransfer' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utils/dataTransfer/FileList' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utils/edit/isContentEditable' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utils/edit/isEditable' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utils/edit/maxLength' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utils/edit/setFiles' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utils/edit/timeValue' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utils/focus/cursor' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utils/focus/getActiveElement' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utils/focus/getTabDestination' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utils/focus/isFocusable' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utils/focus/selection' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utils/focus/selector' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utils' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utils/keyDef/readNextDescriptor' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utils/misc/cloneEvent' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utils/misc/findClosest' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utils/misc/getDocumentFromNode' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utils/misc/getTreeDiff' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utils/misc/getWindow' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utils/misc/isDescendantOrSelf' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utils/misc/isDisabled' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utils/misc/isElementType' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utils/misc/isVisible' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utils/misc/level' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utils/misc/wait' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/cjs/utils/pointer/cssPointerEvents' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/clipboard/copy' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/clipboard/cut' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/clipboard' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/clipboard/paste' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/convenience/click' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/convenience/hover' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/convenience' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/convenience/tab' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/document/copySelection' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/document/getValueOrTextContent' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/document' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/document/interceptor' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/document/patchFocus' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/document/prepareDocument' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/document/trackValue' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/document/UI' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/event/behavior/click' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/event/behavior/cut' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/event/behavior' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/event/behavior/keydown' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/event/behavior/keypress' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/event/behavior/keyup' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/event/behavior/paste' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/event/behavior/registry' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/event/createEvent' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/event/dispatchEvent' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/event/eventMap' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/event/focus' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/event' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/event/input' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/event/radio' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/event/selection/getInputRange' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/event/selection/getTargetTypeAndSelection' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/event/selection' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/event/selection/modifySelection' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/event/selection/modifySelectionPerMouse' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/event/selection/moveSelection' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/event/selection/resolveCaretPosition' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/event/selection/selectAll' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/event/selection/setSelection' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/event/selection/setSelectionPerMouse' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/event/selection/setSelectionRange' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/event/selection/updateSelectionOnFocus' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/event/types' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/event/wrapEvent' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/keyboard' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/keyboard/keyMap' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/keyboard/parseKeyDef' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/options' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/pointer' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/pointer/keyMap' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/pointer/parseKeyDef' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/setup/api' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/setup/directApi' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/setup' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/setup/setup' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/setup/wrapAsync' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/system' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/system/keyboard' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/system/pointer/buttons' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/system/pointer/device' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/system/pointer' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/system/pointer/mouse' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/system/pointer/pointer' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/system/pointer/shared' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utility/clear' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utility' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utility/selectOptions' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utility/type' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utility/upload' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utils/click/isClickableInput' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utils/dataTransfer/Blob' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utils/dataTransfer/Clipboard' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utils/dataTransfer/DataTransfer' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utils/dataTransfer/FileList' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utils/edit/isContentEditable' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utils/edit/isEditable' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utils/edit/maxLength' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utils/edit/setFiles' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utils/edit/timeValue' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utils/focus/cursor' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utils/focus/getActiveElement' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utils/focus/getTabDestination' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utils/focus/isFocusable' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utils/focus/selection' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utils/focus/selector' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utils' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utils/keyDef/readNextDescriptor' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utils/misc/cloneEvent' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utils/misc/findClosest' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utils/misc/getDocumentFromNode' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utils/misc/getTreeDiff' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utils/misc/getWindow' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utils/misc/isDescendantOrSelf' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utils/misc/isDisabled' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utils/misc/isElementType' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utils/misc/isVisible' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utils/misc/level' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utils/misc/wait' {
  declare module.exports: any;
}

declare module '@testing-library/user-event/dist/esm/utils/pointer/cssPointerEvents' {
  declare module.exports: any;
}

// Filename aliases
declare module '@testing-library/user-event/dist/cjs/clipboard/copy.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/clipboard/copy'>;
}
declare module '@testing-library/user-event/dist/cjs/clipboard/cut.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/clipboard/cut'>;
}
declare module '@testing-library/user-event/dist/cjs/clipboard/index' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/clipboard'>;
}
declare module '@testing-library/user-event/dist/cjs/clipboard/index.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/clipboard'>;
}
declare module '@testing-library/user-event/dist/cjs/clipboard/paste.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/clipboard/paste'>;
}
declare module '@testing-library/user-event/dist/cjs/convenience/click.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/convenience/click'>;
}
declare module '@testing-library/user-event/dist/cjs/convenience/hover.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/convenience/hover'>;
}
declare module '@testing-library/user-event/dist/cjs/convenience/index' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/convenience'>;
}
declare module '@testing-library/user-event/dist/cjs/convenience/index.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/convenience'>;
}
declare module '@testing-library/user-event/dist/cjs/convenience/tab.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/convenience/tab'>;
}
declare module '@testing-library/user-event/dist/cjs/document/copySelection.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/document/copySelection'>;
}
declare module '@testing-library/user-event/dist/cjs/document/getValueOrTextContent.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/document/getValueOrTextContent'>;
}
declare module '@testing-library/user-event/dist/cjs/document/index' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/document'>;
}
declare module '@testing-library/user-event/dist/cjs/document/index.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/document'>;
}
declare module '@testing-library/user-event/dist/cjs/document/interceptor.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/document/interceptor'>;
}
declare module '@testing-library/user-event/dist/cjs/document/patchFocus.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/document/patchFocus'>;
}
declare module '@testing-library/user-event/dist/cjs/document/prepareDocument.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/document/prepareDocument'>;
}
declare module '@testing-library/user-event/dist/cjs/document/trackValue.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/document/trackValue'>;
}
declare module '@testing-library/user-event/dist/cjs/document/UI.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/document/UI'>;
}
declare module '@testing-library/user-event/dist/cjs/event/behavior/click.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/event/behavior/click'>;
}
declare module '@testing-library/user-event/dist/cjs/event/behavior/cut.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/event/behavior/cut'>;
}
declare module '@testing-library/user-event/dist/cjs/event/behavior/index' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/event/behavior'>;
}
declare module '@testing-library/user-event/dist/cjs/event/behavior/index.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/event/behavior'>;
}
declare module '@testing-library/user-event/dist/cjs/event/behavior/keydown.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/event/behavior/keydown'>;
}
declare module '@testing-library/user-event/dist/cjs/event/behavior/keypress.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/event/behavior/keypress'>;
}
declare module '@testing-library/user-event/dist/cjs/event/behavior/keyup.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/event/behavior/keyup'>;
}
declare module '@testing-library/user-event/dist/cjs/event/behavior/paste.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/event/behavior/paste'>;
}
declare module '@testing-library/user-event/dist/cjs/event/behavior/registry.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/event/behavior/registry'>;
}
declare module '@testing-library/user-event/dist/cjs/event/createEvent.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/event/createEvent'>;
}
declare module '@testing-library/user-event/dist/cjs/event/dispatchEvent.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/event/dispatchEvent'>;
}
declare module '@testing-library/user-event/dist/cjs/event/eventMap.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/event/eventMap'>;
}
declare module '@testing-library/user-event/dist/cjs/event/focus.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/event/focus'>;
}
declare module '@testing-library/user-event/dist/cjs/event/index' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/event'>;
}
declare module '@testing-library/user-event/dist/cjs/event/index.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/event'>;
}
declare module '@testing-library/user-event/dist/cjs/event/input.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/event/input'>;
}
declare module '@testing-library/user-event/dist/cjs/event/radio.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/event/radio'>;
}
declare module '@testing-library/user-event/dist/cjs/event/selection/getInputRange.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/event/selection/getInputRange'>;
}
declare module '@testing-library/user-event/dist/cjs/event/selection/getTargetTypeAndSelection.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/event/selection/getTargetTypeAndSelection'>;
}
declare module '@testing-library/user-event/dist/cjs/event/selection/index' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/event/selection'>;
}
declare module '@testing-library/user-event/dist/cjs/event/selection/index.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/event/selection'>;
}
declare module '@testing-library/user-event/dist/cjs/event/selection/modifySelection.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/event/selection/modifySelection'>;
}
declare module '@testing-library/user-event/dist/cjs/event/selection/modifySelectionPerMouse.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/event/selection/modifySelectionPerMouse'>;
}
declare module '@testing-library/user-event/dist/cjs/event/selection/moveSelection.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/event/selection/moveSelection'>;
}
declare module '@testing-library/user-event/dist/cjs/event/selection/resolveCaretPosition.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/event/selection/resolveCaretPosition'>;
}
declare module '@testing-library/user-event/dist/cjs/event/selection/selectAll.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/event/selection/selectAll'>;
}
declare module '@testing-library/user-event/dist/cjs/event/selection/setSelection.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/event/selection/setSelection'>;
}
declare module '@testing-library/user-event/dist/cjs/event/selection/setSelectionPerMouse.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/event/selection/setSelectionPerMouse'>;
}
declare module '@testing-library/user-event/dist/cjs/event/selection/setSelectionRange.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/event/selection/setSelectionRange'>;
}
declare module '@testing-library/user-event/dist/cjs/event/selection/updateSelectionOnFocus.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/event/selection/updateSelectionOnFocus'>;
}
declare module '@testing-library/user-event/dist/cjs/event/types.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/event/types'>;
}
declare module '@testing-library/user-event/dist/cjs/event/wrapEvent.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/event/wrapEvent'>;
}
declare module '@testing-library/user-event/dist/cjs/index' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs'>;
}
declare module '@testing-library/user-event/dist/cjs/index.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs'>;
}
declare module '@testing-library/user-event/dist/cjs/keyboard/index' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/keyboard'>;
}
declare module '@testing-library/user-event/dist/cjs/keyboard/index.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/keyboard'>;
}
declare module '@testing-library/user-event/dist/cjs/keyboard/keyMap.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/keyboard/keyMap'>;
}
declare module '@testing-library/user-event/dist/cjs/keyboard/parseKeyDef.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/keyboard/parseKeyDef'>;
}
declare module '@testing-library/user-event/dist/cjs/options.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/options'>;
}
declare module '@testing-library/user-event/dist/cjs/pointer/index' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/pointer'>;
}
declare module '@testing-library/user-event/dist/cjs/pointer/index.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/pointer'>;
}
declare module '@testing-library/user-event/dist/cjs/pointer/keyMap.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/pointer/keyMap'>;
}
declare module '@testing-library/user-event/dist/cjs/pointer/parseKeyDef.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/pointer/parseKeyDef'>;
}
declare module '@testing-library/user-event/dist/cjs/setup/api.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/setup/api'>;
}
declare module '@testing-library/user-event/dist/cjs/setup/directApi.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/setup/directApi'>;
}
declare module '@testing-library/user-event/dist/cjs/setup/index' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/setup'>;
}
declare module '@testing-library/user-event/dist/cjs/setup/index.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/setup'>;
}
declare module '@testing-library/user-event/dist/cjs/setup/setup.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/setup/setup'>;
}
declare module '@testing-library/user-event/dist/cjs/setup/wrapAsync.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/setup/wrapAsync'>;
}
declare module '@testing-library/user-event/dist/cjs/system/index' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/system'>;
}
declare module '@testing-library/user-event/dist/cjs/system/index.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/system'>;
}
declare module '@testing-library/user-event/dist/cjs/system/keyboard.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/system/keyboard'>;
}
declare module '@testing-library/user-event/dist/cjs/system/pointer/buttons.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/system/pointer/buttons'>;
}
declare module '@testing-library/user-event/dist/cjs/system/pointer/device.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/system/pointer/device'>;
}
declare module '@testing-library/user-event/dist/cjs/system/pointer/index' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/system/pointer'>;
}
declare module '@testing-library/user-event/dist/cjs/system/pointer/index.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/system/pointer'>;
}
declare module '@testing-library/user-event/dist/cjs/system/pointer/mouse.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/system/pointer/mouse'>;
}
declare module '@testing-library/user-event/dist/cjs/system/pointer/pointer.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/system/pointer/pointer'>;
}
declare module '@testing-library/user-event/dist/cjs/system/pointer/shared.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/system/pointer/shared'>;
}
declare module '@testing-library/user-event/dist/cjs/utility/clear.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utility/clear'>;
}
declare module '@testing-library/user-event/dist/cjs/utility/index' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utility'>;
}
declare module '@testing-library/user-event/dist/cjs/utility/index.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utility'>;
}
declare module '@testing-library/user-event/dist/cjs/utility/selectOptions.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utility/selectOptions'>;
}
declare module '@testing-library/user-event/dist/cjs/utility/type.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utility/type'>;
}
declare module '@testing-library/user-event/dist/cjs/utility/upload.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utility/upload'>;
}
declare module '@testing-library/user-event/dist/cjs/utils/click/isClickableInput.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utils/click/isClickableInput'>;
}
declare module '@testing-library/user-event/dist/cjs/utils/dataTransfer/Blob.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utils/dataTransfer/Blob'>;
}
declare module '@testing-library/user-event/dist/cjs/utils/dataTransfer/Clipboard.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utils/dataTransfer/Clipboard'>;
}
declare module '@testing-library/user-event/dist/cjs/utils/dataTransfer/DataTransfer.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utils/dataTransfer/DataTransfer'>;
}
declare module '@testing-library/user-event/dist/cjs/utils/dataTransfer/FileList.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utils/dataTransfer/FileList'>;
}
declare module '@testing-library/user-event/dist/cjs/utils/edit/isContentEditable.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utils/edit/isContentEditable'>;
}
declare module '@testing-library/user-event/dist/cjs/utils/edit/isEditable.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utils/edit/isEditable'>;
}
declare module '@testing-library/user-event/dist/cjs/utils/edit/maxLength.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utils/edit/maxLength'>;
}
declare module '@testing-library/user-event/dist/cjs/utils/edit/setFiles.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utils/edit/setFiles'>;
}
declare module '@testing-library/user-event/dist/cjs/utils/edit/timeValue.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utils/edit/timeValue'>;
}
declare module '@testing-library/user-event/dist/cjs/utils/focus/cursor.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utils/focus/cursor'>;
}
declare module '@testing-library/user-event/dist/cjs/utils/focus/getActiveElement.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utils/focus/getActiveElement'>;
}
declare module '@testing-library/user-event/dist/cjs/utils/focus/getTabDestination.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utils/focus/getTabDestination'>;
}
declare module '@testing-library/user-event/dist/cjs/utils/focus/isFocusable.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utils/focus/isFocusable'>;
}
declare module '@testing-library/user-event/dist/cjs/utils/focus/selection.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utils/focus/selection'>;
}
declare module '@testing-library/user-event/dist/cjs/utils/focus/selector.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utils/focus/selector'>;
}
declare module '@testing-library/user-event/dist/cjs/utils/index' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utils'>;
}
declare module '@testing-library/user-event/dist/cjs/utils/index.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utils'>;
}
declare module '@testing-library/user-event/dist/cjs/utils/keyDef/readNextDescriptor.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utils/keyDef/readNextDescriptor'>;
}
declare module '@testing-library/user-event/dist/cjs/utils/misc/cloneEvent.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utils/misc/cloneEvent'>;
}
declare module '@testing-library/user-event/dist/cjs/utils/misc/findClosest.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utils/misc/findClosest'>;
}
declare module '@testing-library/user-event/dist/cjs/utils/misc/getDocumentFromNode.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utils/misc/getDocumentFromNode'>;
}
declare module '@testing-library/user-event/dist/cjs/utils/misc/getTreeDiff.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utils/misc/getTreeDiff'>;
}
declare module '@testing-library/user-event/dist/cjs/utils/misc/getWindow.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utils/misc/getWindow'>;
}
declare module '@testing-library/user-event/dist/cjs/utils/misc/isDescendantOrSelf.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utils/misc/isDescendantOrSelf'>;
}
declare module '@testing-library/user-event/dist/cjs/utils/misc/isDisabled.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utils/misc/isDisabled'>;
}
declare module '@testing-library/user-event/dist/cjs/utils/misc/isElementType.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utils/misc/isElementType'>;
}
declare module '@testing-library/user-event/dist/cjs/utils/misc/isVisible.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utils/misc/isVisible'>;
}
declare module '@testing-library/user-event/dist/cjs/utils/misc/level.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utils/misc/level'>;
}
declare module '@testing-library/user-event/dist/cjs/utils/misc/wait.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utils/misc/wait'>;
}
declare module '@testing-library/user-event/dist/cjs/utils/pointer/cssPointerEvents.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/cjs/utils/pointer/cssPointerEvents'>;
}
declare module '@testing-library/user-event/dist/esm/clipboard/copy.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/clipboard/copy'>;
}
declare module '@testing-library/user-event/dist/esm/clipboard/cut.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/clipboard/cut'>;
}
declare module '@testing-library/user-event/dist/esm/clipboard/index' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/clipboard'>;
}
declare module '@testing-library/user-event/dist/esm/clipboard/index.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/clipboard'>;
}
declare module '@testing-library/user-event/dist/esm/clipboard/paste.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/clipboard/paste'>;
}
declare module '@testing-library/user-event/dist/esm/convenience/click.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/convenience/click'>;
}
declare module '@testing-library/user-event/dist/esm/convenience/hover.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/convenience/hover'>;
}
declare module '@testing-library/user-event/dist/esm/convenience/index' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/convenience'>;
}
declare module '@testing-library/user-event/dist/esm/convenience/index.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/convenience'>;
}
declare module '@testing-library/user-event/dist/esm/convenience/tab.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/convenience/tab'>;
}
declare module '@testing-library/user-event/dist/esm/document/copySelection.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/document/copySelection'>;
}
declare module '@testing-library/user-event/dist/esm/document/getValueOrTextContent.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/document/getValueOrTextContent'>;
}
declare module '@testing-library/user-event/dist/esm/document/index' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/document'>;
}
declare module '@testing-library/user-event/dist/esm/document/index.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/document'>;
}
declare module '@testing-library/user-event/dist/esm/document/interceptor.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/document/interceptor'>;
}
declare module '@testing-library/user-event/dist/esm/document/patchFocus.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/document/patchFocus'>;
}
declare module '@testing-library/user-event/dist/esm/document/prepareDocument.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/document/prepareDocument'>;
}
declare module '@testing-library/user-event/dist/esm/document/trackValue.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/document/trackValue'>;
}
declare module '@testing-library/user-event/dist/esm/document/UI.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/document/UI'>;
}
declare module '@testing-library/user-event/dist/esm/event/behavior/click.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/event/behavior/click'>;
}
declare module '@testing-library/user-event/dist/esm/event/behavior/cut.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/event/behavior/cut'>;
}
declare module '@testing-library/user-event/dist/esm/event/behavior/index' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/event/behavior'>;
}
declare module '@testing-library/user-event/dist/esm/event/behavior/index.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/event/behavior'>;
}
declare module '@testing-library/user-event/dist/esm/event/behavior/keydown.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/event/behavior/keydown'>;
}
declare module '@testing-library/user-event/dist/esm/event/behavior/keypress.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/event/behavior/keypress'>;
}
declare module '@testing-library/user-event/dist/esm/event/behavior/keyup.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/event/behavior/keyup'>;
}
declare module '@testing-library/user-event/dist/esm/event/behavior/paste.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/event/behavior/paste'>;
}
declare module '@testing-library/user-event/dist/esm/event/behavior/registry.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/event/behavior/registry'>;
}
declare module '@testing-library/user-event/dist/esm/event/createEvent.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/event/createEvent'>;
}
declare module '@testing-library/user-event/dist/esm/event/dispatchEvent.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/event/dispatchEvent'>;
}
declare module '@testing-library/user-event/dist/esm/event/eventMap.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/event/eventMap'>;
}
declare module '@testing-library/user-event/dist/esm/event/focus.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/event/focus'>;
}
declare module '@testing-library/user-event/dist/esm/event/index' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/event'>;
}
declare module '@testing-library/user-event/dist/esm/event/index.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/event'>;
}
declare module '@testing-library/user-event/dist/esm/event/input.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/event/input'>;
}
declare module '@testing-library/user-event/dist/esm/event/radio.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/event/radio'>;
}
declare module '@testing-library/user-event/dist/esm/event/selection/getInputRange.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/event/selection/getInputRange'>;
}
declare module '@testing-library/user-event/dist/esm/event/selection/getTargetTypeAndSelection.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/event/selection/getTargetTypeAndSelection'>;
}
declare module '@testing-library/user-event/dist/esm/event/selection/index' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/event/selection'>;
}
declare module '@testing-library/user-event/dist/esm/event/selection/index.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/event/selection'>;
}
declare module '@testing-library/user-event/dist/esm/event/selection/modifySelection.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/event/selection/modifySelection'>;
}
declare module '@testing-library/user-event/dist/esm/event/selection/modifySelectionPerMouse.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/event/selection/modifySelectionPerMouse'>;
}
declare module '@testing-library/user-event/dist/esm/event/selection/moveSelection.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/event/selection/moveSelection'>;
}
declare module '@testing-library/user-event/dist/esm/event/selection/resolveCaretPosition.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/event/selection/resolveCaretPosition'>;
}
declare module '@testing-library/user-event/dist/esm/event/selection/selectAll.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/event/selection/selectAll'>;
}
declare module '@testing-library/user-event/dist/esm/event/selection/setSelection.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/event/selection/setSelection'>;
}
declare module '@testing-library/user-event/dist/esm/event/selection/setSelectionPerMouse.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/event/selection/setSelectionPerMouse'>;
}
declare module '@testing-library/user-event/dist/esm/event/selection/setSelectionRange.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/event/selection/setSelectionRange'>;
}
declare module '@testing-library/user-event/dist/esm/event/selection/updateSelectionOnFocus.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/event/selection/updateSelectionOnFocus'>;
}
declare module '@testing-library/user-event/dist/esm/event/types.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/event/types'>;
}
declare module '@testing-library/user-event/dist/esm/event/wrapEvent.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/event/wrapEvent'>;
}
declare module '@testing-library/user-event/dist/esm/index' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm'>;
}
declare module '@testing-library/user-event/dist/esm/index.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm'>;
}
declare module '@testing-library/user-event/dist/esm/keyboard/index' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/keyboard'>;
}
declare module '@testing-library/user-event/dist/esm/keyboard/index.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/keyboard'>;
}
declare module '@testing-library/user-event/dist/esm/keyboard/keyMap.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/keyboard/keyMap'>;
}
declare module '@testing-library/user-event/dist/esm/keyboard/parseKeyDef.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/keyboard/parseKeyDef'>;
}
declare module '@testing-library/user-event/dist/esm/options.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/options'>;
}
declare module '@testing-library/user-event/dist/esm/pointer/index' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/pointer'>;
}
declare module '@testing-library/user-event/dist/esm/pointer/index.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/pointer'>;
}
declare module '@testing-library/user-event/dist/esm/pointer/keyMap.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/pointer/keyMap'>;
}
declare module '@testing-library/user-event/dist/esm/pointer/parseKeyDef.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/pointer/parseKeyDef'>;
}
declare module '@testing-library/user-event/dist/esm/setup/api.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/setup/api'>;
}
declare module '@testing-library/user-event/dist/esm/setup/directApi.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/setup/directApi'>;
}
declare module '@testing-library/user-event/dist/esm/setup/index' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/setup'>;
}
declare module '@testing-library/user-event/dist/esm/setup/index.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/setup'>;
}
declare module '@testing-library/user-event/dist/esm/setup/setup.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/setup/setup'>;
}
declare module '@testing-library/user-event/dist/esm/setup/wrapAsync.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/setup/wrapAsync'>;
}
declare module '@testing-library/user-event/dist/esm/system/index' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/system'>;
}
declare module '@testing-library/user-event/dist/esm/system/index.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/system'>;
}
declare module '@testing-library/user-event/dist/esm/system/keyboard.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/system/keyboard'>;
}
declare module '@testing-library/user-event/dist/esm/system/pointer/buttons.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/system/pointer/buttons'>;
}
declare module '@testing-library/user-event/dist/esm/system/pointer/device.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/system/pointer/device'>;
}
declare module '@testing-library/user-event/dist/esm/system/pointer/index' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/system/pointer'>;
}
declare module '@testing-library/user-event/dist/esm/system/pointer/index.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/system/pointer'>;
}
declare module '@testing-library/user-event/dist/esm/system/pointer/mouse.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/system/pointer/mouse'>;
}
declare module '@testing-library/user-event/dist/esm/system/pointer/pointer.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/system/pointer/pointer'>;
}
declare module '@testing-library/user-event/dist/esm/system/pointer/shared.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/system/pointer/shared'>;
}
declare module '@testing-library/user-event/dist/esm/utility/clear.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utility/clear'>;
}
declare module '@testing-library/user-event/dist/esm/utility/index' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utility'>;
}
declare module '@testing-library/user-event/dist/esm/utility/index.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utility'>;
}
declare module '@testing-library/user-event/dist/esm/utility/selectOptions.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utility/selectOptions'>;
}
declare module '@testing-library/user-event/dist/esm/utility/type.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utility/type'>;
}
declare module '@testing-library/user-event/dist/esm/utility/upload.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utility/upload'>;
}
declare module '@testing-library/user-event/dist/esm/utils/click/isClickableInput.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utils/click/isClickableInput'>;
}
declare module '@testing-library/user-event/dist/esm/utils/dataTransfer/Blob.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utils/dataTransfer/Blob'>;
}
declare module '@testing-library/user-event/dist/esm/utils/dataTransfer/Clipboard.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utils/dataTransfer/Clipboard'>;
}
declare module '@testing-library/user-event/dist/esm/utils/dataTransfer/DataTransfer.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utils/dataTransfer/DataTransfer'>;
}
declare module '@testing-library/user-event/dist/esm/utils/dataTransfer/FileList.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utils/dataTransfer/FileList'>;
}
declare module '@testing-library/user-event/dist/esm/utils/edit/isContentEditable.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utils/edit/isContentEditable'>;
}
declare module '@testing-library/user-event/dist/esm/utils/edit/isEditable.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utils/edit/isEditable'>;
}
declare module '@testing-library/user-event/dist/esm/utils/edit/maxLength.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utils/edit/maxLength'>;
}
declare module '@testing-library/user-event/dist/esm/utils/edit/setFiles.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utils/edit/setFiles'>;
}
declare module '@testing-library/user-event/dist/esm/utils/edit/timeValue.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utils/edit/timeValue'>;
}
declare module '@testing-library/user-event/dist/esm/utils/focus/cursor.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utils/focus/cursor'>;
}
declare module '@testing-library/user-event/dist/esm/utils/focus/getActiveElement.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utils/focus/getActiveElement'>;
}
declare module '@testing-library/user-event/dist/esm/utils/focus/getTabDestination.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utils/focus/getTabDestination'>;
}
declare module '@testing-library/user-event/dist/esm/utils/focus/isFocusable.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utils/focus/isFocusable'>;
}
declare module '@testing-library/user-event/dist/esm/utils/focus/selection.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utils/focus/selection'>;
}
declare module '@testing-library/user-event/dist/esm/utils/focus/selector.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utils/focus/selector'>;
}
declare module '@testing-library/user-event/dist/esm/utils/index' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utils'>;
}
declare module '@testing-library/user-event/dist/esm/utils/index.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utils'>;
}
declare module '@testing-library/user-event/dist/esm/utils/keyDef/readNextDescriptor.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utils/keyDef/readNextDescriptor'>;
}
declare module '@testing-library/user-event/dist/esm/utils/misc/cloneEvent.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utils/misc/cloneEvent'>;
}
declare module '@testing-library/user-event/dist/esm/utils/misc/findClosest.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utils/misc/findClosest'>;
}
declare module '@testing-library/user-event/dist/esm/utils/misc/getDocumentFromNode.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utils/misc/getDocumentFromNode'>;
}
declare module '@testing-library/user-event/dist/esm/utils/misc/getTreeDiff.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utils/misc/getTreeDiff'>;
}
declare module '@testing-library/user-event/dist/esm/utils/misc/getWindow.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utils/misc/getWindow'>;
}
declare module '@testing-library/user-event/dist/esm/utils/misc/isDescendantOrSelf.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utils/misc/isDescendantOrSelf'>;
}
declare module '@testing-library/user-event/dist/esm/utils/misc/isDisabled.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utils/misc/isDisabled'>;
}
declare module '@testing-library/user-event/dist/esm/utils/misc/isElementType.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utils/misc/isElementType'>;
}
declare module '@testing-library/user-event/dist/esm/utils/misc/isVisible.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utils/misc/isVisible'>;
}
declare module '@testing-library/user-event/dist/esm/utils/misc/level.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utils/misc/level'>;
}
declare module '@testing-library/user-event/dist/esm/utils/misc/wait.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utils/misc/wait'>;
}
declare module '@testing-library/user-event/dist/esm/utils/pointer/cssPointerEvents.js' {
  declare module.exports: $Exports<'@testing-library/user-event/dist/esm/utils/pointer/cssPointerEvents'>;
}
