// flow-typed signature: ef21683a679c9a879953c662ed403a37
// flow-typed version: <<STUB>>/@lagunovsky/redux-react-router_v^3.2.0/flow_v0.176.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@lagunovsky/redux-react-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@lagunovsky/redux-react-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@lagunovsky/redux-react-router/dist/index.es' {
  declare module.exports: any;
}

declare module '@lagunovsky/redux-react-router/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@lagunovsky/redux-react-router/dist/index.es.js' {
  declare module.exports: $Exports<'@lagunovsky/redux-react-router/dist/index.es'>;
}
declare module '@lagunovsky/redux-react-router/dist/index' {
  declare module.exports: $Exports<'@lagunovsky/redux-react-router/dist'>;
}
declare module '@lagunovsky/redux-react-router/dist/index.js' {
  declare module.exports: $Exports<'@lagunovsky/redux-react-router/dist'>;
}
