// flow-typed signature: 96142cd8cf709f7164732dda059eff0d
// flow-typed version: <<STUB>>/@sebastianwessel/esdoc-standard-plugin_v^2.1.0/flow_v0.172.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@sebastianwessel/esdoc-standard-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@sebastianwessel/esdoc-standard-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@sebastianwessel/esdoc-standard-plugin/src/Plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module '@sebastianwessel/esdoc-standard-plugin/src/Plugin.js' {
  declare module.exports: $Exports<'@sebastianwessel/esdoc-standard-plugin/src/Plugin'>;
}
