// flow-typed signature: ec247435aab2197754ece426b45d1f03
// flow-typed version: <<STUB>>/@sebastianwessel/esdoc-jsx-plugin_v^2.1.0/flow_v0.196.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@sebastianwessel/esdoc-jsx-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@sebastianwessel/esdoc-jsx-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@sebastianwessel/esdoc-jsx-plugin/src/Plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module '@sebastianwessel/esdoc-jsx-plugin/src/Plugin.js' {
  declare module.exports: $Exports<'@sebastianwessel/esdoc-jsx-plugin/src/Plugin'>;
}
