// flow-typed signature: 2416d01ec55d834b548600ad4ca5d5b4
// flow-typed version: <<STUB>>/@storybook/addon-actions_v^7.1.1/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-actions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-actions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-actions/dist/decorator' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/jest.config' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/src/runtime/__tests__/action.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/src/runtime/__tests__/actions.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/src/runtime/__tests__/configureActions.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-actions/dist/decorator.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/decorator'>;
}
declare module '@storybook/addon-actions/dist/index' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist'>;
}
declare module '@storybook/addon-actions/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist'>;
}
declare module '@storybook/addon-actions/dist/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/manager'>;
}
declare module '@storybook/addon-actions/dist/preview.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/preview'>;
}
declare module '@storybook/addon-actions/jest.config.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/jest.config'>;
}
declare module '@storybook/addon-actions/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/manager'>;
}
declare module '@storybook/addon-actions/preview.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/preview'>;
}
declare module '@storybook/addon-actions/src/runtime/__tests__/action.test.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/src/runtime/__tests__/action.test'>;
}
declare module '@storybook/addon-actions/src/runtime/__tests__/actions.test.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/src/runtime/__tests__/actions.test'>;
}
declare module '@storybook/addon-actions/src/runtime/__tests__/configureActions.test.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/src/runtime/__tests__/configureActions.test'>;
}
