// flow-typed signature: 28d5444b3a9c67ba54b08740b55f1575
// flow-typed version: <<STUB>>/@storybook/addon-links_v^10.1.11/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-links'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-links' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-links/dist/_browser-chunks/chunk-FX5LXYO2' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/_browser-chunks/chunk-LAYPZ6CY' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/_browser-chunks/chunk-PZ2KFUGG' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/react' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/react' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-links/dist/_browser-chunks/chunk-FX5LXYO2.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/_browser-chunks/chunk-FX5LXYO2'>;
}
declare module '@storybook/addon-links/dist/_browser-chunks/chunk-LAYPZ6CY.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/_browser-chunks/chunk-LAYPZ6CY'>;
}
declare module '@storybook/addon-links/dist/_browser-chunks/chunk-PZ2KFUGG.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/_browser-chunks/chunk-PZ2KFUGG'>;
}
declare module '@storybook/addon-links/dist/index' {
  declare module.exports: $Exports<'@storybook/addon-links/dist'>;
}
declare module '@storybook/addon-links/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist'>;
}
declare module '@storybook/addon-links/dist/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/manager'>;
}
declare module '@storybook/addon-links/dist/preview.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/preview'>;
}
declare module '@storybook/addon-links/dist/react/index' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/react'>;
}
declare module '@storybook/addon-links/dist/react/index.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/react'>;
}
declare module '@storybook/addon-links/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-links/manager'>;
}
declare module '@storybook/addon-links/preview.js' {
  declare module.exports: $Exports<'@storybook/addon-links/preview'>;
}
declare module '@storybook/addon-links/react.js' {
  declare module.exports: $Exports<'@storybook/addon-links/react'>;
}
