// flow-typed signature: 105af46ef2fcb2bf6b9f1526483fa230
// flow-typed version: <<STUB>>/@storybook/addon-essentials_v^7.1.1/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-essentials'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-essentials' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-essentials/dist/actions/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-essentials/dist/actions/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-essentials/dist/backgrounds/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-essentials/dist/backgrounds/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-essentials/dist/controls/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-essentials/dist/docs/mdx-react-shim' {
  declare module.exports: any;
}

declare module '@storybook/addon-essentials/dist/docs/preset' {
  declare module.exports: any;
}

declare module '@storybook/addon-essentials/dist/docs/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-essentials/dist/highlight/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-essentials/dist' {
  declare module.exports: any;
}

declare module '@storybook/addon-essentials/dist/measure/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-essentials/dist/measure/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-essentials/dist/outline/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-essentials/dist/outline/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-essentials/dist/toolbars/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-essentials/dist/viewport/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-essentials/jest.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-essentials/dist/actions/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-essentials/dist/actions/manager'>;
}
declare module '@storybook/addon-essentials/dist/actions/preview.js' {
  declare module.exports: $Exports<'@storybook/addon-essentials/dist/actions/preview'>;
}
declare module '@storybook/addon-essentials/dist/backgrounds/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-essentials/dist/backgrounds/manager'>;
}
declare module '@storybook/addon-essentials/dist/backgrounds/preview.js' {
  declare module.exports: $Exports<'@storybook/addon-essentials/dist/backgrounds/preview'>;
}
declare module '@storybook/addon-essentials/dist/controls/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-essentials/dist/controls/manager'>;
}
declare module '@storybook/addon-essentials/dist/docs/mdx-react-shim.js' {
  declare module.exports: $Exports<'@storybook/addon-essentials/dist/docs/mdx-react-shim'>;
}
declare module '@storybook/addon-essentials/dist/docs/preset.js' {
  declare module.exports: $Exports<'@storybook/addon-essentials/dist/docs/preset'>;
}
declare module '@storybook/addon-essentials/dist/docs/preview.js' {
  declare module.exports: $Exports<'@storybook/addon-essentials/dist/docs/preview'>;
}
declare module '@storybook/addon-essentials/dist/highlight/preview.js' {
  declare module.exports: $Exports<'@storybook/addon-essentials/dist/highlight/preview'>;
}
declare module '@storybook/addon-essentials/dist/index' {
  declare module.exports: $Exports<'@storybook/addon-essentials/dist'>;
}
declare module '@storybook/addon-essentials/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-essentials/dist'>;
}
declare module '@storybook/addon-essentials/dist/measure/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-essentials/dist/measure/manager'>;
}
declare module '@storybook/addon-essentials/dist/measure/preview.js' {
  declare module.exports: $Exports<'@storybook/addon-essentials/dist/measure/preview'>;
}
declare module '@storybook/addon-essentials/dist/outline/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-essentials/dist/outline/manager'>;
}
declare module '@storybook/addon-essentials/dist/outline/preview.js' {
  declare module.exports: $Exports<'@storybook/addon-essentials/dist/outline/preview'>;
}
declare module '@storybook/addon-essentials/dist/toolbars/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-essentials/dist/toolbars/manager'>;
}
declare module '@storybook/addon-essentials/dist/viewport/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-essentials/dist/viewport/manager'>;
}
declare module '@storybook/addon-essentials/jest.config.js' {
  declare module.exports: $Exports<'@storybook/addon-essentials/jest.config'>;
}
