// flow-typed signature: 8ad5c4102b1cd465007df307f69943f9
// flow-typed version: <<STUB>>/@storybook/addon-actions_v^6.5.15/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-actions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-actions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-actions/dist/cjs/components/ActionLogger' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/cjs/components/ActionLogger/style' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/cjs/constants' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/cjs/containers/ActionLogger' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/cjs' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/cjs/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/cjs/models/ActionDisplay' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/cjs/models/ActionOptions' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/cjs/models/ActionsFunction' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/cjs/models/ActionsMap' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/cjs/models/DecoratorFunction' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/cjs/models/HandlerFunction' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/cjs/models' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/cjs/preset/addArgs' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/cjs/preset/addArgsHelpers' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/cjs/preset/addDecorator' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/cjs/preset/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/cjs/preview/action' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/cjs/preview/actions' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/cjs/preview/configureActions' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/cjs/preview/decorateAction' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/cjs/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/cjs/preview/withActions' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/esm/components/ActionLogger' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/esm/components/ActionLogger/style' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/esm/constants' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/esm/containers/ActionLogger' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/esm' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/esm/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/esm/models/ActionDisplay' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/esm/models/ActionOptions' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/esm/models/ActionsFunction' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/esm/models/ActionsMap' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/esm/models/DecoratorFunction' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/esm/models/HandlerFunction' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/esm/models' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/esm/preset/addArgs' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/esm/preset/addArgsHelpers' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/esm/preset/addDecorator' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/esm/preset/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/esm/preview/action' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/esm/preview/actions' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/esm/preview/configureActions' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/esm/preview/decorateAction' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/esm/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/esm/preview/withActions' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/modern/components/ActionLogger' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/modern/components/ActionLogger/style' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/modern/constants' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/modern/containers/ActionLogger' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/modern' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/modern/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/modern/models/ActionDisplay' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/modern/models/ActionOptions' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/modern/models/ActionsFunction' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/modern/models/ActionsMap' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/modern/models/DecoratorFunction' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/modern/models/HandlerFunction' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/modern/models' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/modern/preset/addArgs' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/modern/preset/addArgsHelpers' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/modern/preset/addDecorator' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/modern/preset/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/modern/preview/action' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/modern/preview/actions' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/modern/preview/configureActions' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/modern/preview/decorateAction' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/modern/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/modern/preview/withActions' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/register' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-actions/dist/cjs/components/ActionLogger/index' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/cjs/components/ActionLogger'>;
}
declare module '@storybook/addon-actions/dist/cjs/components/ActionLogger/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/cjs/components/ActionLogger'>;
}
declare module '@storybook/addon-actions/dist/cjs/components/ActionLogger/style.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/cjs/components/ActionLogger/style'>;
}
declare module '@storybook/addon-actions/dist/cjs/constants.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/cjs/constants'>;
}
declare module '@storybook/addon-actions/dist/cjs/containers/ActionLogger/index' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/cjs/containers/ActionLogger'>;
}
declare module '@storybook/addon-actions/dist/cjs/containers/ActionLogger/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/cjs/containers/ActionLogger'>;
}
declare module '@storybook/addon-actions/dist/cjs/index' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/cjs'>;
}
declare module '@storybook/addon-actions/dist/cjs/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/cjs'>;
}
declare module '@storybook/addon-actions/dist/cjs/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/cjs/manager'>;
}
declare module '@storybook/addon-actions/dist/cjs/models/ActionDisplay.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/cjs/models/ActionDisplay'>;
}
declare module '@storybook/addon-actions/dist/cjs/models/ActionOptions.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/cjs/models/ActionOptions'>;
}
declare module '@storybook/addon-actions/dist/cjs/models/ActionsFunction.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/cjs/models/ActionsFunction'>;
}
declare module '@storybook/addon-actions/dist/cjs/models/ActionsMap.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/cjs/models/ActionsMap'>;
}
declare module '@storybook/addon-actions/dist/cjs/models/DecoratorFunction.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/cjs/models/DecoratorFunction'>;
}
declare module '@storybook/addon-actions/dist/cjs/models/HandlerFunction.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/cjs/models/HandlerFunction'>;
}
declare module '@storybook/addon-actions/dist/cjs/models/index' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/cjs/models'>;
}
declare module '@storybook/addon-actions/dist/cjs/models/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/cjs/models'>;
}
declare module '@storybook/addon-actions/dist/cjs/preset/addArgs.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/cjs/preset/addArgs'>;
}
declare module '@storybook/addon-actions/dist/cjs/preset/addArgsHelpers.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/cjs/preset/addArgsHelpers'>;
}
declare module '@storybook/addon-actions/dist/cjs/preset/addDecorator.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/cjs/preset/addDecorator'>;
}
declare module '@storybook/addon-actions/dist/cjs/preset/preview.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/cjs/preset/preview'>;
}
declare module '@storybook/addon-actions/dist/cjs/preview/action.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/cjs/preview/action'>;
}
declare module '@storybook/addon-actions/dist/cjs/preview/actions.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/cjs/preview/actions'>;
}
declare module '@storybook/addon-actions/dist/cjs/preview/configureActions.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/cjs/preview/configureActions'>;
}
declare module '@storybook/addon-actions/dist/cjs/preview/decorateAction.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/cjs/preview/decorateAction'>;
}
declare module '@storybook/addon-actions/dist/cjs/preview/index' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/cjs/preview'>;
}
declare module '@storybook/addon-actions/dist/cjs/preview/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/cjs/preview'>;
}
declare module '@storybook/addon-actions/dist/cjs/preview/withActions.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/cjs/preview/withActions'>;
}
declare module '@storybook/addon-actions/dist/esm/components/ActionLogger/index' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/esm/components/ActionLogger'>;
}
declare module '@storybook/addon-actions/dist/esm/components/ActionLogger/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/esm/components/ActionLogger'>;
}
declare module '@storybook/addon-actions/dist/esm/components/ActionLogger/style.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/esm/components/ActionLogger/style'>;
}
declare module '@storybook/addon-actions/dist/esm/constants.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/esm/constants'>;
}
declare module '@storybook/addon-actions/dist/esm/containers/ActionLogger/index' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/esm/containers/ActionLogger'>;
}
declare module '@storybook/addon-actions/dist/esm/containers/ActionLogger/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/esm/containers/ActionLogger'>;
}
declare module '@storybook/addon-actions/dist/esm/index' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/esm'>;
}
declare module '@storybook/addon-actions/dist/esm/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/esm'>;
}
declare module '@storybook/addon-actions/dist/esm/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/esm/manager'>;
}
declare module '@storybook/addon-actions/dist/esm/models/ActionDisplay.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/esm/models/ActionDisplay'>;
}
declare module '@storybook/addon-actions/dist/esm/models/ActionOptions.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/esm/models/ActionOptions'>;
}
declare module '@storybook/addon-actions/dist/esm/models/ActionsFunction.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/esm/models/ActionsFunction'>;
}
declare module '@storybook/addon-actions/dist/esm/models/ActionsMap.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/esm/models/ActionsMap'>;
}
declare module '@storybook/addon-actions/dist/esm/models/DecoratorFunction.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/esm/models/DecoratorFunction'>;
}
declare module '@storybook/addon-actions/dist/esm/models/HandlerFunction.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/esm/models/HandlerFunction'>;
}
declare module '@storybook/addon-actions/dist/esm/models/index' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/esm/models'>;
}
declare module '@storybook/addon-actions/dist/esm/models/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/esm/models'>;
}
declare module '@storybook/addon-actions/dist/esm/preset/addArgs.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/esm/preset/addArgs'>;
}
declare module '@storybook/addon-actions/dist/esm/preset/addArgsHelpers.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/esm/preset/addArgsHelpers'>;
}
declare module '@storybook/addon-actions/dist/esm/preset/addDecorator.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/esm/preset/addDecorator'>;
}
declare module '@storybook/addon-actions/dist/esm/preset/preview.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/esm/preset/preview'>;
}
declare module '@storybook/addon-actions/dist/esm/preview/action.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/esm/preview/action'>;
}
declare module '@storybook/addon-actions/dist/esm/preview/actions.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/esm/preview/actions'>;
}
declare module '@storybook/addon-actions/dist/esm/preview/configureActions.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/esm/preview/configureActions'>;
}
declare module '@storybook/addon-actions/dist/esm/preview/decorateAction.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/esm/preview/decorateAction'>;
}
declare module '@storybook/addon-actions/dist/esm/preview/index' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/esm/preview'>;
}
declare module '@storybook/addon-actions/dist/esm/preview/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/esm/preview'>;
}
declare module '@storybook/addon-actions/dist/esm/preview/withActions.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/esm/preview/withActions'>;
}
declare module '@storybook/addon-actions/dist/modern/components/ActionLogger/index' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/modern/components/ActionLogger'>;
}
declare module '@storybook/addon-actions/dist/modern/components/ActionLogger/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/modern/components/ActionLogger'>;
}
declare module '@storybook/addon-actions/dist/modern/components/ActionLogger/style.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/modern/components/ActionLogger/style'>;
}
declare module '@storybook/addon-actions/dist/modern/constants.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/modern/constants'>;
}
declare module '@storybook/addon-actions/dist/modern/containers/ActionLogger/index' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/modern/containers/ActionLogger'>;
}
declare module '@storybook/addon-actions/dist/modern/containers/ActionLogger/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/modern/containers/ActionLogger'>;
}
declare module '@storybook/addon-actions/dist/modern/index' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/modern'>;
}
declare module '@storybook/addon-actions/dist/modern/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/modern'>;
}
declare module '@storybook/addon-actions/dist/modern/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/modern/manager'>;
}
declare module '@storybook/addon-actions/dist/modern/models/ActionDisplay.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/modern/models/ActionDisplay'>;
}
declare module '@storybook/addon-actions/dist/modern/models/ActionOptions.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/modern/models/ActionOptions'>;
}
declare module '@storybook/addon-actions/dist/modern/models/ActionsFunction.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/modern/models/ActionsFunction'>;
}
declare module '@storybook/addon-actions/dist/modern/models/ActionsMap.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/modern/models/ActionsMap'>;
}
declare module '@storybook/addon-actions/dist/modern/models/DecoratorFunction.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/modern/models/DecoratorFunction'>;
}
declare module '@storybook/addon-actions/dist/modern/models/HandlerFunction.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/modern/models/HandlerFunction'>;
}
declare module '@storybook/addon-actions/dist/modern/models/index' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/modern/models'>;
}
declare module '@storybook/addon-actions/dist/modern/models/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/modern/models'>;
}
declare module '@storybook/addon-actions/dist/modern/preset/addArgs.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/modern/preset/addArgs'>;
}
declare module '@storybook/addon-actions/dist/modern/preset/addArgsHelpers.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/modern/preset/addArgsHelpers'>;
}
declare module '@storybook/addon-actions/dist/modern/preset/addDecorator.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/modern/preset/addDecorator'>;
}
declare module '@storybook/addon-actions/dist/modern/preset/preview.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/modern/preset/preview'>;
}
declare module '@storybook/addon-actions/dist/modern/preview/action.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/modern/preview/action'>;
}
declare module '@storybook/addon-actions/dist/modern/preview/actions.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/modern/preview/actions'>;
}
declare module '@storybook/addon-actions/dist/modern/preview/configureActions.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/modern/preview/configureActions'>;
}
declare module '@storybook/addon-actions/dist/modern/preview/decorateAction.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/modern/preview/decorateAction'>;
}
declare module '@storybook/addon-actions/dist/modern/preview/index' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/modern/preview'>;
}
declare module '@storybook/addon-actions/dist/modern/preview/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/modern/preview'>;
}
declare module '@storybook/addon-actions/dist/modern/preview/withActions.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/modern/preview/withActions'>;
}
declare module '@storybook/addon-actions/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/manager'>;
}
declare module '@storybook/addon-actions/preview.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/preview'>;
}
declare module '@storybook/addon-actions/register.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/register'>;
}
