// flow-typed signature: 9716ebaf4d17f9d6299b21c5bb692730
// flow-typed version: <<STUB>>/@storybook/builder-webpack4_v^6.5.10/flow_v0.186.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/builder-webpack4'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/builder-webpack4' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/builder-webpack4/dist/cjs' {
  declare module.exports: any;
}

declare module '@storybook/builder-webpack4/dist/cjs/presets/custom-webpack-preset' {
  declare module.exports: any;
}

declare module '@storybook/builder-webpack4/dist/cjs/presets/preview-preset' {
  declare module.exports: any;
}

declare module '@storybook/builder-webpack4/dist/cjs/preview/babel-loader-preview' {
  declare module.exports: any;
}

declare module '@storybook/builder-webpack4/dist/cjs/preview/base-webpack.config' {
  declare module.exports: any;
}

declare module '@storybook/builder-webpack4/dist/cjs/preview/iframe-webpack.config' {
  declare module.exports: any;
}

declare module '@storybook/builder-webpack4/dist/cjs/preview/useBaseTsSupport' {
  declare module.exports: any;
}

declare module '@storybook/builder-webpack4/dist/cjs/preview/virtualModuleEntry.template' {
  declare module.exports: any;
}

declare module '@storybook/builder-webpack4/dist/cjs/preview/virtualModuleStory.template' {
  declare module.exports: any;
}

declare module '@storybook/builder-webpack4/dist/esm' {
  declare module.exports: any;
}

declare module '@storybook/builder-webpack4/dist/esm/presets/custom-webpack-preset' {
  declare module.exports: any;
}

declare module '@storybook/builder-webpack4/dist/esm/presets/preview-preset' {
  declare module.exports: any;
}

declare module '@storybook/builder-webpack4/dist/esm/preview/babel-loader-preview' {
  declare module.exports: any;
}

declare module '@storybook/builder-webpack4/dist/esm/preview/base-webpack.config' {
  declare module.exports: any;
}

declare module '@storybook/builder-webpack4/dist/esm/preview/iframe-webpack.config' {
  declare module.exports: any;
}

declare module '@storybook/builder-webpack4/dist/esm/preview/useBaseTsSupport' {
  declare module.exports: any;
}

declare module '@storybook/builder-webpack4/dist/esm/preview/virtualModuleEntry.template' {
  declare module.exports: any;
}

declare module '@storybook/builder-webpack4/dist/esm/preview/virtualModuleStory.template' {
  declare module.exports: any;
}

declare module '@storybook/builder-webpack4/dist/modern' {
  declare module.exports: any;
}

declare module '@storybook/builder-webpack4/dist/modern/presets/custom-webpack-preset' {
  declare module.exports: any;
}

declare module '@storybook/builder-webpack4/dist/modern/presets/preview-preset' {
  declare module.exports: any;
}

declare module '@storybook/builder-webpack4/dist/modern/preview/babel-loader-preview' {
  declare module.exports: any;
}

declare module '@storybook/builder-webpack4/dist/modern/preview/base-webpack.config' {
  declare module.exports: any;
}

declare module '@storybook/builder-webpack4/dist/modern/preview/iframe-webpack.config' {
  declare module.exports: any;
}

declare module '@storybook/builder-webpack4/dist/modern/preview/useBaseTsSupport' {
  declare module.exports: any;
}

declare module '@storybook/builder-webpack4/dist/modern/preview/virtualModuleEntry.template' {
  declare module.exports: any;
}

declare module '@storybook/builder-webpack4/dist/modern/preview/virtualModuleStory.template' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/builder-webpack4/dist/cjs/index' {
  declare module.exports: $Exports<'@storybook/builder-webpack4/dist/cjs'>;
}
declare module '@storybook/builder-webpack4/dist/cjs/index.js' {
  declare module.exports: $Exports<'@storybook/builder-webpack4/dist/cjs'>;
}
declare module '@storybook/builder-webpack4/dist/cjs/presets/custom-webpack-preset.js' {
  declare module.exports: $Exports<'@storybook/builder-webpack4/dist/cjs/presets/custom-webpack-preset'>;
}
declare module '@storybook/builder-webpack4/dist/cjs/presets/preview-preset.js' {
  declare module.exports: $Exports<'@storybook/builder-webpack4/dist/cjs/presets/preview-preset'>;
}
declare module '@storybook/builder-webpack4/dist/cjs/preview/babel-loader-preview.js' {
  declare module.exports: $Exports<'@storybook/builder-webpack4/dist/cjs/preview/babel-loader-preview'>;
}
declare module '@storybook/builder-webpack4/dist/cjs/preview/base-webpack.config.js' {
  declare module.exports: $Exports<'@storybook/builder-webpack4/dist/cjs/preview/base-webpack.config'>;
}
declare module '@storybook/builder-webpack4/dist/cjs/preview/iframe-webpack.config.js' {
  declare module.exports: $Exports<'@storybook/builder-webpack4/dist/cjs/preview/iframe-webpack.config'>;
}
declare module '@storybook/builder-webpack4/dist/cjs/preview/useBaseTsSupport.js' {
  declare module.exports: $Exports<'@storybook/builder-webpack4/dist/cjs/preview/useBaseTsSupport'>;
}
declare module '@storybook/builder-webpack4/dist/cjs/preview/virtualModuleEntry.template.js' {
  declare module.exports: $Exports<'@storybook/builder-webpack4/dist/cjs/preview/virtualModuleEntry.template'>;
}
declare module '@storybook/builder-webpack4/dist/cjs/preview/virtualModuleStory.template.js' {
  declare module.exports: $Exports<'@storybook/builder-webpack4/dist/cjs/preview/virtualModuleStory.template'>;
}
declare module '@storybook/builder-webpack4/dist/esm/index' {
  declare module.exports: $Exports<'@storybook/builder-webpack4/dist/esm'>;
}
declare module '@storybook/builder-webpack4/dist/esm/index.js' {
  declare module.exports: $Exports<'@storybook/builder-webpack4/dist/esm'>;
}
declare module '@storybook/builder-webpack4/dist/esm/presets/custom-webpack-preset.js' {
  declare module.exports: $Exports<'@storybook/builder-webpack4/dist/esm/presets/custom-webpack-preset'>;
}
declare module '@storybook/builder-webpack4/dist/esm/presets/preview-preset.js' {
  declare module.exports: $Exports<'@storybook/builder-webpack4/dist/esm/presets/preview-preset'>;
}
declare module '@storybook/builder-webpack4/dist/esm/preview/babel-loader-preview.js' {
  declare module.exports: $Exports<'@storybook/builder-webpack4/dist/esm/preview/babel-loader-preview'>;
}
declare module '@storybook/builder-webpack4/dist/esm/preview/base-webpack.config.js' {
  declare module.exports: $Exports<'@storybook/builder-webpack4/dist/esm/preview/base-webpack.config'>;
}
declare module '@storybook/builder-webpack4/dist/esm/preview/iframe-webpack.config.js' {
  declare module.exports: $Exports<'@storybook/builder-webpack4/dist/esm/preview/iframe-webpack.config'>;
}
declare module '@storybook/builder-webpack4/dist/esm/preview/useBaseTsSupport.js' {
  declare module.exports: $Exports<'@storybook/builder-webpack4/dist/esm/preview/useBaseTsSupport'>;
}
declare module '@storybook/builder-webpack4/dist/esm/preview/virtualModuleEntry.template.js' {
  declare module.exports: $Exports<'@storybook/builder-webpack4/dist/esm/preview/virtualModuleEntry.template'>;
}
declare module '@storybook/builder-webpack4/dist/esm/preview/virtualModuleStory.template.js' {
  declare module.exports: $Exports<'@storybook/builder-webpack4/dist/esm/preview/virtualModuleStory.template'>;
}
declare module '@storybook/builder-webpack4/dist/modern/index' {
  declare module.exports: $Exports<'@storybook/builder-webpack4/dist/modern'>;
}
declare module '@storybook/builder-webpack4/dist/modern/index.js' {
  declare module.exports: $Exports<'@storybook/builder-webpack4/dist/modern'>;
}
declare module '@storybook/builder-webpack4/dist/modern/presets/custom-webpack-preset.js' {
  declare module.exports: $Exports<'@storybook/builder-webpack4/dist/modern/presets/custom-webpack-preset'>;
}
declare module '@storybook/builder-webpack4/dist/modern/presets/preview-preset.js' {
  declare module.exports: $Exports<'@storybook/builder-webpack4/dist/modern/presets/preview-preset'>;
}
declare module '@storybook/builder-webpack4/dist/modern/preview/babel-loader-preview.js' {
  declare module.exports: $Exports<'@storybook/builder-webpack4/dist/modern/preview/babel-loader-preview'>;
}
declare module '@storybook/builder-webpack4/dist/modern/preview/base-webpack.config.js' {
  declare module.exports: $Exports<'@storybook/builder-webpack4/dist/modern/preview/base-webpack.config'>;
}
declare module '@storybook/builder-webpack4/dist/modern/preview/iframe-webpack.config.js' {
  declare module.exports: $Exports<'@storybook/builder-webpack4/dist/modern/preview/iframe-webpack.config'>;
}
declare module '@storybook/builder-webpack4/dist/modern/preview/useBaseTsSupport.js' {
  declare module.exports: $Exports<'@storybook/builder-webpack4/dist/modern/preview/useBaseTsSupport'>;
}
declare module '@storybook/builder-webpack4/dist/modern/preview/virtualModuleEntry.template.js' {
  declare module.exports: $Exports<'@storybook/builder-webpack4/dist/modern/preview/virtualModuleEntry.template'>;
}
declare module '@storybook/builder-webpack4/dist/modern/preview/virtualModuleStory.template.js' {
  declare module.exports: $Exports<'@storybook/builder-webpack4/dist/modern/preview/virtualModuleStory.template'>;
}
