// flow-typed signature: b6348e4f68001de4a07069e23ff5f52f
// flow-typed version: <<STUB>>/@storybook/manager-webpack5_v^6.5.14/flow_v0.196.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/manager-webpack5'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/manager-webpack5' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/manager-webpack5/dist/cjs' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/cjs/manager-config' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/cjs/presets/babel-loader-manager' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/cjs/presets/manager-preset' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/cjs/utils/manager-cache' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/cjs/utils/output-stats' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/cjs/utils/prebuilt-manager' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/cjs/virtualModuleRef.template' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/esm' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/esm/manager-config' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/esm/presets/babel-loader-manager' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/esm/presets/manager-preset' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/esm/utils/manager-cache' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/esm/utils/output-stats' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/esm/utils/prebuilt-manager' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/esm/virtualModuleRef.template' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/modern' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/modern/manager-config' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/modern/presets/babel-loader-manager' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/modern/presets/manager-preset' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/modern/utils/manager-cache' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/modern/utils/output-stats' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/modern/utils/prebuilt-manager' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/dist/modern/virtualModuleRef.template' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/manager-preset' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt-manager' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/0.e5489f12ab94aa497491.manager.bundle' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/1.7d0dd704b26935d06a04.manager.bundle' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/10.398dd7a0522c1ff2b3a8.manager.bundle' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/5.23ef655b5acff6eac8ad.manager.bundle' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/6.d2f96bcf3b11b0f1a44b.manager.bundle' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/7.a1c5467faea0833b53d1.manager.bundle' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/8.65ec2749796fb05c258c.manager.bundle' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/9.acd0ef9064e0667433ac.manager.bundle' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/main.bd89f9d2c925d5b084c4.manager.bundle' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/runtime~main.8e5cf3a9715a0d32d390.manager.bundle' {
  declare module.exports: any;
}

declare module '@storybook/manager-webpack5/prebuilt/vendors~main.7c47903ea43e951c3707.manager.bundle' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/manager-webpack5/dist/cjs/index' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/cjs'>;
}
declare module '@storybook/manager-webpack5/dist/cjs/index.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/cjs'>;
}
declare module '@storybook/manager-webpack5/dist/cjs/manager-config.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/cjs/manager-config'>;
}
declare module '@storybook/manager-webpack5/dist/cjs/presets/babel-loader-manager.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/cjs/presets/babel-loader-manager'>;
}
declare module '@storybook/manager-webpack5/dist/cjs/presets/manager-preset.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/cjs/presets/manager-preset'>;
}
declare module '@storybook/manager-webpack5/dist/cjs/utils/manager-cache.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/cjs/utils/manager-cache'>;
}
declare module '@storybook/manager-webpack5/dist/cjs/utils/output-stats.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/cjs/utils/output-stats'>;
}
declare module '@storybook/manager-webpack5/dist/cjs/utils/prebuilt-manager.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/cjs/utils/prebuilt-manager'>;
}
declare module '@storybook/manager-webpack5/dist/cjs/virtualModuleRef.template.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/cjs/virtualModuleRef.template'>;
}
declare module '@storybook/manager-webpack5/dist/esm/index' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/esm'>;
}
declare module '@storybook/manager-webpack5/dist/esm/index.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/esm'>;
}
declare module '@storybook/manager-webpack5/dist/esm/manager-config.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/esm/manager-config'>;
}
declare module '@storybook/manager-webpack5/dist/esm/presets/babel-loader-manager.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/esm/presets/babel-loader-manager'>;
}
declare module '@storybook/manager-webpack5/dist/esm/presets/manager-preset.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/esm/presets/manager-preset'>;
}
declare module '@storybook/manager-webpack5/dist/esm/utils/manager-cache.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/esm/utils/manager-cache'>;
}
declare module '@storybook/manager-webpack5/dist/esm/utils/output-stats.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/esm/utils/output-stats'>;
}
declare module '@storybook/manager-webpack5/dist/esm/utils/prebuilt-manager.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/esm/utils/prebuilt-manager'>;
}
declare module '@storybook/manager-webpack5/dist/esm/virtualModuleRef.template.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/esm/virtualModuleRef.template'>;
}
declare module '@storybook/manager-webpack5/dist/modern/index' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/modern'>;
}
declare module '@storybook/manager-webpack5/dist/modern/index.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/modern'>;
}
declare module '@storybook/manager-webpack5/dist/modern/manager-config.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/modern/manager-config'>;
}
declare module '@storybook/manager-webpack5/dist/modern/presets/babel-loader-manager.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/modern/presets/babel-loader-manager'>;
}
declare module '@storybook/manager-webpack5/dist/modern/presets/manager-preset.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/modern/presets/manager-preset'>;
}
declare module '@storybook/manager-webpack5/dist/modern/utils/manager-cache.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/modern/utils/manager-cache'>;
}
declare module '@storybook/manager-webpack5/dist/modern/utils/output-stats.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/modern/utils/output-stats'>;
}
declare module '@storybook/manager-webpack5/dist/modern/utils/prebuilt-manager.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/modern/utils/prebuilt-manager'>;
}
declare module '@storybook/manager-webpack5/dist/modern/virtualModuleRef.template.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/dist/modern/virtualModuleRef.template'>;
}
declare module '@storybook/manager-webpack5/manager-preset.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/manager-preset'>;
}
declare module '@storybook/manager-webpack5/prebuilt-manager.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt-manager'>;
}
declare module '@storybook/manager-webpack5/prebuilt/0.e5489f12ab94aa497491.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/0.e5489f12ab94aa497491.manager.bundle'>;
}
declare module '@storybook/manager-webpack5/prebuilt/1.7d0dd704b26935d06a04.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/1.7d0dd704b26935d06a04.manager.bundle'>;
}
declare module '@storybook/manager-webpack5/prebuilt/10.398dd7a0522c1ff2b3a8.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/10.398dd7a0522c1ff2b3a8.manager.bundle'>;
}
declare module '@storybook/manager-webpack5/prebuilt/5.23ef655b5acff6eac8ad.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/5.23ef655b5acff6eac8ad.manager.bundle'>;
}
declare module '@storybook/manager-webpack5/prebuilt/6.d2f96bcf3b11b0f1a44b.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/6.d2f96bcf3b11b0f1a44b.manager.bundle'>;
}
declare module '@storybook/manager-webpack5/prebuilt/7.a1c5467faea0833b53d1.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/7.a1c5467faea0833b53d1.manager.bundle'>;
}
declare module '@storybook/manager-webpack5/prebuilt/8.65ec2749796fb05c258c.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/8.65ec2749796fb05c258c.manager.bundle'>;
}
declare module '@storybook/manager-webpack5/prebuilt/9.acd0ef9064e0667433ac.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/9.acd0ef9064e0667433ac.manager.bundle'>;
}
declare module '@storybook/manager-webpack5/prebuilt/main.bd89f9d2c925d5b084c4.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/main.bd89f9d2c925d5b084c4.manager.bundle'>;
}
declare module '@storybook/manager-webpack5/prebuilt/runtime~main.8e5cf3a9715a0d32d390.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/runtime~main.8e5cf3a9715a0d32d390.manager.bundle'>;
}
declare module '@storybook/manager-webpack5/prebuilt/vendors~main.7c47903ea43e951c3707.manager.bundle.js' {
  declare module.exports: $Exports<'@storybook/manager-webpack5/prebuilt/vendors~main.7c47903ea43e951c3707.manager.bundle'>;
}
