// flow-typed signature: 26239b0c16a09d833f56cfbf8b31958f
// flow-typed version: <<STUB>>/@storybook/node-logger_v^8.6.2/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/node-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/node-logger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/node-logger/shim' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/node-logger/shim.js' {
  declare module.exports: $Exports<'@storybook/node-logger/shim'>;
}
