// flow-typed signature: 4fa538287e22ced828dee4a6bf8fd5fc
// flow-typed version: <<STUB>>/@storybook/node-logger_v^8.0.9/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/node-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/node-logger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/node-logger/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/node-logger/dist/index' {
  declare module.exports: $Exports<'@storybook/node-logger/dist'>;
}
declare module '@storybook/node-logger/dist/index.js' {
  declare module.exports: $Exports<'@storybook/node-logger/dist'>;
}
