// flow-typed signature: ed30c637d9521aa458d8069c6be647f4
// flow-typed version: <<STUB>>/@storybook/preset-create-react-app_v^4.1.2/flow_v0.196.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/preset-create-react-app'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/preset-create-react-app' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/preset-create-react-app/dist/helpers/checkPresets' {
  declare module.exports: any;
}

declare module '@storybook/preset-create-react-app/dist/helpers/getModulePath' {
  declare module.exports: any;
}

declare module '@storybook/preset-create-react-app/dist/helpers/getReactScriptsPath' {
  declare module.exports: any;
}

declare module '@storybook/preset-create-react-app/dist/helpers/mergePlugins' {
  declare module.exports: any;
}

declare module '@storybook/preset-create-react-app/dist/helpers/processCraConfig' {
  declare module.exports: any;
}

declare module '@storybook/preset-create-react-app/dist' {
  declare module.exports: any;
}

declare module '@storybook/preset-create-react-app/dist/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/preset-create-react-app/dist/helpers/checkPresets.js' {
  declare module.exports: $Exports<'@storybook/preset-create-react-app/dist/helpers/checkPresets'>;
}
declare module '@storybook/preset-create-react-app/dist/helpers/getModulePath.js' {
  declare module.exports: $Exports<'@storybook/preset-create-react-app/dist/helpers/getModulePath'>;
}
declare module '@storybook/preset-create-react-app/dist/helpers/getReactScriptsPath.js' {
  declare module.exports: $Exports<'@storybook/preset-create-react-app/dist/helpers/getReactScriptsPath'>;
}
declare module '@storybook/preset-create-react-app/dist/helpers/mergePlugins.js' {
  declare module.exports: $Exports<'@storybook/preset-create-react-app/dist/helpers/mergePlugins'>;
}
declare module '@storybook/preset-create-react-app/dist/helpers/processCraConfig.js' {
  declare module.exports: $Exports<'@storybook/preset-create-react-app/dist/helpers/processCraConfig'>;
}
declare module '@storybook/preset-create-react-app/dist/index' {
  declare module.exports: $Exports<'@storybook/preset-create-react-app/dist'>;
}
declare module '@storybook/preset-create-react-app/dist/index.js' {
  declare module.exports: $Exports<'@storybook/preset-create-react-app/dist'>;
}
declare module '@storybook/preset-create-react-app/dist/types.js' {
  declare module.exports: $Exports<'@storybook/preset-create-react-app/dist/types'>;
}
