// flow-typed signature: 2daceac38678aa807df51ccdd9d95183
// flow-typed version: <<STUB>>/@storybook/preset-create-react-app_v^7.1.1/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/preset-create-react-app'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/preset-create-react-app' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/preset-create-react-app/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/preset-create-react-app/dist/index' {
  declare module.exports: $Exports<'@storybook/preset-create-react-app/dist'>;
}
declare module '@storybook/preset-create-react-app/dist/index.js' {
  declare module.exports: $Exports<'@storybook/preset-create-react-app/dist'>;
}
