// flow-typed signature: 81254f20ef135aa9ef9ae47515b34059
// flow-typed version: <<STUB>>/@storybook/react-webpack5_v^7.1.1/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/react-webpack5'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/react-webpack5' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/react-webpack5/dist' {
  declare module.exports: any;
}

declare module '@storybook/react-webpack5/dist/preset' {
  declare module.exports: any;
}

declare module '@storybook/react-webpack5/jest.config' {
  declare module.exports: any;
}

declare module '@storybook/react-webpack5/preset' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/react-webpack5/dist/index' {
  declare module.exports: $Exports<'@storybook/react-webpack5/dist'>;
}
declare module '@storybook/react-webpack5/dist/index.js' {
  declare module.exports: $Exports<'@storybook/react-webpack5/dist'>;
}
declare module '@storybook/react-webpack5/dist/preset.js' {
  declare module.exports: $Exports<'@storybook/react-webpack5/dist/preset'>;
}
declare module '@storybook/react-webpack5/jest.config.js' {
  declare module.exports: $Exports<'@storybook/react-webpack5/jest.config'>;
}
declare module '@storybook/react-webpack5/preset.js' {
  declare module.exports: $Exports<'@storybook/react-webpack5/preset'>;
}
