// flow-typed signature: d9addb0129edae48d909f13c3cd66cb7
// flow-typed version: <<STUB>>/@storybook/react_v^10.1.11/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/react/dist/_browser-chunks/chunk-34HS64JJ' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/_browser-chunks/chunk-7SRU6CYS' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/_browser-chunks/chunk-DDIRQRCA' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/_browser-chunks/chunk-FMVW4CIJ' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/_browser-chunks/chunk-M77NQZM3' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/_browser-chunks/chunk-OCTWNRZO' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/_browser-chunks/chunk-SL3VIQZ3' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/entry-preview-argtypes' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/entry-preview-docs' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/entry-preview-rsc' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/entry-preview' {
  declare module.exports: any;
}

declare module '@storybook/react/dist' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/playwright' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/preset' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/preview' {
  declare module.exports: any;
}

declare module '@storybook/react/preset' {
  declare module.exports: any;
}

declare module '@storybook/react/preview' {
  declare module.exports: any;
}

declare module '@storybook/react/template/cli/js/Button' {
  declare module.exports: any;
}

declare module '@storybook/react/template/cli/js/Button.stories' {
  declare module.exports: any;
}

declare module '@storybook/react/template/cli/js/Header' {
  declare module.exports: any;
}

declare module '@storybook/react/template/cli/js/Header.stories' {
  declare module.exports: any;
}

declare module '@storybook/react/template/cli/js/Page' {
  declare module.exports: any;
}

declare module '@storybook/react/template/cli/js/Page.stories' {
  declare module.exports: any;
}

declare module '@storybook/react/template/components' {
  declare module.exports: any;
}

declare module '@storybook/react/template/stories/docgen-components/imported' {
  declare module.exports: any;
}

declare module '@storybook/react/template/stories/docgen-components/js-proptypes/ext' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/react/dist/_browser-chunks/chunk-34HS64JJ.js' {
  declare module.exports: $Exports<'@storybook/react/dist/_browser-chunks/chunk-34HS64JJ'>;
}
declare module '@storybook/react/dist/_browser-chunks/chunk-7SRU6CYS.js' {
  declare module.exports: $Exports<'@storybook/react/dist/_browser-chunks/chunk-7SRU6CYS'>;
}
declare module '@storybook/react/dist/_browser-chunks/chunk-DDIRQRCA.js' {
  declare module.exports: $Exports<'@storybook/react/dist/_browser-chunks/chunk-DDIRQRCA'>;
}
declare module '@storybook/react/dist/_browser-chunks/chunk-FMVW4CIJ.js' {
  declare module.exports: $Exports<'@storybook/react/dist/_browser-chunks/chunk-FMVW4CIJ'>;
}
declare module '@storybook/react/dist/_browser-chunks/chunk-M77NQZM3.js' {
  declare module.exports: $Exports<'@storybook/react/dist/_browser-chunks/chunk-M77NQZM3'>;
}
declare module '@storybook/react/dist/_browser-chunks/chunk-OCTWNRZO.js' {
  declare module.exports: $Exports<'@storybook/react/dist/_browser-chunks/chunk-OCTWNRZO'>;
}
declare module '@storybook/react/dist/_browser-chunks/chunk-SL3VIQZ3.js' {
  declare module.exports: $Exports<'@storybook/react/dist/_browser-chunks/chunk-SL3VIQZ3'>;
}
declare module '@storybook/react/dist/entry-preview-argtypes.js' {
  declare module.exports: $Exports<'@storybook/react/dist/entry-preview-argtypes'>;
}
declare module '@storybook/react/dist/entry-preview-docs.js' {
  declare module.exports: $Exports<'@storybook/react/dist/entry-preview-docs'>;
}
declare module '@storybook/react/dist/entry-preview-rsc.js' {
  declare module.exports: $Exports<'@storybook/react/dist/entry-preview-rsc'>;
}
declare module '@storybook/react/dist/entry-preview.js' {
  declare module.exports: $Exports<'@storybook/react/dist/entry-preview'>;
}
declare module '@storybook/react/dist/index' {
  declare module.exports: $Exports<'@storybook/react/dist'>;
}
declare module '@storybook/react/dist/index.js' {
  declare module.exports: $Exports<'@storybook/react/dist'>;
}
declare module '@storybook/react/dist/playwright.js' {
  declare module.exports: $Exports<'@storybook/react/dist/playwright'>;
}
declare module '@storybook/react/dist/preset.js' {
  declare module.exports: $Exports<'@storybook/react/dist/preset'>;
}
declare module '@storybook/react/dist/preview.js' {
  declare module.exports: $Exports<'@storybook/react/dist/preview'>;
}
declare module '@storybook/react/preset.js' {
  declare module.exports: $Exports<'@storybook/react/preset'>;
}
declare module '@storybook/react/preview.js' {
  declare module.exports: $Exports<'@storybook/react/preview'>;
}
declare module '@storybook/react/template/cli/js/Button.jsx' {
  declare module.exports: $Exports<'@storybook/react/template/cli/js/Button'>;
}
declare module '@storybook/react/template/cli/js/Button.stories.js' {
  declare module.exports: $Exports<'@storybook/react/template/cli/js/Button.stories'>;
}
declare module '@storybook/react/template/cli/js/Header.jsx' {
  declare module.exports: $Exports<'@storybook/react/template/cli/js/Header'>;
}
declare module '@storybook/react/template/cli/js/Header.stories.js' {
  declare module.exports: $Exports<'@storybook/react/template/cli/js/Header.stories'>;
}
declare module '@storybook/react/template/cli/js/Page.jsx' {
  declare module.exports: $Exports<'@storybook/react/template/cli/js/Page'>;
}
declare module '@storybook/react/template/cli/js/Page.stories.js' {
  declare module.exports: $Exports<'@storybook/react/template/cli/js/Page.stories'>;
}
declare module '@storybook/react/template/components/index' {
  declare module.exports: $Exports<'@storybook/react/template/components'>;
}
declare module '@storybook/react/template/components/index.js' {
  declare module.exports: $Exports<'@storybook/react/template/components'>;
}
declare module '@storybook/react/template/stories/docgen-components/imported.js' {
  declare module.exports: $Exports<'@storybook/react/template/stories/docgen-components/imported'>;
}
declare module '@storybook/react/template/stories/docgen-components/js-proptypes/ext.js' {
  declare module.exports: $Exports<'@storybook/react/template/stories/docgen-components/js-proptypes/ext'>;
}
