// flow-typed signature: d2514da1718290bdd385f85b7b942eda
// flow-typed version: <<STUB>>/@storybook/react-webpack5_v^10.1.11/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/react-webpack5'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/react-webpack5' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/react-webpack5/dist' {
  declare module.exports: any;
}

declare module '@storybook/react-webpack5/dist/node' {
  declare module.exports: any;
}

declare module '@storybook/react-webpack5/dist/preset' {
  declare module.exports: any;
}

declare module '@storybook/react-webpack5/preset' {
  declare module.exports: any;
}

declare module '@storybook/react-webpack5/template/cli/js/Button' {
  declare module.exports: any;
}

declare module '@storybook/react-webpack5/template/cli/js/Button.stories' {
  declare module.exports: any;
}

declare module '@storybook/react-webpack5/template/cli/js/Header' {
  declare module.exports: any;
}

declare module '@storybook/react-webpack5/template/cli/js/Header.stories' {
  declare module.exports: any;
}

declare module '@storybook/react-webpack5/template/cli/js/Page' {
  declare module.exports: any;
}

declare module '@storybook/react-webpack5/template/cli/js/Page.stories' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/react-webpack5/dist/index' {
  declare module.exports: $Exports<'@storybook/react-webpack5/dist'>;
}
declare module '@storybook/react-webpack5/dist/index.js' {
  declare module.exports: $Exports<'@storybook/react-webpack5/dist'>;
}
declare module '@storybook/react-webpack5/dist/node/index' {
  declare module.exports: $Exports<'@storybook/react-webpack5/dist/node'>;
}
declare module '@storybook/react-webpack5/dist/node/index.js' {
  declare module.exports: $Exports<'@storybook/react-webpack5/dist/node'>;
}
declare module '@storybook/react-webpack5/dist/preset.js' {
  declare module.exports: $Exports<'@storybook/react-webpack5/dist/preset'>;
}
declare module '@storybook/react-webpack5/preset.js' {
  declare module.exports: $Exports<'@storybook/react-webpack5/preset'>;
}
declare module '@storybook/react-webpack5/template/cli/js/Button.jsx' {
  declare module.exports: $Exports<'@storybook/react-webpack5/template/cli/js/Button'>;
}
declare module '@storybook/react-webpack5/template/cli/js/Button.stories.js' {
  declare module.exports: $Exports<'@storybook/react-webpack5/template/cli/js/Button.stories'>;
}
declare module '@storybook/react-webpack5/template/cli/js/Header.jsx' {
  declare module.exports: $Exports<'@storybook/react-webpack5/template/cli/js/Header'>;
}
declare module '@storybook/react-webpack5/template/cli/js/Header.stories.js' {
  declare module.exports: $Exports<'@storybook/react-webpack5/template/cli/js/Header.stories'>;
}
declare module '@storybook/react-webpack5/template/cli/js/Page.jsx' {
  declare module.exports: $Exports<'@storybook/react-webpack5/template/cli/js/Page'>;
}
declare module '@storybook/react-webpack5/template/cli/js/Page.stories.js' {
  declare module.exports: $Exports<'@storybook/react-webpack5/template/cli/js/Page.stories'>;
}
