// flow-typed signature: c4693a0348ed5989a70f1472e4e10f77
// flow-typed version: <<STUB>>/@storybook/react_v^7.1.1/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/react/dist/config' {
  declare module.exports: any;
}

declare module '@storybook/react/dist' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/preset' {
  declare module.exports: any;
}

declare module '@storybook/react/jest.config' {
  declare module.exports: any;
}

declare module '@storybook/react/preset' {
  declare module.exports: any;
}

declare module '@storybook/react/preview' {
  declare module.exports: any;
}

declare module '@storybook/react/template/cli/js/Button' {
  declare module.exports: any;
}

declare module '@storybook/react/template/cli/js/Button.stories' {
  declare module.exports: any;
}

declare module '@storybook/react/template/cli/js/Header' {
  declare module.exports: any;
}

declare module '@storybook/react/template/cli/js/Header.stories' {
  declare module.exports: any;
}

declare module '@storybook/react/template/cli/js/Page' {
  declare module.exports: any;
}

declare module '@storybook/react/template/cli/js/Page.stories' {
  declare module.exports: any;
}

declare module '@storybook/react/template/components/Button' {
  declare module.exports: any;
}

declare module '@storybook/react/template/components/Form' {
  declare module.exports: any;
}

declare module '@storybook/react/template/components/Html' {
  declare module.exports: any;
}

declare module '@storybook/react/template/components' {
  declare module.exports: any;
}

declare module '@storybook/react/template/components/Pre' {
  declare module.exports: any;
}

declare module '@storybook/react/template/stories/docgen-components/8140-js-prop-types-oneof/input' {
  declare module.exports: any;
}

declare module '@storybook/react/template/stories/docgen-components/8428-js-static-prop-types/input' {
  declare module.exports: any;
}

declare module '@storybook/react/template/stories/docgen-components/9023-js-hoc/input' {
  declare module.exports: any;
}

declare module '@storybook/react/template/stories/docgen-components/9399-js-proptypes-shape/input' {
  declare module.exports: any;
}

declare module '@storybook/react/template/stories/docgen-components/9586-js-react-memo/input' {
  declare module.exports: any;
}

declare module '@storybook/react/template/stories/docgen-components/9626-js-default-values/input' {
  declare module.exports: any;
}

declare module '@storybook/react/template/stories/docgen-components/9668-js-proptypes-no-jsdoc/input' {
  declare module.exports: any;
}

declare module '@storybook/react/template/stories/docgen-components/imported' {
  declare module.exports: any;
}

declare module '@storybook/react/template/stories/docgen-components/js-class-component/input' {
  declare module.exports: any;
}

declare module '@storybook/react/template/stories/docgen-components/js-function-component-inline-defaults-no-propTypes/input' {
  declare module.exports: any;
}

declare module '@storybook/react/template/stories/docgen-components/js-function-component-inline-defaults/input' {
  declare module.exports: any;
}

declare module '@storybook/react/template/stories/docgen-components/js-function-component/input' {
  declare module.exports: any;
}

declare module '@storybook/react/template/stories/docgen-components/js-proptypes/ext' {
  declare module.exports: any;
}

declare module '@storybook/react/template/stories/docgen-components/js-proptypes/input' {
  declare module.exports: any;
}

declare module '@storybook/react/template/stories/docgen-components/jsdoc/input' {
  declare module.exports: any;
}

declare module '@storybook/react/template/stories/js-argtypes.stories' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/react/dist/config.js' {
  declare module.exports: $Exports<'@storybook/react/dist/config'>;
}
declare module '@storybook/react/dist/index' {
  declare module.exports: $Exports<'@storybook/react/dist'>;
}
declare module '@storybook/react/dist/index.js' {
  declare module.exports: $Exports<'@storybook/react/dist'>;
}
declare module '@storybook/react/dist/preset.js' {
  declare module.exports: $Exports<'@storybook/react/dist/preset'>;
}
declare module '@storybook/react/jest.config.js' {
  declare module.exports: $Exports<'@storybook/react/jest.config'>;
}
declare module '@storybook/react/preset.js' {
  declare module.exports: $Exports<'@storybook/react/preset'>;
}
declare module '@storybook/react/preview.js' {
  declare module.exports: $Exports<'@storybook/react/preview'>;
}
declare module '@storybook/react/template/cli/js/Button.jsx' {
  declare module.exports: $Exports<'@storybook/react/template/cli/js/Button'>;
}
declare module '@storybook/react/template/cli/js/Button.stories.js' {
  declare module.exports: $Exports<'@storybook/react/template/cli/js/Button.stories'>;
}
declare module '@storybook/react/template/cli/js/Header.jsx' {
  declare module.exports: $Exports<'@storybook/react/template/cli/js/Header'>;
}
declare module '@storybook/react/template/cli/js/Header.stories.js' {
  declare module.exports: $Exports<'@storybook/react/template/cli/js/Header.stories'>;
}
declare module '@storybook/react/template/cli/js/Page.jsx' {
  declare module.exports: $Exports<'@storybook/react/template/cli/js/Page'>;
}
declare module '@storybook/react/template/cli/js/Page.stories.js' {
  declare module.exports: $Exports<'@storybook/react/template/cli/js/Page.stories'>;
}
declare module '@storybook/react/template/components/Button.jsx' {
  declare module.exports: $Exports<'@storybook/react/template/components/Button'>;
}
declare module '@storybook/react/template/components/Form.jsx' {
  declare module.exports: $Exports<'@storybook/react/template/components/Form'>;
}
declare module '@storybook/react/template/components/Html.jsx' {
  declare module.exports: $Exports<'@storybook/react/template/components/Html'>;
}
declare module '@storybook/react/template/components/index' {
  declare module.exports: $Exports<'@storybook/react/template/components'>;
}
declare module '@storybook/react/template/components/index.js' {
  declare module.exports: $Exports<'@storybook/react/template/components'>;
}
declare module '@storybook/react/template/components/Pre.jsx' {
  declare module.exports: $Exports<'@storybook/react/template/components/Pre'>;
}
declare module '@storybook/react/template/stories/docgen-components/8140-js-prop-types-oneof/input.jsx' {
  declare module.exports: $Exports<'@storybook/react/template/stories/docgen-components/8140-js-prop-types-oneof/input'>;
}
declare module '@storybook/react/template/stories/docgen-components/8428-js-static-prop-types/input.jsx' {
  declare module.exports: $Exports<'@storybook/react/template/stories/docgen-components/8428-js-static-prop-types/input'>;
}
declare module '@storybook/react/template/stories/docgen-components/9023-js-hoc/input.jsx' {
  declare module.exports: $Exports<'@storybook/react/template/stories/docgen-components/9023-js-hoc/input'>;
}
declare module '@storybook/react/template/stories/docgen-components/9399-js-proptypes-shape/input.jsx' {
  declare module.exports: $Exports<'@storybook/react/template/stories/docgen-components/9399-js-proptypes-shape/input'>;
}
declare module '@storybook/react/template/stories/docgen-components/9586-js-react-memo/input.jsx' {
  declare module.exports: $Exports<'@storybook/react/template/stories/docgen-components/9586-js-react-memo/input'>;
}
declare module '@storybook/react/template/stories/docgen-components/9626-js-default-values/input.jsx' {
  declare module.exports: $Exports<'@storybook/react/template/stories/docgen-components/9626-js-default-values/input'>;
}
declare module '@storybook/react/template/stories/docgen-components/9668-js-proptypes-no-jsdoc/input.jsx' {
  declare module.exports: $Exports<'@storybook/react/template/stories/docgen-components/9668-js-proptypes-no-jsdoc/input'>;
}
declare module '@storybook/react/template/stories/docgen-components/imported.js' {
  declare module.exports: $Exports<'@storybook/react/template/stories/docgen-components/imported'>;
}
declare module '@storybook/react/template/stories/docgen-components/js-class-component/input.jsx' {
  declare module.exports: $Exports<'@storybook/react/template/stories/docgen-components/js-class-component/input'>;
}
declare module '@storybook/react/template/stories/docgen-components/js-function-component-inline-defaults-no-propTypes/input.jsx' {
  declare module.exports: $Exports<'@storybook/react/template/stories/docgen-components/js-function-component-inline-defaults-no-propTypes/input'>;
}
declare module '@storybook/react/template/stories/docgen-components/js-function-component-inline-defaults/input.jsx' {
  declare module.exports: $Exports<'@storybook/react/template/stories/docgen-components/js-function-component-inline-defaults/input'>;
}
declare module '@storybook/react/template/stories/docgen-components/js-function-component/input.jsx' {
  declare module.exports: $Exports<'@storybook/react/template/stories/docgen-components/js-function-component/input'>;
}
declare module '@storybook/react/template/stories/docgen-components/js-proptypes/ext.js' {
  declare module.exports: $Exports<'@storybook/react/template/stories/docgen-components/js-proptypes/ext'>;
}
declare module '@storybook/react/template/stories/docgen-components/js-proptypes/input.jsx' {
  declare module.exports: $Exports<'@storybook/react/template/stories/docgen-components/js-proptypes/input'>;
}
declare module '@storybook/react/template/stories/docgen-components/jsdoc/input.jsx' {
  declare module.exports: $Exports<'@storybook/react/template/stories/docgen-components/jsdoc/input'>;
}
declare module '@storybook/react/template/stories/js-argtypes.stories.jsx' {
  declare module.exports: $Exports<'@storybook/react/template/stories/js-argtypes.stories'>;
}
