// flow-typed signature: 372e4e8099da1385f42d255c65b69223
// flow-typed version: <<STUB>>/@storybook/testing-library_v^0.1.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/testing-library'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/testing-library' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/testing-library/dist/cjs' {
  declare module.exports: any;
}

declare module '@storybook/testing-library/dist/esm' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/testing-library/dist/cjs/index' {
  declare module.exports: $Exports<'@storybook/testing-library/dist/cjs'>;
}
declare module '@storybook/testing-library/dist/cjs/index.js' {
  declare module.exports: $Exports<'@storybook/testing-library/dist/cjs'>;
}
declare module '@storybook/testing-library/dist/esm/index' {
  declare module.exports: $Exports<'@storybook/testing-library/dist/esm'>;
}
declare module '@storybook/testing-library/dist/esm/index.js' {
  declare module.exports: $Exports<'@storybook/testing-library/dist/esm'>;
}
