// flow-typed signature: 2e3cf5cde61d90d266776d2a35b12326
// flow-typed version: <<STUB>>/@storybook/testing-library_v^0.2.0/flow_v0.203.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/testing-library'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/testing-library' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/testing-library/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/testing-library/dist/index' {
  declare module.exports: $Exports<'@storybook/testing-library/dist'>;
}
declare module '@storybook/testing-library/dist/index.js' {
  declare module.exports: $Exports<'@storybook/testing-library/dist'>;
}
