on:
  pull_request:
    branches:
    - master
    types: [opened, edited]
name: Prettier
jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: yarn install --frozen-lockfile --non-interactive
    - run: yarn install --frozen-lockfile --non-interactive
    - run: node_modules/.bin/prettier --write src/**/*.js
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Fix style errors with prettier" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
